### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Chocimier**
Hello!
I have found some bugs and fixed it. I didn't find them on mantis buglist.

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
Thanks for contributing!

I'll do a bit more testing and merge it if everything is okay. For now this pull request is fine, but in future please consider to create separate branches and pull request for different bugs / features.

**Comment by ArseniyShestakov** [comment]
In case you want to dig in VCMI code a bit more here is few things in CGShrine::onHeroVisit:

- Hero might have spell without sufficient wisdom to learn it so check for exist spell should be first. 
- In fact when you give all spells to hero with "vcmiistari" cheat and visit Shrine it's still show you that spell is given to hero.

**Comment by ArseniyShestakov** [comment]
Some interesting Issues related to building requrements: [2162](http://bugs.vcmi.eu/view.php?id=2161), [2321](http://bugs.vcmi.eu/view.php?id=2321).

They probably not related to what fixed there so if you want to fix them please use different branch / PR.

**Comment by Chocimier** [comment]
Thanks for merging :)

I am working on [2321](http://bugs.vcmi.eu/view.php?id=2321).  
[2161](http://bugs.vcmi.eu/view.php?id=2161) is fixed fom some time.
[Cheat need to be discussed](http://bugs.vcmi.eu/view.php?id=2468).

**Comment by ArseniyShestakov** [comment]
Sorry then about cheat. I had to check myself how it's implemented, but thought there some bug in code.

**Pull request merged**
