### PR TITLE
Mutex relax fix

### PR DESCRIPTION
**Pull request by DjWarmonger**

### CODE REVIEW

**Comment by alexvins** [comment]
Random crash at mapHandler.cpp:861. Look like uninitialized obj field of tile.objects.

**Comment by DjWarmonger** [comment]
I know there is random crash after mapHandler::hideObject was simplified, hoping to fix it.

**Comment by DjWarmonger** [comment]
The issue is caused by empty def name - but don't know how it could get empty.

**Comment by IvanSavenko** [comment]
This may be caused by
a) normal objects - object defined in h3m with missing .def file (corrupted map, unlikely)
b) random objects - there is mechanism that during object randomization stage will try to find appearance from it. Maybe it fails in some cases? Or appearance for this object is not defined in objects.txt / json config?
c) towns - they may change their appearance based on built buildings (village, fort, capitol). Perhaps this mechanism is faulty or it fails to find acceptable appearance for a town?

**Comment by DjWarmonger** [comment]
I got it on fixed stack on random map http://bugs.vcmi.eu/view.php?id=1647 - troll at (7,71,1). Reproductible on new game and save as well. The map itself is SoD random map, but bug occurs on VCMI random maps as well.

**Comment by ArseniyShestakov** [comment]
BTW is this one still need some work or testing?

**Comment by DjWarmonger** [comment]
I think I will revert the part with adventure map hiding or put it into another branch. Other improvements are useful and work well.

**Comment by DjWarmonger** [comment]
I think it's ready now for merge and works nicely.

**Comment by ArseniyShestakov** [comment]
Tested with autoskip and everything looks fine.

**Pull request merged**
