### PR TITLE
Noncopyable bonus system node

### PR DESCRIPTION
**Pull request by alexvins**
Refactored with noncopyable CBonusSystemNode. Save format changed, no backward compatibility.
Should fix many serialisation related bugs. Deep testing required.

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
I'm extensively testing that one last ~12 hours, so far it's working good for AI-only games and clearly don't break anything. There was no corrupted game saves yet, but as I find out before these was tricky to reproduce so it's hard to say if it's fully fixed or not.

**Comment by ArseniyShestakov** [comment]
So other day of testing passed and I think it's actually fixed the problem. :+1:

**Comment by alexvins** [comment]
What next: deside when to break save compatibility at merge or try to retain icompatibility?

**Comment by DjWarmonger** [comment]
I think it will be fine to break save compatibiliy with 0.99 release.

**Comment by alexvins** [comment]
Also I think that cherry pick 3c9d84c is a good idea

**Comment by alexvins** [comment]
As I`m retaining it even with new map format, may be try to do that here also.

**Comment by ArseniyShestakov** [comment]
Then it's would be good to have one more development build in between. Though I'm want to fix several crashes / freezes first.

**Comment by alexvins** [comment]
@ArseniyShestakov as 0.99 should be with map format and editor, you have some time (1-2 dev releases) for fixes ;)

**Comment by alexvins** [comment]
As for this branch, I may be try hard way - with move constructors for some classes and in separate branch starting from 3c9d84c, if it succeed, this one will be deleted.

**Comment by alexvins** [comment]
See https://github.com/vcmi/vcmi/pull/202

**Pull request closed without merging**
