### PR TITLE
Mapselection - popup

### PR DESCRIPTION
**Pull request by Laserlicht**
another HD thing...

grafik
grafik

### CODE REVIEW

**Comment by dydzio0614** [comment]
Looks promising

**Comment by Laserlicht** [comment]
Added some descriptions.

`std::format` has minimum requirement of C++20. Also there is some condition... :(

grafik

**Comment by DjWarmonger** [comment]
Yes, but we've got boost::format for that.

**Comment by DjWarmonger** [comment]
Also, if it's from HD mod, you may want to add it to the list: https://github.com/orgs/vcmi/projects/2

**Comment by krs0** [comment]
Filename:  
And
Creation Date:
Are just noise in that popup. The information can be understood without that extra words.

At minimum Creation Date could be replaced with with Last Save: or Save Date:

**Comment by IvanSavenko** [comment]
@krs0 Perhaps. But it makes this dialog look a little bit organized and not look like randomly placed set of words.

@DjWarmonger Yeah, it is, but I think only people with write access can add issue to project. Added.

**Review by IvanSavenko — APPROVED** [review]

**Pull request merged**
