### PR TITLE
turn indicator

### PR DESCRIPTION
**Pull request by Laserlicht**
grafik
grafik

### CODE REVIEW

**Comment by dydzio0614** [comment]
maybe the small size will not satisfy everybody but good addition overall...

**Comment by Laserlicht** [comment]
> maybe the small size will not satisfy everybody but good addition overall...

Yeah, but disabling for the small is also not good, I think.

The HD way I don't want to choose, because handling the StackQueue is a pain.

**Comment by IvanSavenko** [comment]
Would be nice to add word "turn" somewhere for clarity. If we don't go hd mod approach then perhaps something like this?

Might use a bit more of vertical space though...
зображення

**Comment by Laserlicht** [comment]
I didn't feel it was necessary. Was self-explanatory for me in the game.
The bar has one major disadvantage. It hides the units (the small rectangle also, but not that much).


https://github.com/vcmi/vcmi/assets/13953785/2db951ed-1902-4dce-9cce-234e56298b06

**Comment by Laserlicht** [comment]
Simplified it in small mode:

grafik

I think it's better like this.

**Comment by krs0** [comment]
Its more than enough to work with until a HD mod like will be implemented in the far future.

Thanks for the addition, sometimes I really wanted an indicator when a torn will end.

**Comment by Laserlicht** [comment]
> Is it possible to color the bar separating turns in big version as well? Something more toned down though... like dark grey or something?

Basically it's possible. But I think it doesn't look really good. Tested a little bit in GIMP.

**Pull request merged**
