### PR TITLE
Added option for saving generated maps on client side

### PR DESCRIPTION
**Pull request by alexvins**
* new configuration option 'general.saveRandomMaps'
* maps being saved to 'userCachePath/RandomMaps'
* no deletion of old random maps
* map filename generated based on template name and random seed

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
Can't start game on saved maps: all player slots marked as computer-only.

**Comment by alexvins** [comment]
> 2017-Jun-04 20:23:01.018554 INFO global [1b68] - Final player config: 8 total, 8 cpu-only

This is how RMG works

**Comment by ArseniyShestakov** [comment]
Then no reason not to merge. I'll try to fix UI after then.

**Comment by alexvins** [comment]
The thing is that player options are partly ignored for random map - StartInfo is used instead that why this bug never appears before.

**Comment by ArseniyShestakov** [comment]
Yeah both UI and RMG need some work. When this one merged I'll try to implement proper restart so saved map can be used. E.g in H3 client doesn't re-generate map, but change seed and restart it.

**Comment by ArseniyShestakov** [comment]
Yeah both UI and RMG need some work. When this one merged I'll try to implement proper restart so saved map can be used. E.g in H3 client doesn't re-generate map, but change seed and restart it.

**Pull request merged**
