### PR TITLE
Add basic system to give more advantages for ai player

### PR DESCRIPTION
**Pull request by Nordsoft91**
Probably resolves https://github.com/vcmi/vcmi/issues/2879 and https://github.com/vcmi/vcmi/issues/1931

Bonuses themselves are for reference only, will be removed. It's up to modders to find proper balance

### CODE REVIEW

**Comment by Nordsoft91** [comment]
> Can we add global/permanent bonuses in addition to per-battle bonuses?

There is similar functionality already, but I'll check

> Can we add bonuses separately for battles vs neutrals and for battles vs other players? To make it easier for AI to clear monsters without obvious cheats in player-vs-player battles.

Do we need bonuses vs other players? I implemented only vs neutrals exactly to hide actual cheating from players

**Comment by dydzio0614** [comment]
Maybe it should be separate difficulty slider, somewhere near ingame difficulty picker or in launcher (off/1/2/3/4/5/based on primary difficulty).

Also not sure how many examples from #1931 can be implemented exclusively via bonus system, i would be OK with hardcoding the rest since most of them exist either in H4 enhancement mod or H5 AI so they feel like pretty standard AI code extensions to me.

**Comment by IvanSavenko** [comment]
> There is similar functionality already, but I'll check

There is similar functionality indeed. But it can't be configured separately for AI's and human players.

> Do we need bonuses vs other players? I implemented only vs neutrals exactly to hide actual cheating from players

Ah, missed check for neutrals. Looks OK in this case.

**Comment by krs0** [comment]
The final solution would be to decouple AI difficulty from starting resources. 2 separate options.
This way even 2 human players could play with same AI but different starting resources. Some kind of handicap system.

**Comment by krs0** [comment]
No need to give attack or defense boost o AI in battle, if AI does well on map.

Lets boost AI on map and then this battle boost is not needed.

**Comment by dydzio0614** [comment]
i think we need to be able to add as many arbitrary boost types as possible

**Comment by DjWarmonger** [comment]
> No need to give attack or defense boost o AI in battle, if AI does well on map.
> 
> Lets boost AI on map and then this battle boost is not needed.

But adventure AI is way better than battle AI, and the reason AI player struggles is that it loses many units in the battle.

**Comment by dydzio0614** [comment]
i agree with @DjWarmonger , though "better" is relative - adventure AI by definition has to be much more complicated due to wider range of responsibilities, and "weak battle AI" such as stupidAI has low chances of ruining game for average players, while bad adventure map AI will just make game non-challenging at all, due to the scope at which these AI's influence the gameplay

**Comment by luk3ZPL** [comment]
"more hero movement per turn etc." it is a AI personality feature in vanilla H3.
Cheating should be optional in my opinion.

**Comment by Nordsoft91** [comment]
let's start with what we have. Boost AI mod is already available. I believe it's challenging enough even on "rook" difficulty

**Pull request merged**
