### PR TITLE
VCAI: hard limit on iterations per turn

### PR DESCRIPTION
**Pull request by nullkiller**
Simple hack to workaround freezes in VCAI

### CODE REVIEW

**Comment by dydzio0614** [comment]
Few questions:
Is size 30 enough? Won't it trigger in legit situations a lot when there is no infinite loop?
Maybe add log message if size exceeded? These bugs should be eventually fixed "proper way"?
Add comment that it is workaround that hides potential bugs?

**Comment by nullkiller** [comment]
> Few questions: Is size 30 enough? Won't it trigger in legit situations a lot when there is no infinite loop? Wouldn't 1000 etc. be more appropriate? Maybe add log message if size exceeded as these bugs should be eventually fixed "proper way"? Add comment that it is workaround that hides potential bugs?

Who knows. NKAI has this feature already. And regarding logs I am not sure they are efficient enough. Nobody cares until it crash/hang. Sure log is needed. I will consider adding it maybe.
30 is enough. It also does not touch wandering so 30 is enough for sure. Big value will cause hanging which will irritate people.

**Comment by DjWarmonger** [comment]
Good spot. There used to be a limit to goal decomposition depth, but it is not sufficient with overhauled architeture.,

**Comment by IvanSavenko** [comment]
@nullkiller  Merge? Or is this waiting for something?

**Comment by IvanSavenko** [comment]
@nullkiller another ping. Should this be merged or not?

**Pull request merged**
