### PR TITLE
Bonus: prism breath

### PR DESCRIPTION
**Pull request by Laserlicht**
Requested by @by003 for modding

[Peek 2024-10-20 21-57.webm](https://github.com/user-attachments/assets/f296e2c9-6e7d-4369-832a-d546113bbe52)

### CODE REVIEW

**Comment by Alucard648** [comment]
What about expanding this bonus to allow arbitrary attack patterns?

**Comment by Laserlicht** [comment]
> What about expanding this bonus to allow arbitrary attack patterns?

Not sure how we could configure this... Of course we could some binary translation to a single number. But that wouldn't be self explaining...

**Comment by Alucard648** [comment]
Apparently, a table consisting of hex positions (relative to attack spot) and damage modifiers for each spot, ala H5.

**Comment by IvanSavenko** [comment]
Not sure if we need yet another type of multi-tile attack. We have what, 3 of them already? Cerberi, Dragons, and one from wog.

Perhaps we can encode pattern in bonus addinfo? And convert existing bonuses to such form.

We have EDir enum which specifies one of 6 possible direction. So we can specify addInfo as list of trasformations.
For example, Dragon Breath = clone primary attack hex in right / east direction (with obvious adjustment if attack comes from another direction). Cerberi multi-head attack = clone primary hex to top-left, clone primary hex to bottom-left, etc.

**Comment by Laserlicht** [comment]
Yes. Should be possible to combine:
- TWO_HEX_ATTACK_BREATH
- WIDE_BREATH
- PRISM_HEX_ATTACK_BREATH

However `THREE_HEADED_ATTACK` needs another config. It doesn't attack own units...

**Pull request merged**
