### PR TITLE
Better fix for allowed heroes on h3m maps

### LINKED ISSUE #3215: Cove heroes cannot be chosen in ROE,AB and SOD format maps
I don't know whether it occurs in other's game, it really occurs in my game with latest daily build.
image
Although I chose cove town as my fraction, but heroes from this alignment cannot be selected, and then, a castle hero was given by the system. 

**Version**
 - OS: Windows
 - Version: 1.4.0 daily build in 22nd of November

### PR DESCRIPTION
**Pull request by IvanSavenko**
- Fixes #3215

### CODE REVIEW

**Comment by krs0** [comment]
Will these changes work in case no heroes or no artifacts?

**Comment by IvanSavenko** [comment]
What do you mean? No heroes or no artifacts?

**Comment by krs0** [comment]
Both :). The question comes from SW mods perspective, where no objects are needed.

What I was thinking, if it would be possible when touching code, to accomodate stuff that is not possible atm in VCMI

Not going out of the way to do it... but gradually eliminate some limitations.

**Comment by IvanSavenko** [comment]
Not sure what's going on with SW mod, but this is fix for a regression. So should work as in 1.3

**Pull request merged**
