### PR TITLE
Preserve order of secondary skills during hero json serialization/deserialization

### LINKED ISSUE #2507: Hero skills have different order in campaigns
**Describe the bug**
A relatively minor bug, but still a bug :) the hero has a different skill order in the second map of a campaign than in the first one.

**To Reproduce**
1. Finish a campaign's map

**Expected behavior**
Skills should have the same order regardless map

**Actual behavior**
Skills have a different order

**Did it work earlier?**
don't think so

**Screenshots**
first map
Screenshot_20230807_171654

second map
Screenshot_20230807_171734

**Version**
 - OS: Linux
 - Version: 1.3

### PR DESCRIPTION
**Pull request by wb180**
Serialization will use this syntax:
```
"secondarySkills" :
[ 
    {"core:wisdom":"expert"},
    {"core:logistics":"basic"},
    {"core:waterMagic":"advanced"},
    {"core:offence":"expert"}
]
```
to keep the order of skills, while deserialization can use either new or the old one(so nothing is broken)

Closes #2507

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Hi. Thanks for the fix. Can you change format to this one?
```
"secondarySkills" :
[ 
    { "skill" : "core:wisdom", "level" : "expert"},
...
```
This is more in line with how we handle similar cases

**Comment by wb180** [comment]
> Hi. Thanks for the fix. Can you change format to this one?

Yes, will look into it

**Comment by wb180** [comment]
Format changed

**Review by IvanSavenko — APPROVED** [review]

**Comment by IvanSavenko** [comment]
Looks OK, however will merge after 1.3.1 release, just in case. Relatively minor bug after all.

**Pull request merged**
