### PR TITLE
Fix market of time, crashes game

### PR DESCRIPTION
**Pull request by nullkiller**
Sample map. Visiting market of time was crashing game.
[SoD_Dzien_wistaka.zip](https://github.com/vcmi/vcmi/files/12445430/SoD_Dzien_wistaka.zip)

image

### CODE REVIEW

**Comment by dydzio0614** [comment]
I would probably target beta with this fix

**Comment by nullkiller** [comment]
Might be so this bug is here for ages)

**Comment by IvanSavenko** [comment]
FYI - there is Market of Time on default map, "Titan's Winter"

As for a bug itself - should probably be fixed in a different way. If vcmi encounters unknown object it shouldn't crash. Some weird user-made maps have H3 objects with weird sub ID (which vcmi is not aware of). 
Wog maps also definitely have objects that vcmi is not aware of

**Comment by nullkiller** [comment]
This one has valid subid of 0. And visible on the map. Because it is a part of original heroes files. Regarding other objects we should either handle them with valid JSON or skip during loading so they no longer present after map starting

**Comment by nullkiller** [comment]
For instance we can allow some way to specify template for all possible subids or whatever. I just got crash, just fixed it. The thing you suggest is a bit bigger.

**Comment by IvanSavenko** [comment]
What exactly caused crash?
Unsupported objects should be created as CGObjectInstance with no-op heroVisit method

**Comment by nullkiller** [comment]
Mostly attempt to log it somewhere) It asks object name and crashes

**Comment by nullkiller** [comment]
Also AI turn crashes with message can not find handler for 50:0

**Comment by IvanSavenko** [comment]
> Mostly attempt to log it somewhere) It asks object name and crashes

We do have some checks for for non-existing handlers. But clearly not enough. Might be better to return some empty/default handler for such cases instead of hunting down every unchecked access.

Not against this PR as a quick fix measure though.

**Pull request merged**
