### PR TITLE
Bonuses fixes

### PR DESCRIPTION
**Pull request by IvanSavenko**
Fixes to issues discovered by @krs0 when updating mods to 1.4:
- Added new TERRAIN_NATIVE bonus for use in place of NO_TERRAIN_PENALTY bonus since native terrain and terrain penalty are separate concepts (for Cove Lodestar)
- SPELL_DURATION now allows subtypes. If set to spell, bonus will only affect specified spell
- Added documentation for NEGATIVE_EFFECTS_IMMUNITY, bonus now correctly loads subtype (spell school)

@krs0 please confirm that everything is OK now and I have not missed anything

### CODE REVIEW

**Comment by rilian-la-te** [comment]
@IvanSavenko what is a difference berween native terrain and terrain penalty for Lodestar?

**Comment by IvanSavenko** [comment]
Native terrain is way more than just terrain penalties:
- no terrain penalties 
- +1 to attack/defense/speed 
- mines/quicksand visibilty

**Comment by krs0** [comment]
Looks ok at mod loading.
These 2 remain:

[ ] MIND_IMMUNITY needs Subtype for only negative spells: (EG: Immune to all negative mind spells)

```
"bonus" :
                {
                    "type" : "MIND_IMMUNITY", //powinno być Not Immune Beneficial Mind Spells 
                    "subtype" : 1 //all except positive - może nie działać
                },
```
https://github.com/vcmi/vcmi/blob/develop/docs/modders/Bonus/Bonus_Types.md#mind_immunity

- [ ] LEVEL_SPELL_IMMUNITY to be able to specify school as well. (EG: Immune to all level 1 Ari Magic spells)

```
"bonus" :
                {
                    "type" : "LEVEL_SPELL_IMMUNITY",
                    "subtype" : 1 
                },
```

**Comment by rilian-la-te** [comment]
@IvanSavenko but is it wor with your changes?

And, is there a case, when creatures do not have terrain penalty and terrain is not native? Can Nomads see mines in sand?

**Comment by IvanSavenko** [comment]
> And, is there a case, when creatures do not have terrain penalty and terrain is not native? Can Nomads see mines in sand?

https://heroes.thelazy.net//index.php/Nomad

No, they don't get native terrain advantages

**Comment by rilian-la-te** [comment]
@IvanSavenko seems reasonable then to add a new bonus.

**Comment by krs0** [comment]
- [ ] GENERAL_ATTACK_REDUCTION Should support subtypes

EG: Used in ToW dryad for example
```
damageTypeAll; // -1
damageTypeMelee; // 0
damageTypeRanged; // 1
```

**Comment by IvanSavenko** [comment]
@krs0 All these cases are not regressions, but rather bonuses that never worked as intended (or worked in some ancient versions). The only change is that vcmi can now detect such cases.

So probably merging as it, unless more stuff is found

**Comment by krs0** [comment]
Maybe list the ones missing in a separate issue?

**Comment by IvanSavenko** [comment]
> Maybe list the ones missing in a separate issue?

Up to you I guess?
To be honest not really interested in expanding modding functionality unless I need this functionality in base game.
And it is not like we can implement every request from every modder.

**Pull request merged**
