### PR TITLE
Battle actions refactoring

### LINKED ISSUE #1502: During archangel's turn highlighting creatures does not show blue border
**Describe the bug**
During archangel's turn highlighting creatures does not show blue border

**To Reproduce**
1. Use vcmiainur cheat during adventure map to get some archangels
2. Start any battle
3. Make sure your archangel is creature currently making turn
4. Hover mouse over opponent or another ally creature - no blue border

**Expected behavior**
Blue border should appear around creature 2D sprite

**Actual behavior**
No border around creature

**Did it work earlier?**
I do not remember

**Screenshots**
obraz

**Version**
 - OS: Kubuntu 22.04
 - Version: current develop

### LINKED ISSUE #1503: Two-hex creature spellcaster should have only one hex darkened on mouse hover after pressing F button for casting mode
**Describe the bug**
When two hex unit is caster in battle, toggling casting mode (F keyboard button) should change mouse-hovered highlight mode to one hex

**To Reproduce**
1. Use vcmiainur cheat to get some archangels in army
2. Start any battle
3. Toggle on hex highlighting stuff in battle setting etc.
4. Press F during archangel's turn
5. Two hexes are still highlighted, which is good for movement logic but normal spell target is one hex in general

**Expected behavior**
One hex under cursor is highlighted in F mode

**Actual behavior**
Two hexes are highlighted

**Did it work earlier?**
I dont remember

**Screenshots**
obraz

**Version**
 - OS: Kubuntu 22.04
 - Version: current develop

### PR DESCRIPTION
**Pull request by IvanSavenko**
Changes: 
- Removed massive handleHex method that so far avoided refactoring
- Cleaned up handling of spellcaster creatures
- Fixes #1502
- Fixes #1503 
- Added HERO_INFO action that used for interaction with heroes in battle
- Hovering over hero now shows correct log message & cursor

### CODE REVIEW

**Comment by IvanSavenko** [comment]
PR ready, description updated to reflect changes

**Comment by dydzio0614** [comment]
1. Clicking hero doesn't open his spellbook anymore, works in develop
2. Melee attack cursor doesn't change to arrow after clicking enemy creature until move & attack animation finishes or non-battlefield object such as retreat button is hovered
3. Caster creature in F casting mode doesn't show blue border if target is invalid for spell. How does it work in H3 for faerie dragons trying to cast spell on black dragon?

non-branch related: does it look this way in H3? I mean darkening of green hex frames that are within area spell effect
obraz

**Comment by dydzio0614** [comment]
3rd point and screenshot thing not relevant anymore - checked in H3 and they work as they should, so only hero spellbook and melee attack cursors to fix

**Comment by IvanSavenko** [comment]
@dydzio0614 
Fixed these issues.

**Comment by dydzio0614** [comment]
Looks OK now

**Pull request merged**
