### PR TITLE
Launcher zhCN translation

### PR DESCRIPTION
**Pull request by tytannial**

### CODE REVIEW

**Comment by Nordsoft91** [comment]
@IvanSavenko , is there something else needed to add new language into the list?

**Comment by tytannial** [comment]
> 

I think....UTF8 :D

**Comment by IvanSavenko** [comment]
> @IvanSavenko , is there something else needed to add new language into the list?

New .ts files should also be added to list here:
https://github.com/vcmi/vcmi/blob/develop/launcher/CMakeLists.txt#L54

Other than that - Chinese is already added where necessary.

**Comment by tytannial** [comment]
done.

**Comment by IvanSavenko** [comment]
Looks to be working.

@tytannial 
Merging, so it will be part of our next release (1.3 most likely)

If you wish to use it in 1.2 then you can unpack this file into `launcher/translation` directory of your vcmi install.
[chinese.zip](https://github.com/vcmi/vcmi/files/11359216/chinese.zip)

**Comment by tytannial** [comment]
> Looks to be working.
> 
> @tytannial Merging, so it will be part of our next release (1.3 most likely)
> 
> If you wish to use it in 1.2 then you can unpack this file into `launcher/translation` directory of your vcmi install. [chinese.zip](https://github.com/vcmi/vcmi/files/11359216/chinese.zip)

I think that's good at next major release. there will be sufficient time to identify issues. After all, proofreading in translation work is a very important process. hopfully more fans join us.

**Pull request merged**
