### PR TITLE
video loop fix and missing videos/sounds for battle result

### LINKED ISSUE #2260: Bad loop for the evading video
**Describe the bug**
The deserting video after a battle is not looped as the original version. There was two parts for the video:

1. An introduction played once
2. A loop

So that we have the feeling that the video continues but do not restart.

**Game logs**

**To Reproduce**
1. Start a battle
2. Click on 'Desert'

**Expected behavior**
The animation starts and then loops.

**Actual behavior**
The animation loops entirely.

**Did it work earlier?**

**Screenshots**

**Version**
 - OS: Windows 10
 - Version: 1.2.1

**Additional context**

### LINKED ISSUE #2910: Animation of loosing a battle is cut
sci (2)

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI 1.3.2]

### PR DESCRIPTION
**Pull request by Laserlicht**
Fixes #2260 
Fixes #2910

### CODE REVIEW

**Review by Nordsoft91 — APPROVED** [review]

**Review by IvanSavenko — COMMENTED** [review]
Perhaps instead of retrieving current video form VideoHandler store all required information in BattleResultWindow?

1. Add `getAudioPath` method to BattleResults window that will return audio file for current battle
2. Add `getIntroVIdeoPath` method that will return video path for intro video
3. Add `getLoopedVideoPath` method that will return looped video name. 

Last method should probably be called once, on BattleResultWIndow construction and stored in member - battleResult might be destroyed after construction.

**Comment by Laserlicht** [comment]
Hmm. I'm not sure. The current solution uses the name already saved. Only add a function to get this.

It's more generic and maybe usable in other cases.

Do you think adding new functions would make the code more readable here? I think it's easy to understand.

**Comment by IvanSavenko** [comment]
> Do you think adding new functions (and overhead) would make the code more readable here? I think it's easy to understand.

Yes. Currently constructor does *a lot* of things. over 150 lines of code. 

For readability ~50 lines for a method is probably the limit - enough to fit into screen and look over entire method at once. Anything larger than that likely deserves looking into it and splitting into smaller methods.


Hmm...
Alternatively - perhaps create a separate method that will set both video name and audio path, to separate it from constructor?


In any case please remove video name from video handler - this is global state which is something to be avoided. For example it would prevent potential playback of multiple video files at once.

**Comment by Laserlicht** [comment]
@IvanSavenko Better like this?

**Pull request merged**
