### PR TITLE
smooth scroll fix and gui option to disable

### PR DESCRIPTION
**Pull request by Laserlicht**

### CODE REVIEW

**Comment by dydzio0614** [comment]
did not manually test but idea sounds good

**Comment by Laserlicht** [comment]
Keep in mind, that it only stops the current "animation" (to avoid overlapping).

**Comment by DjWarmonger** [comment]
Zuuzel already complainedit feels unnatural as it is.

But I like it, maybe make it optional feature?

**Comment by Laserlicht** [comment]
> Zuuzel already complainedit feels unnatural as it is.

I think that's very individual. When I used 1.3.2, it felt very unnatural to me. :D

> But I like it, maybe make it optional feature?

The option already existed. I have added it to the GUI. But I leave it active by default because
- we don't differentiate between mobile and desktop (on mobile it should be standard in any case)
- Map dragging is not an OH3 function anyway
- Map dragging (at least with links) is deactivated by default on the desktop anyway

**Pull request merged**
