### PR TITLE
Missing validation translations

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @IvanSavenko,

This PR translates missing captions for validations in French and Spanish and add the entries in the other languages.

PS: Is it possible to create a repository for the English translation? I have some fixes to do.

### CODE REVIEW

**Comment by IvanSavenko** [comment]
> PS: Is it possible to create a repository for the English translation? I have some fixes to do.

You mean this one?
https://github.com/vcmi-mods/h3-for-vcmi-englisation

**Comment by Fabrice-TIERCELIN** [comment]
Yes 🙂

**Comment by Fabrice-TIERCELIN** [comment]
Hi @IvanSavenko,

Is there a reason there is not:

```xml
    <message>
        <location filename="../cmodlistmodel_moc.cpp" line="170"/>
        <source>Name</source>
        <translation>Nom</translation>
    </message>
    <message>
        <location filename="../cmodlistmodel_moc.cpp" line="173"/>
        <source>Type</source>
        <translation>Type</translation>
    </message>
    <message>
        <location filename="../cmodlistmodel_moc.cpp" line="174"/>
        <source>Version</source>
        <translation>Version</translation>
    </message>
```

**Comment by IvanSavenko** [comment]
@Fabrice-TIERCELIN Sorry, what are you asking? What's wrong with these entries?

**Comment by Fabrice-TIERCELIN** [comment]
So there is no reason :) Never mind, @IvanSavenko

**Pull request merged**
