### PR TITLE
Moved RMG templates from vcmi-extras to vcmi mod

### PR DESCRIPTION
**Pull request by IvanSavenko**
RMG templates are now part of core vcmi mod, allowing usage of RMG without vcmi-extras.

For now templates are part of our 'vcmi' mod directly, without submods. Can be changes/reconsidered for 1.3 if necessary.

- rechecked our templates, fixed some inconsistencies, e.g. missing connections between zones
- disabled 4 too broken H3 templates (json's will stay in repo, but won't be loaded).
- removed xxl templates since they are identical to standard ones. We can simply extend range of original templates and avoid copy-paste.
- disabled some "random templates", e.g. Midnight Mix, Anarchy since they create too many entries in template selection list. We need some sort of "template packs" for them.
- disabled unknown templates (not present in h3, hd mod, hota). We have more than enough templates as it and I don't have reference to compare this template with visual preview
- fixed river/road placement next to map edge, tired looking on it during my tests
- fixed Jebus Cross - now used on L-U & XL-U, as it should be.
- fixed 6lm10a template, now replaces one version of OH3 6lm10 template (since 6lm10a is basically its fixed version)

### CODE REVIEW

**Comment by Nordsoft91** [comment]
Why moving them?
For modders will be easier to download lightweight repo with vcmi-extras. Also, it will be easier to give permissions to more people there...

**Comment by IvanSavenko** [comment]
This was discussed many times on Slack.

We currently require people to install vcmi-extras just to have working RMG. This needs to go.

People want to play game not figure out where to ask for help and how to install required mods

**Comment by Nordsoft91** [comment]
Problem statement is clear (it's quite similar to oh3 data).
But chosen solution is questionable and has disadvantages

**Comment by IvanSavenko** [comment]
Like what? That our 0 modders that have shown interest in working with RMG templates won't be able to submit changes via PR to vcmi-extra?

**Comment by IvanSavenko** [comment]
We talked about this month ago, if not more. No solutions other than moving templates to main repo were proposed

**Comment by IvanSavenko** [comment]
@DjWarmonger should I restore them?

And what about other large templates that are as of right now exclusive to XL+U? Namely:
- Spider
- Nostalgia
- 6ML10 (including 'a')
- Coldshadow's Fantasy (less zones than in other, but still quite a lot)
- Clash of Dragons ("only" 18 zones)

Should I extend them to larger maps? How large? All the way to G+U?

**Comment by IvanSavenko** [comment]
@DjWarmonger Done, all templates set as you've suggested (except for 6LM10 - kept at xl+u due to poor maps)

However "Coldshadow's Fantasy" consistently tends to generate such obstacle-filled zones:
(look at minimap)
зображення

Tested other templates mentioned here at G+U.
Results:
- 6LM10 (non-A) - too small, huge unused areas, reverted to XL+U
- 6LM10A - unused areas at G+U, looks fine at XH+U
- Spider, Marathon, Nostalgia, Clash of Dragons - OK even at G+U
- Coldshadows Fantasy - unused areas as on screenshot, and persist even at less absurd sizes. Issue with template zone? It is always zone with dragon dwellings.

**Review by DjWarmonger — APPROVED** [review]

**Comment by DjWarmonger** [comment]
Yep, these are so-called "junction" zones and they only contain a straight path to the entrance.

**Pull request merged**
