### PR TITLE
Fix tests compiling

### PR DESCRIPTION
**Pull request by Nordsoft91**
To be able to run tests, I removed ERM/scripting tests.

Most of tests failed, but it reflects reality about develop branch at most

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Perhaps we should enable running tests on CI to prevent future regressions?
Assuming that it is possible to run compilation but ignore failing tests in CI.

**Comment by rilian-la-te** [comment]
@Nordsoft91 what is a difference with #1623? 

Is tests running without H3 data?

**Comment by rilian-la-te** [comment]
On #1623 all tests passing.

**Comment by rilian-la-te** [comment]
If your branch is also not working without H3 data, I suggest to merge #1623 without last commit instead, because that branch is more complete.

**Pull request closed without merging**
