### PR TITLE
Initial Czech translation

### PR DESCRIPTION
**Pull request by cewbdex**
Would like to merge this before new release happens. Will see if I manage to find more time to complete this.

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Hi. If you're familiar enough with Git, can you rebase this onto "beta" branch?

"develop" is currently used for 1.4 release, 1.3.2 preparations are in "beta".

Also, please translate & add following section into Mods/vcmi/mod.json, similar to other languages:
```
	"czech" : {
		"name" : "VCMI essential files",
		"description" : "Essential files required for VCMI to run correctly",
		
		"skipValidation" : true,
		"translations" : [
			"config/vcmi/czech.json"
		]
	},
```

**Comment by cewbdex** [comment]
Done, I hope the English files are the same, as I used the `english.json` template from `develop`.

**Comment by IvanSavenko** [comment]
Thanks!

FYI - Github has an option to change target branch without creating new PR - check "Edit" button in top-right corner. Well, I guess too late for that now :)


> Done, I hope the English files are the same, as I used the `english.json` template from `develop`.

They are either same or almost same. Should be OK to use either one.

**Comment by cewbdex** [comment]
Oh, is that a recently added feature? Afaik it was not possible before, thanks for letting me know.

**Pull request closed without merging**
