### PR TITLE
Fixes for crashes caused by town building changes

### PR DESCRIPTION
**Pull request by IvanSavenko**
Fixes two crashes reported on Discord:
- crash on town event that builds large number of buildings
- crash on using town portal to enter town

### CODE REVIEW

**Comment by Povelitelh3** [comment]
The Lone Knight still crashes..

**Comment by IvanSavenko** [comment]
Unable to reproduce for some reason, even after multiple attempts

**Comment by IvanSavenko** [comment]
For now merging, will look into that crash if I manage to reproduce it.

**Comment by Povelitelh3** [comment]
> For now merging, will look into that crash if I manage to reproduce it.

here a crashdump https://drive.google.com/file/d/1VJrKi3Cqu862nfeYTn5Tj0Eu2CWoGzPM/view?usp=drive_link
develop 1.6.0.1e74216040ba4d2a59cfc1772fc9aca3842f0c51 msvs

**Pull request merged**
