### PR TITLE
Fix building in debug mode

### PR DESCRIPTION
**Pull request by IvanSavenko**
- Fixes (yet again) broken compilation in Debug mode
- Attempt to add one more CI run that uses debug mode to prevent these issues in future

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
from the code change it's absolutely unclear how/why it builds in release mode

**Comment by IvanSavenko** [comment]
@kambala-decapitator 
In release mode, preprocessor completely removes assert's, so compiler won't "see" code inside assert and won't issue any errors.

**Comment by rilian-la-te** [comment]
@IvanSavenko @kambala-decapitator maybe better to use clang and ubuntu-latest? Or you used dated dependencies and operating system with purpose?

**Comment by IvanSavenko** [comment]
@rilian-la-te 
Ideally - I'd rather use both oldest and newest version, if only to make sure that vcmi can still be compiled with these versions. However not sure about adding new CI runs due to usage limits - sure, it's free, but we do sometimes end up with queued builds for hours due to multiple active PR's.

clang vs gcc - we need to check both, so don't see any point in switching to one or another.

**Comment by kambala-decapitator** [comment]
> @kambala-decapitator
> In release mode, preprocessor completely removes assert's, so compiler won't "see" code inside assert and won't issue any errors.

thanks. I've overlooked the fact that all code changes are inside asserts :)

**Comment by SoundSSGood** [comment]
@IvanSavenko thanks for fixing it. I forget to remove NDEBUG define from preprocessor options.

**Pull request merged**
