### PR TITLE
Issue/2306

### PR DESCRIPTION
**Pull request by alexvins**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
VCMI crashes with this version, merged with develop.
```
0   libVCAI.dylib                 	0x000000010dde2a63 SectorMap::firstTileToGet(HeroPtr, int3 const&) + 179
1   libVCAI.dylib                 	0x000000010ddeb38a VCAI::isGoodForVisit(CGObjectInstance const*, HeroPtr, SectorMap&) + 106
2   libVCAI.dylib                 	0x000000010ddec2bc VCAI::getPossibleDestinations(HeroPtr) + 268
3   libVCAI.dylib                 	0x000000010ddecd48 VCAI::wander(HeroPtr) + 1832
4   libVCAI.dylib                 	0x000000010dde10de VCAI::performTypicalActions() + 1486
5   libVCAI.dylib                 	0x000000010dddd45c VCAI::makeTurnInternal() + 4444
6   libVCAI.dylib                 	0x000000010ddd3537 VCAI::makeTurn() + 1863
7   libboost_thread-mt.dylib      	0x0000000104ea1715 boost::(anonymous namespace)::thread_proxy(void*) + 53
8   libsystem_pthread.dylib       	0x00007fff931e99b1 _pthread_body + 131
9   libsystem_pthread.dylib       	0x00007fff931e992e _pthread_start + 168
10  libsystem_pthread.dylib       	0x00007fff931e7385 thread_start + 13
```

The following code:

```
int3 ret(-1,-1,-1);
  fprintf(stderr, "%d %d %d %d %d %d\n",
	      h->visitablePos().x, h->visitablePos().y, h->visitablePos().z,
	      dst.x, dst.y, dst.z);
  int sourceSector = retreiveTile(h->visitablePos()), destinationSector = retreiveTile(dst);
  fprintf(stderr, "%p %zu %d %d\n", this, infoOnSectors.size(), sourceSector, destinationSector);
  fprintf(stderr, "src exists %d\n", (int)(infoOnSectors.find(sourceSector) != infoOnSectors.end()));
  fprintf(stderr, "end exists %d\n", (int)(infoOnSectors.find(destinationSector) != infoOnSectors.end()));
  const Sector *src = &infoOnSectors[sourceSector],
		       *dest = &infoOnSectors[destinationSector];
```

Segfaults on find() (!!!), if you remove find() != end() checks, it segfaults on operator[]. Output:

```
...
Hero Октавия moved from 76 71 0 to 74 70 0. Returning 0.
Hero Октавия apparently used all MPs (0 left)
Looking into Галтран, MP=1700
99 70 0 106 60 0
0x7ff23f9d8068 22, 16 16
src exists 1
end exists 1
0x7ff23f9d35a8 0x7ff23f9d35a8
99 70 0 65 64 0
0x7ff23f9d8068 22, 16 4
src exists 1
end exists 1
0x7ff23f9d35a8 0x7ff23f9d2468
added object id=3769; address=140678421529632; name=Лодка
99 70 0 67 41 0
0x7ff23f9d8068 22 163 163
```

**Comment by vmarkovtsev** [comment]
Save: https://mega.nz/#!YN5zWRjS

**Comment by vmarkovtsev** [comment]
Merging with 2a59cb619137cb443adce6aba009ecf37a6a57da (before paths rework) does not segfault. I've created https://github.com/vmarkovtsev/vcmi/tree/stable-develop to finish the damn map :)

**Comment by alexvins** [comment]
So there is regression in recent upstream commits (like Pathfinder rework)?

**Comment by alexvins** [comment]
Also is this https://github.com/vcmi/vcmi/commit/1bcfa986e4243bb4a17b3d6d632e04011fc7cf93 exact version works? (The commit just before it will not work on your side)

**Comment by DjWarmonger** [comment]
I can't tell that at least AI has no visible issues with recent pathfinder.

**Comment by vmarkovtsev** [comment]
@alexvins Yes, it does not work. I tested exactly 1bcfa98

**Comment by IvanSavenko** [comment]
@vmarkovtsev, @alexvins Are there any know issues with this pull? Apart from merge conflicts of course.

And to make it clear - this issue comes from types that have their methods inlined/autogenerated. That is, only net packs? Or there are other types affected by this bug as well? If only NetPacks are affected then I'd rather ensure that their vtable is always in libvcmi instead of relying on strings comparison.

Can you merge this branch with develop? Right now this branch can't be merged due to conflicts. And please revert your barrier fix - I got that bug as well on Linux (so this is not MacOS-only), and it should be fixed now. Same goes to SectorMap crash in AI.

**Comment by ArseniyShestakov** [comment]
Please wait till I merge all my 3 finished branches before fixing this one. Thanks. :-)

**Comment by alexvins** [comment]
>I'd rather ensure that their vtable is always in libvcmi

@IvanSavenko How to do that? DLL_LINKAGE will not work on class declaration with netpacks.

**Comment by IvanSavenko** [comment]
It will work. If implementation of virtual method will be in .cpp that is part of library instead of inlining in header.

**Comment by alexvins** [comment]
I`m talking about applyCl and applyGh. They will not link and it had been confirmed long ago.

**Comment by IvanSavenko** [comment]
You're right. Will see if I find another way to avoid this bug.

**Comment by IvanSavenko** [comment]
Yeah, no way around this as far as I can see. The only possible improvement I found was switching from std::map to std::unordered_map in type_infos.

If there are no issues left and it works for @vmarkovtsev then looks OK for me.

**Comment by vmarkovtsev** [comment]
I will check it today.

**Comment by vmarkovtsev** [comment]
Actually, that mutex/cond is just redundant and was inserted long time ago for some lame reason (threads do not work that way).  That's why we should remove it.

**Comment by vmarkovtsev** [comment]
I can confirm that this kind of works. AI works. Adventure map and battles work. Looks like ok to merge.

I've made https://github.com/vcmi/vcmi/pull/149 to fix the mutex problem I described.

**Pull request merged**
