### PR TITLE
Version bump for Linux

### PR DESCRIPTION
**Pull request by Mixaill**

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
Are you able to test RPM build somewhere? If yes can you please change it to use SDL2?
I'll do same thing for debian build today.

**Comment by Mixaill** [comment]
Now builds fine for Fedora 20 and Fedora 21
http://copr.fedoraproject.org/coprs/mixaill/vcmi/

**Comment by ArseniyShestakov** [comment]
Thanks!

**Comment by ArseniyShestakov** [comment]
I think it's can be merged now.

Though just in case is there any reason you using Release instead of RelWithDebInfo?
Will it have enough debug info in symbols files?

**Comment by Mixaill** [comment]
>Though just in case is there any reason you using Release instead of RelWithDebInfo?
Will it have enough debug info in symbols files?

That's my fail. RelWithDebInfo is definitely better in this situation.

**Comment by ArseniyShestakov** [comment]
I'll fix it, no big deal.

**Pull request merged**
