### PR TITLE
fix boost.locale crash on macOS-arm64

### PR DESCRIPTION
**Pull request by kambala-decapitator**
The fix is taken from https://github.com/SuperTux/supertux/pull/1663

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
just thought that https://github.com/vcmi/vcmi/blob/develop/client/CMT.cpp#L169 might be related

**Comment by ArseniyShestakov** [comment]
Need to test it on Linux just in case, but I guess for 99% of users UTF-8 is default anyway. Though who knows might be there some corner cases that make it not just Windows quirck.

**Comment by kambala-decapitator** [comment]
if you think it's dangerous, the condition can be changed to exclude only ARM Macs

**Comment by ArseniyShestakov** [comment]
Ok, finally tested it properly just in case.
Thanks for contribution!

**Pull request merged**
