### PR TITLE
Fixes for issues discovered in beta

### LINKED ISSUE #1612: Was not able to pass through the open gate during siege.
**Describe the bug**
Was not able to pass through the open gate during siege. Troglodytes got morale on the first turn and moved through the gate, it opened and they stopped on it. Killed them by a stack of centaurs while they were standing on the opened gate. Afterwards I was attacked by a stack of griffins, they also landed on the gate. Killed them with counterattack. Animation left the gate opened but I was not able to pass through it.

**Expected behavior**
When a stack is killed on an opened gate it has to stay opened till the end of the siege

**Actual behavior**
Was not able to pass through the opened gate. Had to spend a few more turns until I killed enemies.

**Did it work earlier?**
Worked fine at least in 1.0

**Version**
 - latest develop, platform windows, msvc
 
[Saves.zip](https://github.com/vcmi/vcmi/files/10831320/Saves.zip)

### PR DESCRIPTION
**Pull request by IvanSavenko**
- Fixes #1612 
- Fixes hang on battle startup with "no intro sound" mod in use
- Fixed potential crash on nullptr dereference in ambient sounds
- Fixed corrupted black colors in battle on some creatures from mods (reported on forum)
- Fixes cutoff position of shooters, should now match H3
- Added Chinese in-game texts
- Added check for "keepDisabled" property in mods for client
- Use fast SDL blit for redrawing windows backgrounds
- Fix corrupted redraw on buying artifact at artifact merchant
- Kills in damage estimation tooltip will be limited to stack size

### CODE REVIEW

**Comment by rilian-la-te** [comment]
Is this fixes will be integrated to develop soon?

**Comment by dydzio0614** [comment]
they should be if you need some changes from them

**Comment by IvanSavenko** [comment]
Will probably merge open PR's and then merge beta->develop

**Comment by rilian-la-te** [comment]
I need to change same functions, because now I trying to make crystal dragons correctly passing moat)

**Pull request merged**
