### PR TITLE
Rename default map template to random map template

### PR DESCRIPTION
**Pull request by DjWarmonger**
This is quite a bugger

How it should be:
image

Translations:

- [x] Chinese
- [x] German
- [x] English
- [ ] French
- [ ] Hungarian
- [x] Polish
- [x] Russian
- [ ] Spanish
- [x] Ukrainian

### CODE REVIEW

**Comment by DjWarmonger** [comment]
@Laserlicht @tytannial @IvanSavenko Please check if current translation is suitable.

**Comment by IvanSavenko** [comment]
Ukrainian: should be "(Випадковий)"

**Comment by Laserlicht** [comment]
German should be "(Zufällig)".

**Comment by tytannial** [comment]
Simplify Chinese should be "(随机)".

**Comment by kambala-decapitator** [comment]
Russian: (Случайный)

**Comment by DjWarmonger** [comment]
Okay. Removed old text id, added new one. Outdated translations will warn about missing string.

**Pull request merged**
