### PR TITLE
disintegrate bonus

### PR DESCRIPTION
**Pull request by Laserlicht**
...after death no corpse remains...

### CODE REVIEW

**Comment by dydzio0614** [comment]
does it correctly count these creatures to battle casualties after battle?

**Comment by Laserlicht** [comment]
> does it correctly count these creatures to battle casualties after battle?

Yes. Tested this one. Other things to test?

**Comment by IvanSavenko** [comment]
Necromancy perhaps? Can't think of any other cases.

**Comment by by003** [comment]
Disintegrate bonus might be mainly used in Ring of Oblivion.
Actually it blocks any 
resurrection in battle, which cannot be resurrected and raised after battle by necromancy.

**Comment by Laserlicht** [comment]
Yes this PR based on  @by003 ideas for bonuses as it was easy to integrate.

**Comment by Alucard648** [comment]
Will it be possible to add this attribute to creature and spell ability? Like H4 didintegration spell.

**Comment by by003** [comment]
Send my suggestions for subtype here:
disintegrateAbsolute: used for Ring of Oblivion, it will block any resurrection ability and cannot be drained blood. Then, it blocks necromancy after battle.
disintegrateNormal: used for automaton in detonation ability, it can be resurrected unless be eliminated.

If disintegrate spell needs to be implemented, a new bonus 'DISINTEGRATE_ATTACK' is needed.It can only affect the part which is eliminated by the ability owner. Like a spell or a creature.If all eliminated quantities are caused by ability owner, no body remains.

**Comment by by003** [comment]
Disintegrate bonus icon is finished.
image

Anyone can add it into vcmi extra.

**Pull request merged**
