### PR TITLE
Added LotR alternatives for vcmiarmy and vcmiexp

### PR DESCRIPTION
**Pull request by krs0**

### CODE REVIEW

**Comment by rilian-la-te** [comment]
@krs0 why not the classics?

**Comment by krs0** [comment]
? what classics?

**Comment by dydzio0614** [comment]
IMO LotR cheat places should not be there in the first place and existing are not removed for compatibility

**Comment by rilian-la-te** [comment]
@dydzio0614 why not? LoTR cheats is good and originates from WoG. Classics for @krs0: vcmigandalfwhite for exp and there is no classic for army.

**Comment by krs0** [comment]
@rilian-la-te did not new those are from WoG.
I just invented vcmimithrandir :)
will change to that one.
@dydzio0614 I just made a quick change following what was existing so that it gets into 1.2

**Comment by dydzio0614** [comment]
not against this change, but in general cheats should be intuitive easy to memorize to be useful, easter egg names are not very practical
too many aliases also may make a mess for players in a wiki

**Comment by IvanSavenko** [comment]
Well... Strictly speaking, VCMI cheats are not from LotR but from Silmarillion. So neither Mithrandir nor Gandalf fit

**Comment by krs0** [comment]
Ok, this was intended as a quick fun fix... maybe not my thing :)

All names seem to be invented for VCMI and no connection to other H3 versions. And like Ivan mentioned seem to be using Silmarillion.

In the Silmarillion, Gandalf is referred to as "Olórin"

You can discard the PR completely if not ok. No biggie.

**Pull request merged**
