### PR TITLE
Fixes for regressions related to adventure map

### LINKED ISSUE #1654: Map renderer issues
**Describe the bug**
Some list of map renderer issues
1. Chat is not causing redraw of the console correctly, leading to weird behaviour (see screenshots)
2. Sometimes cursor does not changes from arrow to horse

**To Reproduce**
1.
Run vcmiclient
Enter around 5 lines of chat (or 3-4 cheats)
2. Happens randomly

**Expected behavior**
Chat should not be weird, cursor should always be correct

**Actual behavior**
A clear description what is currently happening 

**Did it work earlier?**
before rewrite I did not saw 1 at least

**Screenshots**
1. 
image

For 2 - it is difficult to do screenshot.

**Version**
 - OS: Linux
 - Version: #1645

### LINKED ISSUE #1674: Crash on killing hero on boat
**Describe the bug**
Crash on killing hero on boat.

**To Reproduce**
1. Load attached save
2. Attack blue enemy boat
3. Kill enemy with a spell
4. After accepting battle result a crash happens

**Expected behavior**
No crash.

**Actual behavior**
A crash happens

> `uint8_t MapRendererObjects::checksum(IMapRendererContext & context, const int3 & coordinates)`
> `{`
> `	for(const auto & objectID : context.getObjects(coordinates))`
> `	{`
>` 		const auto * objectInstance = context.getObject(objectID);`
>` 		size_t groupIndex = context.objectGroupIndex(objectInstance->id);`
>` 		Point offsetPixels = context.objectImageOffset(objectInstance->id, coordinates);`

objectInstance is nullptr

**Did it work earlier?**
Yes

**Version**
 - Windows, MSVC
 - Version: latest develop (e.g. 1.2)

**Additional context**
[Saves.zip](https://github.com/vcmi/vcmi/files/10950259/Saves.zip)

### LINKED ISSUE #1681: New renderer: battle opened when hero is not a city
**Describe the bug**
Self-explanatory

**Game logs**
Not applicable

**To Reproduce**
[Autosave_1.v.zip](https://github.com/vcmi/vcmi/files/10972796/Autosave_1.v.zip)
Attack town with Uland

**Expected behavior**
Hero should finish movement in a tile before

**Actual behavior**
He does not finished movement before battle starts, but finished it in background when battle takes place.

**Did it work earlier?**
before new renderer

**Version**
 - OS: Linux
 - Version: #1680 

**Additional context**

### LINKED ISSUE #1686: After defeating a monster that guards some resources, cursor updates to horse only after moved from resource.
After you defeat a monster if you keep your mouse on a resource the cursor will never update to prancing horse.

image

**Version**
 - OS: Windows
 - Version: develop

### LINKED ISSUE #1710: When I hit end turn all Adventuremap animations are really fast
When I hit end turn all Adventuremap animations are really fast

**Version**
 - OS: Windows
 - Version: develop

### PR DESCRIPTION
**Pull request by IvanSavenko**
Fixes so far:
- Fix crash on winning scenario
- Fix crash on switching players in hotseat
- Fix corrupted town visual on building fort
- Fix corrupted text in game console
- Fixes #1710 
- Fixes #1674 
- Fixes #1681 
- Fixes #1686 
- Fixes #1654

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Most of known regressions fixed, will merge this tomorrow

**Comment by rilian-la-te** [comment]
@IvanSavenko what about console regression?

**Comment by IvanSavenko** [comment]
> @IvanSavenko what about console regression?

You're referring to green console text that appears on top of adventure map? Yes, fixed:
- Fix corrupted text in game console

**Comment by rilian-la-te** [comment]
@IvanSavenko thanks. Moats also most likely to be finished this week. I do not know what is next - maybe another spell mechanics bug, and maybe fixing tests to work without H3 data.

**Pull request merged**
