### PR TITLE
Update version on each compiling

### PR DESCRIPTION
**Pull request by drizt**

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
Is the old version of code didn't worked for you?
I was pretty sure it's updated with every little commit just fine regardless of any other changes.

**Comment by drizt** [comment]
It works for me. And yes current way is pretty good. But in TODO _So for now commit hash only updated when CMake reconfigured._ This patch allows to avoid extra CMake reconfiguration.

**Comment by ArseniyShestakov** [comment]
In case this code should actually work for all generators you should remove that TODO item from main CMakeLists.txt.
Now I can recall it's was problem with Visual Studio where it's only re-generated Version.cpp on reconfiguration.

**Comment by drizt** [comment]
@dydzio0614, can you test this with Visual Studio?

**Comment by drizt** [comment]
@ArseniyShestakov, should I move **Version.cmake** to **cmake_modules** folder?

**Comment by ArseniyShestakov** [comment]
Yeah it's good idea to place it into ```cmake_modules```.
I'll check it with MSVS.

**Comment by drizt** [comment]
Also with this patch it is possible to add extra data to Version.cpp. Compilation date and time for example.

**Comment by ArseniyShestakov** [comment]
This code doesn't seems to work when you building outside of source directory.

**Comment by drizt** [comment]
Change `CMAKE_CURRENT_SOURCE_DIR` to `CMAKE_CURRENT_LIST_DIR` in **GetGitRevisionDescription.cmake**.

**Comment by ArseniyShestakov** [comment]
Thanks for contribution! Tested with MSVS2015/2017 and Xcode 8.3 and everything seems to work well.

I cherry picked and edited it a bit here:
https://github.com/vcmi/vcmi/commit/3c1c72319b53b6d7c531a33dc5f5e500a9572e3d
Closing.

**Pull request closed without merging**
