### PR TITLE
Travis: add Windows build via MXE

### PR DESCRIPTION
**Pull request by ArseniyShestakov**
Still have to find out why return code is wrong, but I think it's works fine.

In future I want to to publish artifacts from Travis too so daily builds not depend on my own PC.

### CODE REVIEW

**Comment by viciious** [comment]
It'd be nice to have Appveyod MSVC builds too

**Comment by ArseniyShestakov** [comment]
@viciious yeah I would absolutely love to have CI for MSVC so we don't break compatibility, but sadly we have no one using VS together with CMake as generator and I don't really want to host project files in repository. Also I have no idea where to look for prebuilt libraries for Windows and not really want to trying to make it work myself.

**Comment by ArseniyShestakov** [comment]
Yeah for some reason vcmitest fail to build with MXE and I not sure if I should disable it for that build or no.

**Comment by viciious** [comment]
@ArseniyShestakov yeah, pre-built libraries for msvc is definitely something worth having as a downloadable bundle. Pulling it all together is an exercise in patience you don't want to repeat too often. Maybe I can do it some time later.

**Comment by ArseniyShestakov** [comment]
@viciious just in case if you ever decide to participate I dropped you invite to our slack.

I suppose dydzio might have all libraries we need, but his VS setup is kind a tricky.

**Pull request merged**
