### PR TITLE
Add welcome/setup page to Laucher

### PR DESCRIPTION
**Pull request by IvanSavenko**
As discussed before, mock-up of initial setup/welcome page for Launcher. 
Currently this is just UI mock-up, with 0 implemented functionality, mostly to gather feedback. Will probably wait for a week or so 

### Overall Design
- This tab will open automatically on first install or if H3 data is missing (e.g. deleted by user since last start)
- While in this tab, buttons from left panel will be most likely disabled until user finishes setup. We can't really play game if there is no H3 data.
- "Setup" button from left side will be likely removed, potentially - moved to settings.
- Top panel on mock-up has both progress bar and buttons to show progress. Currently planning to remove progress bar and only keep buttons. Another option is to keep only progress bar, but buttons are probably better option.

### Language Selector
- Left side will have language names using same format as language selector, e.g "Українська (Ukrainian)", shamelessly taken from Steam webpage design.
- For right side I'm planning to have some sort of introduction text, but not yet sure what to write there. Suggestions welcomed.

### Heroes III Data Selector
Should be mostly self-describing.
- text inputs near "Heroes II data files" should show one of data_dir paths (e.g. `.` on Windows or `/usr/share/vcmi` on Linux) and user data directory (e.g. `Documents/My Games/vcmi` for Windows, `~/.local/share/vcmi/` on Linux)
- some elements are conditional and won't always show up:
- - vcmibuilder tool only exists on Linux (and I think MacOS?), so no reason to show it on Windows/mobile platforms
- - "data successfully found" will only show up if H3 data detected (and disable/hide other texts)
- - for language, only one label will be shown, depending on language detection result.

### Mods Preset Selector
- Should probably add separate label with explanation about "optionally installable mods", to explain what's this about
- "Install localization" should be only visible if selected language differs from H3 language AND we have mod with localization to selected language.
- "HD support" means installation of vcmi-extras mod
- user can either skip this step completely and play vanilla game, or install more than one "preset"

### Finish tab
No screenshot because nothing to show. Currently considering dropping links to community (probably Discord & vcmi.eu forum) as well as link to Github for bug reports.

Probably some basic description of what can vcmi do would be good addition, but not sure what to add there. Suggestions?

Another option is to axe this tab and show community links someplace else, e.g. add "About" button or "Help" button somewhere with these links. Should be someplace easily accessible, e.g. on left panel, and not buried deep into settings.

### Screenshots
launcher-welcome-language
launcher-welcome-h3data
launcher-welcome-modspreset

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
looks good I think.

maybe rename "HD support" to "high resolutions" that people don't think that it means "HD mod".

**Comment by IvanSavenko** [comment]
> Looks like a setup wizard. 

Pretty much, yeah. Except this part is performed in Launcher and on any OS (and not Windows-only)

> And why is the button size so small? Suggestion: place a button first in the list and always start the launcher with the screen of the wizard.

You mean "setup" button? Temporary code for mock-up to give me a way to access this window.

Yes, in final version I'm planning to remove that button and instead open setup screen automatically if:
a) Player has not completed this setup before
b) Heroes III data was not found, e.g. remove since last launch.

**Comment by krs0** [comment]
Complete names with Icon would be more suggestive for selecting the 2 big mods. Heroes III + does not bring anything extra and could be dropped. 

 **Horn of the Abys** 
 **Horn of the Abys (HotA)**

 **In the Wake of Gods (WoG)**

**Comment by krs0** [comment]
_VCMI provides its own version of HotA_ sounds like you appropriate something.
Install VCMI port of Horn of the Abyss fan-made Heroes III mod. (Perhaps with a work in progress disclaimer?)

**Comment by krs0** [comment]
@IvanSavenko 
3) Horn of the Abyss fan-made Heroes III mod, ported by VCMI team? 
Emphasizes the HotA mod itself, as the most important element and the word "ported" that comes after mod name makes it clear that the mod already exists and that the team is simply responsible for the porting process.

**Comment by IvanSavenko** [comment]
Assuming PR to be ready for review & merge.
Will merge in a few days if there are no comments/objections.

Functionality is done, but might still need one more UX/usability pass.
Will probably merge as it, collect opinions/bug reports from rest of the team / players and then do another pass before 1.2

Changes compared to initial design:
- Removed "Finish" tab, since that tab remained empty with no content.
- Mod preset now uses checkboxes instead of buttons & actual install of mods happens after setup is complete - mostly to avoid reimplementing mod install progress UI in here.

**Comment by rilian-la-te** [comment]
@IvanSavenko is it supports vcmibuilder?

**Comment by IvanSavenko** [comment]
@rilian-la-te Not really. Just link to the wiki at the moment. It is possible to copy already installed data, but no way to extract it from gog.exe

If somebody else can integrate vcmibuilder into this install window - go ahead, but I am not really familiar with Qt so process takes too long - I would rather focus on game proper.

**Comment by rilian-la-te** [comment]
I see hasVCMIBuilderScript variable in your PR. What it should do?

**Comment by IvanSavenko** [comment]
@rilian-la-te 
As I said - Just link to the wiki at the moment. 
Not much point behind showing that link on Android/Windows

**Comment by rilian-la-te** [comment]
So, we need to translate vcmibuilder into C++ and use it in page 2 in next PR. Understood.

**Comment by IvanSavenko** [comment]
@rilian-la-te 
If you or somebody else is interested in this - sure, go ahead.

Don't think that we need to convert entire vcmibuilder script - converting innoextract part should fine. I doubt that we still have people with H3 disks.

**Comment by rilian-la-te** [comment]
@IvanSavenko I mostly care about innoextract part, but CD rip part can be converted too. 

I am interested, because I do not think than Linux should be second-class citizen. I think Linux should be a priority, because there is no native H3 on Linux except VCMI.

**Comment by IvanSavenko** [comment]
@rilian-la-te 
Go ahead then. 
I just don't feel comfortable enough working with Qt and feel that I am spending too much time on it for too little progress.
Integration of shell script and filesystem operations would take even more time for me.

As for script:
- Innoextract is definitely important
- mp3->ogg conversion may be dropped, not sure what's current status of mp3 support in sdl in distros like Fedora
- CD extraction can be dropped. A lot of PC's don't even have CD drive nowadays. And that's assuming that 20-year old install CD still works.
- Copying of existing install is already in Launcher

**Pull request merged**
