### PR TITLE
Ban objects on maps without water

### PR DESCRIPTION
**Pull request by DjWarmonger**

### CODE REVIEW

**Comment by DjWarmonger** [comment]
I actually wonder how to handle this in custom scenarios. Mapmakers may want to allow some heroes deliberately, so we can't force ban them on map load.

**Comment by IvanSavenko** [comment]
Well, if we want "hota style" approach then it looks to be only used on RMG maps based on "water content" option.
If we want to extend this to single scenarios then we can have this autodetection in H3M maps, and explicit flag in VCMI maps (editable by map maker). Or only use flag on VCMI maps and remove autodetection completely.

**Review by IvanSavenko — COMMENTED** [review]
- Please update json validation schemas
- I don't see handling of Navigation skill ban. Intended?

**Comment by rilian-la-te** [comment]
It should be optional feature, I think. In OH3 there is no ban for Navigation and related heroes. I think HoTA is evil, but I understand than some players want HoTA features. So, I think this should be optional non-default feature, when HoTA mod is disabled.

**Comment by IvanSavenko** [comment]
Merge?

**Pull request merged**
