### PR TITLE
Refactoring/serialization

### PR DESCRIPTION
**Pull request by DjWarmonger**
Testing.

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
New serializer also decrease compilation time for me from 1m24s to 1m17s.

**Comment by alexvins** [comment]
Something wrong with merge, at least Connection.[h|.cpp] was moved to another directory and restored by merge

**Comment by alexvins** [comment]
Suggest to put this on hold for now, at least until crash with SXX`s test map will be fixed. Also  953c77b screwed up completely, impossible to track changes.

**Comment by ArseniyShestakov** [comment]
Rebased version in PR #212.

**Pull request closed without merging**
