### PR TITLE
Replace deprecated FFmpeg API for compatibility with ffmpeg 2.9

### PR DESCRIPTION
**Pull request by josch**
these changes make vcmi compatible with ffmpeg 2.9 (while at the same time compiling with ffmpeg 2.8)

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
This one break build on Ubuntu 14.04 for me.
av_alloc_frame / av_frame_free are undeclared.

**Comment by alexvins** [comment]
We should support version 2.7

**Comment by josch** [comment]
right, it seems I need to wrap this in a preprocessor directive - stay tuned...

**Comment by alexvins** [comment]
Also, we have backward compatibility code for even smth around 2.2.x We should clean-up if we are raising minimum version

**Comment by ArseniyShestakov** [comment]
Ok this way it's compile and works fine. :-)

**Comment by IvanSavenko** [comment]
Everything looks OK, should this be merged?

@josch do you wish to take a look on video player and remove all ancient versions checks?

Anything older than 2.6 can go - I don't see any Linux distro with 2.5 or earlier so we can remove support for it before video player code turns into #ifdef maze yet again.

**Comment by josch** [comment]
Hi Ivan, no sorry I will not have time for this in the near future.

**Comment by IvanSavenko** [comment]
Then merging as it is.

**Comment by alexvins** [comment]
@IvanSavenko ifdef maze cleared in #140 - need testing

**Pull request merged**
