### PR TITLE
Fix Market of Time missing Template

### PR DESCRIPTION
**Pull request by krs0**
Tested and works. (visit but nothing happens). Visitable and blocking seem to work ok. But I am no modder so please doublecheck.

### CODE REVIEW

**Comment by nullkiller** [comment]
When I recently fixed market of time it worked. It should fetch template from HOMM3 data?

**Comment by nullkiller** [comment]
Or maybe it depends on data itself and some homm3 data does not have market of time at all?

**Comment by IvanSavenko** [comment]
@nullkiller 
Market of Time has no templates in H3 - this is unused object after all.
And objects without templates generate warning during mod validation.

And map with pre-placed Market of Time does not requires template - H3M has templates embedded into map format.

**Review by IvanSavenko — APPROVED** [review]
Looks OK.

Does not fixes original root cause of this change - crash on visiting unknown object, but if goal is to fix warning then probably OK.

**Comment by krs0** [comment]
Yes goal is to fix warning and to shkw no surprise behaviour on visit.

IE should behave like intended on map except nothing happens on visit

**Pull request merged**
