### PR TITLE
BattleAI: fix moving to unreachable in case of back-to-back 2-hex

### PR DESCRIPTION
**Pull request by nullkiller**
Fix bug when 2-hex AI can not move towards enemy backward

### CODE REVIEW

**Comment by dydzio0614** [comment]
maybe this can target beta?

**Comment by IvanSavenko** [comment]
> maybe this can target beta?

Or I can cherry-pick it to beta

**Comment by smanolloff** [comment]
nice! The `ERROR Stack failed movement!` and friends have been plaguing my logs for months now whenever BattleAI is involved o.O I never managed to identify the exact circumstances, hope your PR fixes it 🍻

**Comment by nullkiller** [comment]
Not sure, I think it is something else.

**Pull request merged**
