### PR TITLE
show resurrect message in the battle log

### LINKED ISSUE #957: amount of resurrected creatures isn't written to battle log
tested with Archangels

oh3 message:
Screenshot 2023-01-22 at 16 12 32

### PR DESCRIPTION
**Pull request by kambala-decapitator**
fixes #957

test map: [resurrect.h3m.zip](https://github.com/vcmi/vcmi/files/10475071/resurrect.h3m.zip) Hero has Archangels and Resurrect spell.

Screenshot 2023-01-22 at 20 34 29
Screenshot 2023-01-22 at 20 39 06

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
@IvanSavenko could you review as it touches battle logic?

**Review by IvanSavenko — COMMENTED** [review]
Not exactly familiar with spell system, but at least Damage effect and Timed handle log differently. They call method `server->describeChanges()` to check whether log entries have to be generated and if it returns false - skip logging.

Also, it is a bit weird to have spell-related information "leak" into UnitState. Perhaps keep changes contained in Heal effect & compute heal amount/resurrected amount locally, by comparing old health value with new one?

**Comment by nullkiller** [comment]
> Not exactly familiar with spell system, but at least Damage effect and Timed handle log differently. They call method `server->describeChanges()` to check whether log entries have to be generated and if it returns false - skip logging.
> 
> Also, it is a bit weird to have spell-related information "leak" into UnitState. Perhaps keep changes contained in Heal effect & compute heal amount/resurrected amount locally, by comparing old health value with new one?

I agree. Makes sense. Or return some data structure from Heal method describing healing result. { ResurectedCreaturesCount, HealthPointsRestored } and format it before adding to battle log.

**Comment by kambala-decapitator** [comment]
thanks! adjusted.

**Review by IvanSavenko — APPROVED** [review]

**Pull request merged**
