### PR TITLE
Launcher improvements for 1.2

### LINKED ISSUE #1526: [Launcher] Sort mods by type - language independent
**Describe the bug**
Only a small thing: Better sorting of the mods.

**To Reproduce**
Change language (e.g. german)

**Expected behavior**
Mods of the same category should be sorted together, independent from language.
Use for sorting the english language.

**Actual behavior**
grafik

**Did it work earlier?**
Localization is a new feature

### PR DESCRIPTION
**Pull request by IvanSavenko**
- [x] Fix weird error message on finishing setup with disabled mod repository startup update
- [x] Fix crash on starting launcher without Heroes III data files present
- [x] Added proper error messages for selection of directory without Heroes III data
- [x] Added detection of unsupported versions of Heroes III for data copying (e.g. HD Edition)
- [x] Mod info now shows list of languages supported by mod
- [x] Mod info now shows references to other mods (e.g. dependencies/conflicts) with human-readable names of mods instead of mod ID's
- [x] Added fixed list of mod types, fixes #1526 
- [x] Slightly better layout for mod preset installation tab
- [x] improve starting setup tab - add welcome message & community links.
- [x] look into #1556
- [x] regenerate Qt translations
- [x] update mod.json schema - mod type no longer needs to be translated
- [x] update mod.json schema - mod type should now be enum

Removed from todo:
- investigate common error report where mod fails to update (incorrect selection of repository to update from?) -> move to separate issue
- add icons for hota and wog for mod preset tab? -> rejected/postponed

### CODE REVIEW

**Comment by misiokles** [comment]
add icons for hota and wog for mod preset tab?
I think not - players would think that those mods have special treatments and vcmi devs should keep them in constant development.

**Comment by IvanSavenko** [comment]
> I think not - players would think that those mods have special treatments and vcmi devs should keep them in constant development.

Hmmm... I get what you're saying, however players already give special treatment to these two mods (outside of vcmi), due to their popularity.

Will probably keep them without icons though - not sure whether it will fit in design-wise anyway.

**Comment by rilian-la-te** [comment]
@dydzio0614 we need only hardcoded hota features, not all hota features. Like moving 1 hex backwards)

**Comment by psyhlo** [comment]
> add icons for hota and wog for mod preset tab? I think not - players would think that those mods have special treatments and vcmi devs should keep them in constant development.
may be you could make feature, if mod creators wants to put logo/icon in fixed dimensions?

**Comment by IvanSavenko** [comment]
> ivan will probably hate me for that idea but in past I had idea to implement module.hota same as there is module for commanders and create alternative versions of mechanics to cover 100% of hota features based on bool check if its on or off

Like what? What mechanics does hota have that require such "module"? Vast majority of hota changes are changes in some numbers here and there or new content. What we need to do is provide a way to change them via mod.
For new content we already provide most of what hota needs.
For changes in numbers we can use game settings aka former defaultMods.
And some quality-of-life changes can be added to base vcmi, like that "1 hex backward" move.

**Comment by IvanSavenko** [comment]
> > add icons for hota and wog for mod preset tab? I think not - players would think that those mods have special treatments and vcmi devs should keep them in constant development.
> 
> may be you could make feature, if mod creators wants to put logo/icon in fixed dimensions?

Icons in questions are about setup/welcome screen, which is not part of mod view that we have in 1.1

As for icons in mod list - this is more of design issue. We don't really have place for them at the moment in our UI. So maybe later. Quite low-priority compared to other stuff we have.

**Comment by dydzio0614** [comment]
> Like what? What mechanics does hota have that require such "module"? Vast majority of hota changes are changes in some numbers here and there or new content. What we need to do is provide a way to change them via mod. For new content we already provide most of what hota needs. For changes in numbers we can use game settings aka former defaultMods. And some quality-of-life changes can be added to base vcmi, like that "1 hex backward" move.

example mechanics: different siege tower damage calculation, spells reroll in guild, changes that could not be covered via bonus system for example some secondary skills stuff

**Comment by rilian-la-te** [comment]
@dydzio0614 what secondary skill stuff cannot be handled by new 1.2 bonuses? Tower damage calculation - modder just add some attack and defence to siege towers and it will work. 

Hota grail can be covered by bonus system, and hota cannon - why not?

**Comment by IvanSavenko** [comment]
- different siege tower damage calculation - just different numbers, can be represented as bonus / parameters of arrow tower "creature"
- spells reroll in guild - questionable feature, better to postpone for scripting IMO. Or spell reroll "module" if somebody really wants this ahem, "feature"
- secondary skills stuff - just different numbers, plus one new skill that I believe already supported in mod
- hota grail - need bonus with such functionality
- hota cannon - already implemented/mostly implemented as custom war machine

**Comment by rilian-la-te** [comment]
For Hota grail we should define something like this:

```js
"bonuses": [
    "type": "NO_TERRAIN_PENALTY",
    "propagator": ALL_CREATURES,
    "limiters" : [{
          "type" : "CREATURE_FACTION_LIMITER",
          "parameters" : ["hota:cove"]
     }]
]
```
I do not know why this is hardcoded in VCMI?

**Comment by dydzio0614** [comment]
regarding secondary skills - i talk about past thoughts, not about release 1.1 or 1.2 available features (though i doubt new secondary skill that drops enemy hero magic power is fully supported, including showing reduced amount in braces in hero info window)
tower damage calculation cannot be remade the exactly same way via mods - "Their innate 10 attack points now added together with the defending hero Attack skill and increase damage properly, while still ignoring the target's defense parameter. archery now increase the Arrow tower damage as well. The armorer, air shield and petrification bug has been fixed, so these modificators now properly decrease the Arrow tower damage."

but i do not see reason to talk about past stuff i had in mind 1 year ago

**Comment by rilian-la-te** [comment]
@dydzio0614 we does not increase air shield damage already afaik. Regarding archery, attack and defence - I think bumping attack for Arrow Tower unit will handle it automatically (increasing by archery). Increasing by hero attack - I do not know if it is implemented. 

Yes, Hota map format needs to be done.

**Comment by IvanSavenko** [comment]
And because of such "past thoughts" we now have hardcoded stuff like hota Grail...
(@dydzio0614, yes, I know that you're not the one who made that)

I do agree that hota & hd mod features need more attention, if only due to their popularity. 
Once 1.2 stuff is done with, I have plans to talk about plans 😛. Specifically - look for a better way to organize current state of affairs & get nice list of what's left to be done. @krs0 issues are a good start, but probably too big to be usable for development. Perhaps try using Github Projects for hota/hd mod?

**Comment by rilian-la-te** [comment]
@IvanSavenko when @misiokles will fix hota grail in json, I think there is time to remove such hardcoded thing.

**Pull request merged**
