### PR TITLE
Select random object template instead of first

### PR DESCRIPTION
**Pull request by Nordsoft91**
Idk if there is any issue to be linked

### CODE REVIEW

**Comment by krs0** [comment]
https://github.com/vcmi/vcmi/issues/2531

**Comment by krs0** [comment]
Tried it and something is not quite right.
I have WoG installed and only green chests on rmg. The core red ones are gone
I think same is with prison

**Comment by krs0** [comment]
Hmmm another more critical bug! If I overrided a template, the overrriden template can still appear on map?
Can reproduce with this mod that overrides Ancient Lamp from HotA:
https://github.com/krs0/H3Evo/tree/main/Mods/Artifacts

below the 2 lamps appear. 1 new lamp from mod. 2 old lamp from HotA
image

**Comment by Nordsoft91** [comment]
> Tried it and something is not quite right. I have WoG installed and only green chests on rmg. The core red ones are gone I think same is with prison

Same behavior on develop. It's mod problem, not PR

**Comment by Nordsoft91** [comment]
@krs0 in the mod you shared, template is allowed for sand. What do I miss?

'''

"templates" :
				{
					"advCursedLamp" :
					{
						"animation" : "hota/ancientLamp/avtglam",
						"visitableFrom" : [ "+++", "+++", "+++" ],
						"mask" : ["VAV"],
						"allowedTerrains" : [ "lava", "sand" ] //hota jebus cross conditions
					}
				}
'''

**Comment by krs0** [comment]
In that mod yes, and in next mod (mirage lamp) it is overwritten and restricted to lava only! like pasted above.
So I think both templates are considered.

**Comment by krs0** [comment]
> PR

But my understanding of this PR is that all templates are now taken into consideration right?
So I would expect red chests to appear as well.

**Comment by Nordsoft91** [comment]
@krs0, yes, good catch. There is special logic for treasures' template. Will see if I can do that.
But actually, for me it's hard to debug with WoG since it widely broken (see logs - so many warnings, becoming an assertion in debug mode)

**Comment by krs0** [comment]
@Nordsoft91 wog is in bitesized pieces right now. use only `Map Decorations` submod and delete from .json everything but 		`"config/mapDecorations/vanillaInteractive/treasureChest.json",`

https://github.com/vcmi-mods/wake-of-gods/pull/23

**Comment by Nordsoft91** [comment]
@krs0 , should work now, hopefully nothing gets broken

**Comment by krs0** [comment]
All the ugly chests are there ;). campfires are there.
Will test more.

**Comment by krs0** [comment]
In map editor `miniftws `still does not appear
image

**Comment by Nordsoft91** [comment]
Is it some mod?

**Comment by krs0** [comment]
Oh sorry! Did not realize it was so cryptic.
Its minihillfort from _HotA Wastelands_ terrain.

Usually ending _ws_ for a def means wasteland.

**Comment by Nordsoft91** [comment]
@krs0 `"hota.mapObjects:miniHillFort" : {` -> `"hota.mapobjects:miniHillFort" : {`

**Comment by krs0** [comment]
Nooooo. Lowercase strikes again :(

Thanks for the catch, I've spent some time trying to figure this one out.

**Comment by krs0** [comment]
> @krs0 `"hota.mapObjects:miniHillFort" : {` -> `"hota.mapobjects:miniHillFort" : {`

@misiokles I know you were wondering too :)

**Pull request merged**
