### PR TITLE
Fixing regressions

### PR DESCRIPTION
**Pull request by SoundSSGood**
Some fixes for issues found in https://github.com/vcmi/vcmi/pull/2055, https://github.com/vcmi/vcmi/pull/2164

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
any chance to write proper commit message(s) telling what they actually do? This PR is completely unclear regarding what it solves.

**Comment by SoundSSGood** [comment]
The first regression
Place artifact as on picture. Then move one to the backpack, and equip the one in the backpack. Next, pick up the artifact in the backpack.
er00er01er02

The second. Place any artifact into backpack. Place into backpack the second art Angelic alliance. Next, disassemble the Angelic alliance and scroll backpack right by 1. Assemble Angelic alliance. As a result, the backpack will remain scrolled to the right by 1.
er10er11er12

**Comment by IvanSavenko** [comment]
By that way, not sure if this is related to your recent changes or an old issue, but on current develop if starting bonus is set to artifact AND appropriate slot of our starting hero is NOT empty then this will lead to an assertion failure. 

Release build seems to be working fine - new artifact gets sent to the backpack

Test map with hero that has no empty slots for starting artifact:
[SiegeTests.zip](https://github.com/vcmi/vcmi/files/11678832/SiegeTests.zip)

**Comment by SoundSSGood** [comment]
> Test map with hero that has no empty slots for starting artifact:

thanks, will take a look

**Comment by IvanSavenko** [comment]
Very similar/same issue - visit Warrior's Tomb with no free equipment slots
(same test map, a bunch of tombs to the left from staring town)

**Comment by SoundSSGood** [comment]
@IvanSavenko Fixed in this PR.

**Comment by Nordsoft91** [comment]
@SoundSSGood, does it fix https://bugs.vcmi.eu/view.php?id=3253 ?

**Comment by SoundSSGood** [comment]
> @SoundSSGood, does it fix https://bugs.vcmi.eu/view.php?id=3253 ?

does not fix

**Pull request merged**
