### PR TITLE
issue/1372

### PR DESCRIPTION
**Pull request by alexvins**
Second attempt to fix http://bugs.vcmi.eu/view.php?id=1372
(#124 has serious regressions, merge has been reverted.)

### CODE REVIEW

**Comment by alexvins** [comment]
@ArseniyShestakov could you please retest this PR

**Comment by ArseniyShestakov** [comment]
Just wonder, maybe you have some idea how to implement this one?
http://bugs.vcmi.eu/view.php?id=1376

**Comment by alexvins** [comment]
Ticket 1376 already contains possible solutions. Most elegant solution is to add ENEMY_DEFENCE_REDUCTION to arrow tower abilities.

**Comment by ArseniyShestakov** [comment]
So ENEMY_DEFENCE_REDUCTION will actually reduce any possible defense to zero?

**Comment by ArseniyShestakov** [comment]
So what I can say: at least catapult and empty slots problems are gone.
Though all this ressurect / summon still need refactoring.

**Comment by alexvins** [comment]
>So ENEMY_DEFENCE_REDUCTION will actually reduce any possible defense to zero?

**Comment by ArseniyShestakov** [comment]
So only suspicious thing I found is that cloned Pit Lords can as well use that skill, but end up that it's same behaviour in H3 (even if original cloned stack already used skill). So it's looks like that work well enough this time.

Only unrelated bug I seen is catapult resurrection (both archangels and spell).

**Comment by ArseniyShestakov** [comment]
Posted resurrection bug on mantis:
http://bugs.vcmi.eu/view.php?id=2407

**Pull request merged**
