### PR TITLE
radial wheel for hero-exchange

### PR DESCRIPTION
**Pull request by Laserlicht**
Radial Wheel menu for hero:
- Dismiss hero
- Open exchange between two heroes (only when two heroes in castle)
- Get all creatures from other hero (only when two heroes in castle)
- Get all artifacts from other hero (only when two heroes in castle)
- Swap creatures with other hero (only when two heroes in castle)
- Swap artifacts with other hero (only when two heroes in castle)

grafik

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Screenshot and description please?

**Comment by Laserlicht** [comment]
@IvanSavenko  Sorry. See above.

**Comment by IvanSavenko** [comment]
Swap heroes / dismiss hero - perhaps make icon smaller and/or give it more thinner lines?
Artifact icons - perhaps reuse backpack icon? Possibly downscaling it if needed? https://github.com/vcmi/vcmi/blob/develop/Mods/vcmi/Sprites/buttons/backpackButtonIcon.png

**Comment by Laserlicht** [comment]
I'm not really good in creating icons.

If someone want to create better fitting: feel free to make some. :)

I think we could also replace them later.

**Comment by IvanSavenko** [comment]
Slightly better icons (hopefully)

Can you try using them instead?
[icons.zip](https://github.com/vcmi/vcmi/files/12927564/icons.zip)

**Review by IvanSavenko — APPROVED** [review]

**Pull request merged**
