### PR TITLE
To be released as 0.100~beta1

### PR DESCRIPTION
**Pull request by alexvins**
Merging this pull request starts 0.100 release cycle. There is already a release draft for 0.100~beta1, merge commit of this PR will be released. No new features and re-factorings will be accepted until 0.100 release.

### CODE REVIEW

**Comment by DjWarmonger** [comment]
After 0.99 comes 1.00, not 0.100 :P

**Comment by adanski** [comment]
0.100 😃

**Comment by FeniksFire** [comment]
Better `0.100` than `1.0`, 
Anyway some future thoughts about versioning, in the future we should use `VERSION` with the `project()` command:
`project(projectName
[VERSION major[.minor[.patch[.tweak]]]]
[LANGUAGES languageName ...]
)`
Now it's better don't break it, because it requires changing cmake to 3.0.

**Comment by Alucard648** [comment]
Now we need list of all missing H3 features.

**Comment by alexvins** [comment]
@Alucard648 https://trello.com/b/68e5rAAl/vcmi-missing-features-only

**Comment by Alucard648** [comment]
I found this Trello board a bit outdated. For instance, ability to prevent hero from buying a spellbook is done in pull request #472, and corresponding Mantis ticket is marked as resolved.

**Comment by ArseniyShestakov** [comment]
Fixed it on Trello.
If someone want access to the board editing please let me know.

**Comment by josch** [comment]
Hi @nullkiller, thank you for all the commits you pushed in the last few hours! But why did you close this pull request without any comment as to why it can be closed instead of merged? I'm maintaining vcmi in Debian and for us it would be much appreciated if there were another release (like 0.100) instead of us having to pick any random git commit. Thanks!

**Comment by kambala-decapitator** [comment]
@josch we're preparing 1.00 release: https://github.com/vcmi/VCMI.eu/pull/7

**Pull request closed without merging**
