### PR TITLE
Gui cleanup3

### PR DESCRIPTION
**Pull request by alexvins**
* IImage is now being stored and used as shared_ptr
* Spell window has been reworked
* Changed most gui classes to use smart pointers

### CODE REVIEW

**Comment by alexvins** [comment]
Enough refactoring for now. Next part to be done in separate PR after #402 merge.

**Comment by ArseniyShestakov** [comment]
Ok first bug found: town selection is broken. Hero selection works, but town selection doesn't.

**Comment by ArseniyShestakov** [comment]
Next hero button also broken.

**Comment by ArseniyShestakov** [comment]
Next: "Scroll hero list" upper buttons always active and don't have right click text.

**Comment by ArseniyShestakov** [comment]
Sleep / Wake also broken, should change icon and switch for next hero which doesn't happen.

**Comment by ArseniyShestakov** [comment]
In hero levelup window label telling you ```%s is not level %d %s``` is missing.

screenshot_20180405_225245

**Comment by alexvins** [comment]
"Sleep / Wake" is not a regression, selection and levelup fixed.

**Comment by alexvins** [comment]
"Sleep / Wake" is not a regression, selection and levelup fixed.

**Comment by ArseniyShestakov** [comment]
Ok problems above that are not regressions in develop are fixed.

**Comment by ArseniyShestakov** [comment]
Another problem: right click on skills icons in levelup window doesn't bring popup.

**Comment by alexvins** [comment]
fixed both

**Comment by ArseniyShestakov** [comment]
One more regression, it's feels like main menu object not being fully destroyed when gameplay start. This in fact could be fault of my own branch, that's possible. But seems like this branch exposed problem even more.

Yet in this branch when you open "Artifact Merchant" menu and then left click on bottom middle artifact in the right I get "high scores menu not implemented" error and seems like if I click down there I also attempt to "exit game" via main menu and get dialog about it. Also once I got same thing appeared in battle so it's seems like universal problem.

**Pull request merged**
