### PR TITLE
Reindex objects to show interactive objects on top

### PR DESCRIPTION
**Pull request by DjWarmonger**
Some results:

Reindex 1
Reindex 2

**TODO**:

- [ ] Modify Windmill template instead of hardcoding it

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Only used for RMG maps. Correct?

**Comment by DjWarmonger** [comment]
I wonder about the editor.

**Comment by DjWarmonger** [comment]
@Ivan is there actually a way to patch original templates? I tried this, and Windmills stopped to spawn altogether:
```
				"templates": {
					"avmwms0" :{
						"zIndex" : 101
					},
					"avmwndd0" : {
						"zIndex" : 101
					}
				}
```

**Comment by IvanSavenko** [comment]
> @ivan is there actually a way to patch original templates? I tried this, and Windmills stopped to spawn altogether:

Might not possible actually. I think H3 templates bypass our modding system at the moment.

Why do you need it by the way?

**Comment by DjWarmonger** [comment]
I'd like to tweak z-index in config instead of hardcoding windmills. But it already works the way it is.

**Review by IvanSavenko — APPROVED** [review]

**Pull request merged**
