### PR TITLE
Fix 1989 cavaliers -> champions in stables

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Try to fix http://bugs.vcmi.eu/view.php?id=1989

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
Small comment about H3 behaviour: InfoWindow must appear as well even if it 2nd+ visit of stables and you just get an upgrade without any movement bonus.

**Comment by vmarkovtsev** [comment]
Damn, it will be much harder to display 2 InfoWindows - it is hardcoded to be a single window per CGBonusingObject, so there are going to be quite a few ugly hacks.
Besides, I need to find out the corresponding text ID. Can you post a screenshot of that window from OH3 please?

**Comment by ArseniyShestakov** [comment]
It's uses same text ID in H3 so there is no special message that only include information about upgrade.

As you note there was object refactoring, but unfortunately Ivan didn't find way to make objects fully configurable back then. So if adding infowindow on upgrade will require dirty hacks in code then just leave it as and post bug about unfinished UI feature on bug tracker.

**Comment by vmarkovtsev** [comment]
Am I right that if we visit stables for the first time and have cavaliers, the message says "... blah-blah you got champions", and if we visit stables for the second time and have cavaliers, exactly the same message must be shown (not the usual "you have already visited this")? Or should we concatenate "you have already visited this" with "you got champions" text and picture? The third variant is first display "you have already visited this" and then display  "... blah-blah you get champions" (the bad one - hard to implement).

**Comment by ArseniyShestakov** [comment]
Just show exactly same message as it's what H3 do.

**Comment by vmarkovtsev** [comment]
Got it, it's easy then

**Comment by vmarkovtsev** [comment]
Done

**Pull request merged**
