### PR TITLE
Fixed some configs

### PR DESCRIPTION
**Pull request by Olegmods**

### CODE REVIEW

**Comment by by003** [comment]
Need fix: 
1. Dungeon hero Jeddite is not female.
2. Special hero Mutare and Mutare Drake are not warlock.
3. Non Living creature, Gargoyle, Mechanical(not updated yet), War machine cannot be affected by Elixir of Life.
4. Resurrection cannot dispel nagative spell for target unit.

**Comment by Olegmods** [comment]
> Need to fix:
> 
> 1. Dungeon hero Jeddite is not female. `heroes/dungeon.json`
> 2. Special hero Mutare and Mutare Drake are not warlock. `heroes/special.json`
> 3. Non Living creature, Gargoyle, Mechanical(not updated yet), War machine cannot be affected by Elixir of Life. `artifacts.json`
> 4. Resurrection cannot dispel nagative spell for target unit. `spell/other.json`
> 5. Catapult is immune to Implosion. `creatures/special.json`
> 
> Please update these json files in config.

1. Fixed
2. Fixed
3. Added war machines' immunity to the config. Gargoyles and non-living creatures are actually in the config already.
4. Not too sure about that. Cannot find any info about how that works in OH3. Needs confirmation.
5. Fixed

**Comment by by003** [comment]
Resurrection will only recover the quantity of current creature, but not dispel any spells. Same as animate dead. Some other resurrection like spells I will fix it in the mod.

**Comment by Olegmods** [comment]
> Resurrection will only recover the quantity of current creature, but not dispel any spells. Same as animate dead. Some other resurrection like spells I will fix it in the mod. This is animate dead: image This is resurrection: image

Found some info regarding it. Seems Resurrection should dispel anything except Disrupting Ray, Acid Breath and Poison. And that's not all of the negative effects in OH3, so that will be harder to fix.

**Comment by by003** [comment]
Just remove the

**Comment by Olegmods** [comment]
> Just remove the fields in the red box.
> 
> image Reference from Might and Magic Wiki.

I have got another info from FizMig (I won't paste screenshot here since I don't want to translate the entry). So I guess that needs to be tested.

**Comment by Olegmods** [comment]
I guess the PR could be merged. Dispell effects are undocumented for now, so I don't know how to fix Resurrection.

**Pull request merged**
