### PR TITLE
Check for playing battle animations

### PR DESCRIPTION
**Pull request by wb180**
Don't start new staged animation, if there are animations playing. Otherwise it leads to situations, like in this [video](https://www.youtube.com/watch?v=pk9xFvjSsGc)(second cast)

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Sorry for delay.
Any idea how game ended up in such situation? Actually sounds like waitForAnimations() call is missing someplace else.

**Comment by wb180** [comment]
> Sorry for delay. Any idea how game ended up in such situation? Actually sounds like waitForAnimations() call is missing someplace else.

It happens like that:
1. BattleInterface::spellCast - it stages BEFORE_HIT and HIT animations
2. Another thread on timer update calls BattleStacksController::updateBattleAnimations - BEFORE_HIT animations start here
3. BattleStacksController::stacksAreAttacked - here HIT animations are starting to play, because there is no check

**Comment by IvanSavenko** [comment]
Sounds like step 2. is incorrect. updateBattleAnimations should not initiate animations when none are playing. It should only continue already started animation chain.

**Comment by wb180** [comment]
Unfortunately have no idea how to fix this properly, so if someone wants to fix this - feel free to do it.

**Comment by dydzio0614** [comment]
fixing client battle bugs in a nutshell xD

**Pull request closed without merging**
