### PR TITLE
MapEditor: Player settings improvements

### PR DESCRIPTION
**Pull request by Nordsoft91**
Within this RP few features are implemented:
 - Customizable colors for players
 - Finally teams supported in map editor
 - "export as" menu item: https://github.com/vcmi/vcmi/issues/1345
 - Partially resolved (in map validator functionality) https://github.com/vcmi/vcmi/issues/1256

### CODE REVIEW

**Comment by Nordsoft91** [comment]
@DjWarmonger ?

**Comment by DjWarmonger** [comment]
Ahh, will take a look today.

**Comment by DjWarmonger** [comment]
Not exactly what I meant. It takes a screenshot of a visible window, but not the entire map ¯\_(ツ)_/¯
Diamond Stardust

Also, .jpeg export didn't work once I exported .png in the same folder, with same name/

**Comment by DjWarmonger** [comment]
Also, you may want to automatically resize the player settings window:
image

**Comment by Nordsoft91** [comment]
@DjWarmonger , thanks!

> Not exactly what I meant. It takes a screenshot of a visible window, but not the entire map ¯_(ツ)_/¯

Now full map exported.

> Also, .jpeg export didn't work once I exported .png in the same folder, with same name/

Cannot reproduce (

> Also, you may want to automatically resize the player settings window

Cannot reproduce, but tried to fix. Need another run from you to verify

**Comment by DjWarmonger** [comment]
Will try to fix player settings window, not trivial as I thought.

**Pull request merged**
