### PR TITLE
Improve metainfo file

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
Since the Slack chat seems to focus on development and software centers usually have a separate section to show license info.

E.g.:

image

### CODE REVIEW

**Comment by krs0** [comment]
There are some annoying warnings on CI about slack plugin. Would that fall into this cleanup category?

**Comment by Alexander-Wilms** [comment]
I'm not sure what you mean.

I know there are a bunch of warnings because the secret is not available, but would you prefer to remove the Slack integration or fix it?

Also, that's not something I can do.

**Comment by krs0** [comment]
Yeah it was about the missing secret.
@someone else knows how to fix it

**Review by IvanSavenko — APPROVED** [review]

**Comment by Nordsoft91** [comment]
@ArseniyShestakov should probably know slack secret

**Pull request merged**
