### PR TITLE
Shift center of tiling to center of the map

### PR DESCRIPTION
**Pull request by DjWarmonger**
Should fix crashes related to Penrose tiling for good.

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Unfortunately problem still exists...
[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/15247501/VCMI_Client_log.zip)
```
[2024-May-08 13:23:09.910541] INFO [runServer] global - RMG map: 108x108, NO underground
[2024-May-08 13:23:09.910871] INFO [runServer] global - RMG settings: players 8, teams -1, computer players 0, computer teams -1, water 0, monsters 3
[2024-May-08 13:23:09.911113] INFO [runServer] global - RMG template name: 8XM8
```
Check log for penrose tiling dump

**Comment by DjWarmonger** [comment]
L no U is too small for this template and it won't be playable anyway.

**Comment by IvanSavenko** [comment]
Then its size should be bumped.
What should be its minimal size? XL? L+U?
Will check other templates

**Comment by IvanSavenko** [comment]
8XM8 crashes even at XL+U

[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/15247602/VCMI_Client_log.zip)

**Comment by IvanSavenko** [comment]
Jebus - stable, both L and XL sizes
6LM10a XL+U - crashed on ~10th attempt

[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/15247697/VCMI_Client_log.zip)
(huge log with multiple rmg runs)

**Comment by IvanSavenko** [comment]
I am not so lucky...
1st attempt to run new build:
```
[2024-May-08 14:52:30.978326] INFO [runServer] global - RMG map: 144x144, NO underground
[2024-May-08 14:52:30.978686] INFO [runServer] global - RMG settings: players 8, teams -1, computer players 0, computer teams -1, water 0, monsters 3
[2024-May-08 14:52:30.979931] INFO [runServer] global - RMG template name: 8XM8
```

[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/15248394/VCMI_Client_log.zip)
I think it is now better than before? 8XM8, XL-U now crashes... around 20% of runs maybe?

Got crash on 8XM8, XL+U:
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/15248467/VCMI_Server_log.txt)

**Comment by dydzio0614** [comment]
to automate the process maybe triggering game restart from code after scenario load might help, so restart will loop eternally until VCMI crashes - each restart generates new map (and it should stay that way)

**Comment by IvanSavenko** [comment]
Not just 8XM8. Other templates may also crash, even Jebus L-U:
[Jebus.zip](https://github.com/vcmi/vcmi/files/15248693/Jebus.zip)
Less often than cursed 8XM8, but not zero.

**Comment by DjWarmonger** [comment]
> Got crash on 8XM8, XL+U: [VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/15248467/VCMI_Server_log.txt)

This is very suspicious:
`[2024-Apr-12 22:23:10.794102] INFO network - Thread listening for Connection with **VCMI 1.4.3** (server) (ID: 1 UUID: 0a815255-4345-405b-baac-d0eab16a3cde) ended`

For me it reads "VCMI 1.5.0" as expected.

**Comment by IvanSavenko** [comment]
Sorry, wrong log. We don't even write server log now.

Here is crash on your current build, `VCMI 1.5.0.765760fe7dfac3af960a503ff340e5dcf745b17d`
8XM8, XL-U.
Crash on 8th rmg run:
[8XM8.zip](https://github.com/vcmi/vcmi/files/15249039/8XM8.zip)

**Comment by DjWarmonger** [comment]
Now this is actually very interesting.
`[2024-May-08 15:43:33.639258] INFO [runServer] global - Generated 15971 vertices and 431 unique vertices`
8XM8 431 unique vertices

**Comment by IvanSavenko** [comment]
Oh, and you should be able to reproduce it using mingw builds from CI if you only have Visual Studio setup.

**Comment by DjWarmonger** [comment]
Oh, just figured this out as well

**Comment by IvanSavenko** [comment]
Okay, ~10 runs of cursed 8XM8 on L-U
0 crashes so far.

Yes, hard to call it 'playable' due to huge amount of tiny zones, but that's to be expected considering the template

Will test a little bit more, but so far looks OK.

**Comment by IvanSavenko** [comment]
Yeah, seems to be fixed. 
0 crashes on ~100 runs with multiple different templates and different map sizes.
Thanks.

**Pull request merged**
