### PR TITLE
VCMI credits

### PR DESCRIPTION
**Pull request by Laserlicht**
what do you think about it?

### CODE REVIEW

**Comment by krs0** [comment]
Nice to have something like this, but more people should be on that list than only developers.
Modders should be listed?
And Misiokles needs a special category :)

**Comment by Laserlicht** [comment]
I think modders have already a place to get credit: In the launcher at each mod (author field).

**Comment by Nordsoft91** [comment]
How about parsing https://github.com/vcmi/vcmi/blob/develop/AUTHORS ?

Maybe revise a structure of this file to json or something easy to parse. Then no need to do one more manual step prior release

**Comment by IvanSavenko** [comment]
Taking use of AUTHORS file makes sense, but for that we'll need to:
- ensure that this file is installed on all platforms
- update that file - drop horribly outdated "what person does" part, check for missing contributors, add non-coding contributors such as QA (Povelitel, Misiokles, etc). Possibly remove emails?
- move this file or copy it - vcmi does not includes root directory in virtual filesystem, it needs to be in config directory.

**Comment by Laserlicht** [comment]
New approach.

What do you think about it. Could also be displayed by launcher. In Client: Only usernames are shown (because of encoding).
Also the groups are displayed in Client.

**Comment by IvanSavenko** [comment]
Personal opinion on new approach:
- Not sure about removal of AUTHORS file. Personally OK with that but others might disagree
- Probably drop email completely
- For those with both name and nickname we should probably display both - e.g. "Michał Urbańczyk aka Tow"
- Encoding is an issue, but I think can be ignored for now - we likely need to integrate unicode-capable font for 1.4 anyway, for MP chat.

**Comment by Laserlicht** [comment]
@IvanSavenko 

> Probably drop email completely

Okay for me - but if we add authors to launcher too we can also add a "mailto://"-link.

> For those with both name and nickname we should probably display both - e.g. "Michał Urbańczyk aka Tow"

Possible but ingame it's to long (2-3 lines per name; nickname only one line) -> looks not good. But maybe in the launcher?

**Comment by by003** [comment]
VCMI is amazing for many mods, although I am not a developer, I still contributed many mods for it. I reckon modding is one of the attraction aspects for VCMI as well.

**Comment by IvanSavenko** [comment]
> Possible but ingame it's to long (2-3 lines per name; nickname only one line) -> looks not good. But maybe in the launcher?
See video above.

Yeah, watched video only after than message.

Option 1: keep as it is now
Option 2: add line breaks after every name and use format `(real name) \n aka (nickname) \n (empty line)`

Also:
- Give Tow and Tow Dragon special category as project founders?
- Perhaps sort names? Alphabetically probably to be safe. By contributions would also work, but rather arbitrary.

**Comment by Nordsoft91** [comment]
> Perhaps sort names? Alphabetically probably to be safe. By contributions would also work, but rather arbitrary.

Usually it's not sorted alphabetically. Historical order (authors are added sequentially) is more common approach.

> Not sure about removal of AUTHORS file. Personally OK with that but others might disagree

Probably fine to remove file but let's keep short contribution summary which is in the file (without showing it in game)

**Comment by IvanSavenko** [comment]
Might be good idea to add at least these people:
[rilian-la-te](https://github.com/rilian-la-te)
[henningkoehlernz](https://github.com/henningkoehlernz)
[SoundSSGood](https://github.com/SoundSSGood)
[vmarkovtsev](https://github.com/vmarkovtsev)
[krs0](https://github.com/krs0)

They have significant number of commits in stats, but looks to be missing from authors list.

> Probably fine to remove file but let's keep short contribution summary which is in the file (without showing it in game)

That list is horribly incomplete even for no longer active devs

**Review by IvanSavenko — APPROVED** [review]

**Comment by Laserlicht** [comment]
> Might be good idea to add at least these people: [rilian-la-te](https://github.com/rilian-la-te) [henningkoehlernz](https://github.com/henningkoehlernz) [SoundSSGood](https://github.com/SoundSSGood) [vmarkovtsev](https://github.com/vmarkovtsev) [krs0](https://github.com/krs0)

done :)

**Comment by by003** [comment]
Can you add me into test? I have already tested many kinds of bugs and they were already fixed.

**Comment by Laserlicht** [comment]
> Can you add me into test? I have already tested many kinds of bugs and they were already fixed.

done :)

**Comment by by003** [comment]
> > Can you add me into test? I have already tested many kinds of bugs and they were already fixed.
> 
> done :)

Thanks, my email address is benyan9110@gmail.com, same in my mods introduction

**Pull request merged**
