### PR TITLE
add vcmibuilder version check for innoextract

### PR DESCRIPTION
**Pull request by paulsetchko**
add vcmibuilder check for the old innoextract is unable to unpack the latest GOG package

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
I don't get why this ```printf``` needed, but really you should at least check if version is greater.

**Comment by paulsetchko** [comment]
fixed the commented issue; do you know why is that travis takes so long to start the mac build?

**Comment by ArseniyShestakov** [comment]
Travis usually takes long on Mac builds mainly because we commit a lot and they have limited Mac instances pool. Regardless it's not required for this to be merged since we don't really expose it on macOS.

**Comment by ArseniyShestakov** [comment]
Sorry for taking long to merge this, had to check that innoextract on 14.04(1.4) and 16.04 (1.5) in fact use same version output. Thanks for contributing!

**Pull request merged**
