### PR TITLE
InfoBar: disable scrollbar

### LINKED ISSUE #1898: Visual bug with extra text for Artifact in Info Panel
**Describe the bug**
Extra Text? / Story for artifact shows scrollable window....

**To Reproduce**
1. Place Clover of Fortune artifact on a map.
2. Pick it up
3. See Info Panel for scroll elements

**Expected behavior**
If too much text... show a proper window

**Screenshots**
image

**Version**
 - OS: windows
 - Version: beta

### PR DESCRIPTION
**Pull request by rilian-la-te**
Fixes #1898 

@krs0, please test.

### CODE REVIEW

**Comment by rilian-la-te** [comment]
How it look now: 

image

@krs0

**Comment by krs0** [comment]
Text is truncated... but is better than incomplete scroll window.
image

**Comment by rilian-la-te** [comment]
@krs0 can you show a full text of this artifact?

**Comment by rilian-la-te** [comment]
@krs0 another PR update. Now it shows story only if it can show a full story. Text is no longer truncated. Can you test it?
image

**Comment by krs0** [comment]
Will test.

**Comment by krs0** [comment]
Looks ok.

**Pull request merged**
