### PR TITLE
Share visited status of CPlayersVisited objects across team

### PR DESCRIPTION
**Pull request by Chocimier**
It makes sense for all such objects - cartographer, obelisk, shrine and witch hut. 
Should it be renamed to CTeamVisited?

### CODE REVIEW

**Comment by DjWarmonger** [comment]
Probably yes. Now I see wasVisited() calls wasVisited() :v

**Comment by ArseniyShestakov** [comment]
Actually I expect we could have objects that visiting status might be not shared across team. Thoughts?

**Comment by Chocimier** [comment]
I see that CPlayersVisited does nearly the same what is done with CRewardableObject::VISIT_PLAYER.
So we can move CRewardableObject::wasVisited to CGObjectInstance, add there VISIT_TEAM and remove CPlayersVisited.

Another issue: what it means for bank to be visited: look into and know what guards are there or defeat?

**Comment by ArseniyShestakov** [comment]
We cannot just "move" them for two reasons:

- There is save serialization breakage involved.
- Those objects remained separate exactly because map object refactoring wasn't completed.

So unless you want to do some heavy refactoring and complete what Ivan started long ago there is no reason to toss code around at all. Might be we could rename them then and leave everything as is if CRewardable object can already handle object that visited once per player OR team.

**Comment by Chocimier** [comment]
Yes, CRewardable can handle per player visit and also can handle per team visit.

Sorry, but I do not understand - what am I supposed to do now?

**Comment by ArseniyShestakov** [comment]
Sorry for not answering straight away. If all objects still using CPlayersVisited should be "team visited" then you can rename it and please add comment that it's legacy class and it's not to be used.

As long as it's not break anything that should be fine.

**Comment by ArseniyShestakov** [comment]
I didn't want to bother you to fix formatting, so I just squashed / merged it manually.
Next time please fix formatting along the way. Thanks.

**Pull request closed without merging**
