### PR TITLE
Spells refactoring5

### PR DESCRIPTION
**Pull request by alexvins**
* adventure-related spells refactoring
* file structure reorganisation
* implemented VIEW_AIR VIEW_EARTH VISIONS DISGUISE spells
* no more features planned in this branch, need testing

### CODE REVIEW

**Comment by DjWarmonger** [comment]
I just realized this case can be tricky and wait for later.

**Comment by alexvins** [comment]
Now VIEW_AIR, VIEW_EARTH (except expert  VIEW_EARTH) handled on server side.

**Comment by alexvins** [comment]
Where is /lib/spells/CDefaultSpellMechanics.h after merge?

**Comment by ArseniyShestakov** [comment]
Also as far as I get contents of this file is incorrect:
https://github.com/vcmi/vcmi/blob/develop/lib/spells/CSpellHandler.cpp
https://github.com/alexvins/vcmi/blob/SpellsRefactoring5/lib/spells/CSpellHandler.cpp

In develop it's still mention "SpellMechanics.h" while it's have to be "ISpellMechanics.h".
So possible more code isn't merged properly.

**Comment by alexvins** [comment]
There are different files: CDefaultSpellMechanics.h and ISpellMechanics.h in SR5 and SpellMechanics.h is old file. I`ll fix if myself in develop. Please, be careful later.

**Comment by alexvins** [comment]
Also:
1) "spells/CSpellHandler.h" is still main spell-related "entry point" for the rest of engine.
2) ISpellMechanics.h is the only entry point for mechanics and used only by  CSpellHandler.cpp
3) any other files in spells directory are "hidden details" and should not be used anywhere else

**Pull request merged**
