### PR TITLE
vcmi: russian

### PR DESCRIPTION
**Pull request by rilian-la-te**

### CODE REVIEW

**Comment by rilian-la-te** [comment]
@kambala-decapitator this PR should target both, but I do not know how to make a PR than targets both.

**Comment by kambala-decapitator** [comment]
either do in separate PRs or target just beta if not a blocker - beta will be merged in develop after the release

**Comment by rilian-la-te** [comment]
@kambala-decapitator second PR for beta done, feel free to merge into beta.

**Comment by IvanSavenko** [comment]
Ah, missed that this was for develop.
@rilian-la-te depending on need/activity in beta branch I'll merge beta into develop from time to time, so no need for duplicated PR's for both

**Pull request merged**
