### PR TITLE
Erase boat object goals on hero death

### PR DESCRIPTION
**Pull request by dydzio0614**
This code may fix bug #3021 - unsure.

### CODE REVIEW

**Comment by ArseniyShestakov** [comment]
Are you absolutely sure it's not handled by ```VCAI::objectRemoved```?

**Comment by DjWarmonger** [comment]
I don't quite get it either. If hero is in a boat, he's still a hero. If there's boat without hero, it's just ordinary object. Even if there's a bug, this shouldn't need a special treatment.

**Comment by dydzio0614** [comment]
Yeah, now this code looks invalid for me. The problem is that for some reason AI does not reliably remove goals related to boarded hero when hero on boat dies.

**Comment by DjWarmonger** [comment]
IIRC there was a bug also where normal land hero is lost., is it any different?

**Pull request closed without merging**
