### PR TITLE
Improve neutral creature adventure map popup

### LINKED ISSUE #2459: Add creature portrait for r-click popup on adventure map
**Describe your proposal**
Add creature portrait to this pop-up to make it a little bit clearer.
image

Right now the popup completely covers the creature in question, which can be confusing with many creatures added via mods.

### PR DESCRIPTION
**Pull request by dydzio0614**
Improve neutral creatures adventure map popup to better match H3:
image

Not ideal, but improvement over what we currently have, main leftover annoyance being text vertical layout (horizontal layout consistency was prioritized). Optimal solution would be creating TOPCENTER text alignment and I do not plan to dig further in this window for now, due to bad [time spent / impact on playability] ratio

Fixes #2459

### CODE REVIEW

**Comment by dydzio0614** [comment]
this screenshot was made with vision spell effect for max amount of content

**Comment by krs0** [comment]
```
	auto creatureData = (*CGI->creh)[creature->stacks.begin()->second->getCreatureID()].get();
	creatureImage = std::make_shared<CAnimImage>(graphics->getAnimation("TWCRPORT"), creatureData->getIconIndex());
```

is this not a recurring function in all VCMI code base: GetCreaturePortraitLarge(creature)?

**Comment by dydzio0614** [comment]
@krs0 what? There is portraitLarge for heroes and no such thing for creatures

BTW anything needed to merge this?

**Comment by dydzio0614** [comment]
obraz

Quick-added new text alignment, seems to work OK

**Comment by krs0** [comment]
What I meant was that that complicated code would be easier on the eye if hidden in a function: getCreatureIcon(creatureId)

**Comment by IvanSavenko** [comment]
Perhaps adjust height based on text size?

**Comment by dydzio0614** [comment]
Height of what? Line wrapping works OK and line break between sections "quantity", "visions info", "threat" matches H3 (except threat being our addition). Space between picture and text pixel-perfect matches H3

**Comment by dydzio0614** [comment]
@krs0 maybe, but I find these 2 lines to be short code and pretty readable, there is also no sign for code reuse potential. I could create lambda for these 2 lines and call it below but it would be probably more of code obfuscation than help

**Pull request merged**
