### PR TITLE
Mine roads

### PR DESCRIPTION
**Pull request by DjWarmonger**
If zone has only one entry and no towns, it will have no roads.

In such case RMG will create dirt roads to mines if possible.

### CODE REVIEW

**Comment by Alucard648** [comment]
Is it possible to create branching roads to mines in regular zones, like player start zones?

**Comment by DjWarmonger** [comment]
> Is it possible to create branching roads to mines in regular zones, like player start zones?

Possible - yes, but more complicted. Also I think it'd be an overkill to have roads all over the zone.

**Comment by Alucard648** [comment]
> Also I think it'd be an overkill to have roads all over the zone.

It should be a template setting. For template editor.

**Comment by Nordsoft91** [comment]
There should be easier solution - take a look at ObjectManager::placeObject. Maybe adding node there + filtering inside roadPlacer would be better

**Comment by Alucard648** [comment]
> There should be easier solution - take a look at ObjectManager::placeObject. Maybe adding node there + filtering inside roadPlacer would be better

Agreed. This would allow template designer to include road connection with other important elements of generated map, such as dragon utopias.

**Pull request merged**
