### PR TITLE
Do not show mod entries without name

### LINKED ISSUE #2849: Empty line in launcher for stardust-terrain mod
**Describe the bug**
image

**To Reproduce**
1. Install 1.3.2
2. See empty line in launcher

**Version**
 - OS: [e.g. Windows,
 - 1.3.2

### PR DESCRIPTION
**Pull request by Nordsoft91**
Fixes #2849

### CODE REVIEW

**Comment by krs0** [comment]
How can the name be null? Is there a correction needed in the mod as well?

**Comment by IvanSavenko** [comment]
Why are we hiding such mods? Can player (for example) delete such mod if he have one?
In which cases this might happen? Is it possible that this mod will be present in game but hidden in Launcher?

**Comment by Nordsoft91** [comment]
> How can the name be null? Is there a correction needed in the mod as well?

We don't have mod names in repository, and only links

https://github.com/vcmi/vcmi-mods-repository/blob/develop/vcmi-1.4.json

**Comment by Nordsoft91** [comment]
> Why are we hiding such mods? Can player (for example) delete such mod if he have one?
> 
> In which cases this might happen? Is it possible that this mod will be present in game but hidden in Launcher?

There are several possible ways to handle this, hiding is less disruptive, then showing something impossible to install. I will test for local mod, but technically only remote mod can be checked.

**Comment by krs0** [comment]
> > How can the name be null? Is there a correction needed in the mod as well?
> 
> We don't have mod names in repository, only links
> 
> https://github.com/vcmi/vcmi-mods-repository/blob/develop/vcmi-1.4.json

ok but in those links the name property is set correctly to : "name" : "Stardust and Fields of Glory terrain". It is still null for some reason.

**Comment by Nordsoft91** [comment]
Mod is incompatible- that's why it's not shown. But record is there, because mod is contained in repository

**Comment by krs0** [comment]
I would list the mod anyway as disabled.
If I had a mod installed and upg VCMI and mod would disappear from list, I would be surprised :)

**Comment by Nordsoft91** [comment]
It's not supposed to be. It's about downloadable mods

**Comment by IvanSavenko** [comment]
> Mod is incompatible- that's why it's not shown. But record is there, because mod is contained in repository

Why we are hiding mod based on empty name instead of on compatibility status?

**Comment by Nordsoft91** [comment]
> Why we are hiding mod based on empty name instead of on compatibility status?

what do you mean? We have empty empty name because of compatibility status

**Pull request merged**
