### PR TITLE
Battle fast targets

### PR DESCRIPTION
**Pull request by nullkiller**
It targets beta for now but not intended to be included as hotfix.
The idea is to reduce amount of canBeCastAt(). Has not significant performance improvement.

### CODE REVIEW

**Comment by nullkiller** [comment]
Some tests show that spellcast evaluation time can be reduced by up to 50% when a lot of spells are in spellbook.

**Comment by DjWarmonger** [comment]
Looks good to me, calculating the speed outside the loop is definitely the way.

**Comment by nullkiller** [comment]
Yes this patch is quite simple, but may theoretically affect real spellcasting. So I checked manually and have not found any issues so far.

**Comment by DjWarmonger** [comment]
Okay, for now I can tell it works.

**Comment by DjWarmonger** [comment]
So, what are we waiting for?

**Comment by nullkiller** [comment]
Ok, this can be merged. It is not complex so hardly can break anything

**Pull request merged**
