### PR TITLE
Use boost::multi_array to store FoW and other map-related info

### PR DESCRIPTION
**Pull request by DjWarmonger**
Do not merge, breaks savegame compatibility. Things to do in this branch:

- [x] Move all map-related structures to 3D arrays

- [x] Swap coordinates to [z][x][y] for optimized access

- [x] Merge PR #128

### CODE REVIEW

**Comment by viciious** [comment]
boost:multi_array has its share of performance problems, see http://stackoverflow.com/questions/446866/boostmulti-array-performance-question

**Comment by DjWarmonger** [comment]
@viciious I read that thread you linked and the tets in masterpost is obviously flawed. What I'm going to eventually do here is to optimize memory access - locality and remove the vector pile. Of course nothing can break POD array here, but at least interface is cleaner.

**Comment by DjWarmonger** [comment]
Okay, I admit I do it all mostly for practice :P. Maybe Android users will see any performance improvements, for PC it's already fast enough.

**Comment by DjWarmonger** [comment]
The branch is finished for now, waiting for better days to merge.

**Comment by ArseniyShestakov** [comment]
Is there reason to not simply add compatibility code?

**Comment by DjWarmonger** [comment]
@alexvins These error messages seem to be unrelated to anything I submitted in this commit, though :v @ArseniyShestakov This would require more code than the branch itself.

**Comment by alexvins** [comment]
@DjWarmonger error produced by recent 2-3 commits (after  	a98ebc0). But yes they are just exactly your fault

**Comment by viciious** [comment]
Has any of the work related to this ended up in master? Last time I checked, the cache-related optimizations were still relevant

**Comment by DjWarmonger** [comment]
> Has any of the work related to this ended up in master? Last time I checked, the cache-related optimizations were still relevant

Yep, here: https://github.com/vcmi/vcmi/pull/912

**Pull request closed without merging**
