### PR TITLE
Add commander resurrection info window upon entering town

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Do you know the correct info window text? I dumped allTexts to no avail.

### CODE REVIEW

**Comment by alexvins** [comment]
this a WoG feature, so the text should be somewhere in ZMESS00.TXT and we heed to handle situation when wog mod is not present.

**Comment by alexvins** [comment]
One solution would be put text to config\translate.json or combine with wog text - use translate.json as a fall-back.

**Comment by vmarkovtsev** [comment]
The correct messages appear in ZNPC00.txt. I am unable to play original WoG at the moment, but it seems to me that commanders shall be recovered after paying money. Do we have those mechanics defined in some document? @ArseniyShestakov you may know this...

**Comment by ArseniyShestakov** [comment]
Sorry, but in this case I can't do much except to test it later since I don't play with WoG usually.

**Comment by vmarkovtsev** [comment]
Merging this because the problem appeared to be much deeper than I thought. We have to implement commander both hiring and reviving.

**Pull request merged**
