### PR TITLE
 Use 64px and 32px as icon sizes in launcher sidebar

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
image

### CODE REVIEW

**Comment by IvanSavenko** [comment]
60 -> 64px change might be a good idea to reduce scaling artifacts but help & map editor are deliberately smaller than rest - Launcher is used on iOS with very limited vertical space. So less "important" icons were made smaller to avoid overflow

**Comment by Alexander-Wilms** [comment]
Alright, I've changed he smaller ones to 32px:

image

**Review by IvanSavenko — APPROVED** [review]

**Comment by Nordsoft91** [comment]
Actually, it introduces a little cosmetic defect on iOS
IMG_4722
IMG_4723

**Comment by Alexander-Wilms** [comment]
Maybe set them all to 48px?

image

Or just leave it as is?

**Comment by Nordsoft91** [comment]
Let's merge as is. There should be software solution for this

**Pull request merged**
