### PR TITLE
Crashfixes

### PR DESCRIPTION
**Pull request by IvanSavenko**
- Added check for presence of AB files to detect incomplete data early
- Fixed crash on loading maps if Scholar has been changed to not be a "rewardable" object
- Fixed memory corruption on using member after delete in radial wheel for town/hero sorting
- Fixed crash on randomizing dwelling when no suitable dwelling was found
- Attempt to fix crash on destruction of object classes handler

Merging to master, will upload to Google Play to monitor situation with crashes.

### CODE REVIEW

**Comment by Laserlicht** [comment]
>     * Fixed memory corruption on using member after delete in radial wheel for town/hero sorting

This change break the sort town feature. The `updateWidget` is needed. :(

**Comment by IvanSavenko** [comment]
For me that redraw would always happen instantly? Probably when radial wheel is closed. Have not noticed any issues with reordering...

**Comment by Laserlicht** [comment]
https://github.com/vcmi/vcmi/assets/13953785/99f21f0f-fa6c-48f7-9e53-c028dcbeada6

**Comment by IvanSavenko** [comment]
Will recheck.
I was testing mostly with towns, might be different with heroes

**Comment by IvanSavenko** [comment]
Confirmed, will fix

**Pull request merged**
