### PR TITLE
Catapult nearest wall

### PR DESCRIPTION
**Pull request by rilian-la-te**
Catapult now to be able to choose nearest wall instead of random.

(fixes part of #1236)

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Hmm... 
Not sure about this.
1) I doubt that this how H3 works here. Such details are not documented anywhere. Have you investigated it and confirmed or you're basing this on my comment?
2) Current code is already close enough - very few players will notice a difference, so not sure if there is any need to add another code that also does not matches H3
3) Really dislike such brute-force approach. Picking 2 closest targets would have been better instead of hardcoding every possible combination

**Comment by rilian-la-te** [comment]
@IvanSavenko I am not sure too. I think old approach was good enough, but you have a TODO inside your meta-issue.

About distance - we currently does not have such method as count wall distance. Should I add this method?

**Comment by rilian-la-te** [comment]
@IvanSavenko FizMig does not says anything about catapult and how it should hit target, if it misses.

**Comment by dydzio0614** [comment]
then do something moir or less similar for now and add TODO?

**Comment by IvanSavenko** [comment]
> About distance - we currently does not have such method as count wall distance. Should I add this method?

Indirectly it already exists - you can check distance between hexes to which walls are bound. However it won't match H3. I only tested few cases, but at the very least with gates catapult would randomly attack wall above or below. But as it is now, distance (in hexes) from these walls to gates would not b equal due to how they are placed.

Personally I would rather leave it as it for now until we find (or investigate in details) H3 behavior here.

> then do something more or less similar for now and add TODO?

That's precisely what I did :)

**Comment by rilian-la-te** [comment]
So, let's close it then? (without merging)?

**Comment by IvanSavenko** [comment]
Probably yes.

**Pull request closed without merging**
