### PR TITLE
Update VCMI icon

### LINKED ISSUE #1993: HD executable icon for windows
**Describe your proposal**
Draw a HD executable icon for windows :D

**Additional context**
image

icon not feet the modern system hd icon

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
Fixes #1993

Sources will be added to https://github.com/vcmi/vcmi-assets

### CODE REVIEW

**Comment by PingPongun** [comment]
New icons look nice, but I have two objections/questions:
1. Shouldn't shield be a little bit larger (so it would almost match height of whole icon)? In previous icon height of shield was circa 92% of icon height, in new icons shield is about 80% of icon height. It could bring some visibility improvement to smaller icon sizes.
2. What about changing font, there was also some dispute about it here and on Discord? Wouldn't the one proposed by Andruids/Dydzio on Discord match new shield design better than current, pixelated one?

**Comment by DjWarmonger** [comment]
>It could bring some visibility improvement to smaller icon sizes.

I don't think so, the issue is readability letters, not the shield.

And please make no style changes after a number of people cast their votes on this one.

**Comment by IvanSavenko** [comment]
Agree on shield size - original/proposed version actually had larger shield:
https://cdn.discordapp.com/attachments/298106089885401090/1143877748016812192/vcmi-icons.png
Should occupy all/almost all vertical space, just like old icon.

Font - better to keep as it. Haven't seen any clearly better options, this version is what was discussed, and we want to keep some similarity with old icon, to stay recognizable.

**Review by Nordsoft91 — COMMENTED** [review]
Awesome, great job!

Please, update also:
- launcher/icons/menu-game.png
- launcher/VCMI_launcher.ico

Agree with comment about shield size - larger would look better

**Comment by PingPongun** [comment]
> And please make no style changes after a number of people cast their votes on this one.

There wasn't much of a choice regarding the font, so I guess some people (including me) voted for the shield design mostly. There could be always second stage of voting

Quick glance at scaled shield:
image3
A- from this PR; 
B- shield height is 99% of icon size; 
C- as B, but changed font (, however now, looking at it, I'm no longer sure if it's that much better than older one: it looks better, but it's slightly less readable)

**Comment by dydzio0614** [comment]
font from C is million times better

**Comment by IvanSavenko** [comment]
> font from C is million times better... I prefer bigger size as well

But if this icon is downscaled 2-3 times then text on C is completely unreadable, while A&B are still clearly visible.

**Comment by Alexander-Wilms** [comment]
The second version turned out a bit less saturated:

First commit:
vcmiclient 128x128

Second commit:
vcmiclient 128x128-1

Should the brown sections be more or less saturated?

**Comment by IvanSavenko** [comment]
More saturated version. Looks better (IMO) and more similar to our current icon

**Comment by Laserlicht** [comment]
@Alexander-Wilms Looks really nice. :)
Like also the optimizations for the small files and the solution for SVG graphics.

But there are more files to replace: For Android and Apple. Have a look here: https://github.com/vcmi/vcmi/pull/1999/files
In the PR is also a description to create ICNS file on linux.

**Comment by Alexander-Wilms** [comment]
I'll add the remaining icons this evening.

**Comment by Alexander-Wilms** [comment]
I think I've replaced all of them. If the installer is still using the old icon, do you know which one I might've missed?

**Comment by Laserlicht** [comment]
This file is missing: https://github.com/vcmi/vcmi/blob/develop/osx/vcmi.icns

**Comment by Alexander-Wilms** [comment]
Maybe the commits should be squashed before merging.

**Comment by Nordsoft91** [comment]
MacOS-arm tested: OK
iOS: app icon not updated

**Comment by Laserlicht** [comment]
Also not correct:
- ico contains only a few sizes, but should contain all image sizes (up to 2048)

Missing:
- /mapeditor/icons/menu-game.png
- /Mods/vcmi/Sprites/mapFormatIcons/vcmi1.png
- /client/ios/Images.xcassets/AppIcon.appiconset
- /client/vcmi.ico

**Comment by Alexander-Wilms** [comment]
I added the remaining icons and fixed the .ico files

**Comment by IvanSavenko** [comment]
Looks like something is wrong with Windows installer in CI...

**Comment by Alexander-Wilms** [comment]
Some of the sizes were compressed as PNG, that probably caused the issue:

image

**Comment by Alexander-Wilms** [comment]
Microsoft applications apparently only ship .ico files with a resolution of up to 256px: https://stackoverflow.com/a/74392449/2278742

**Comment by Laserlicht** [comment]
Looks good on Windows. Nice, thanks!

Only a minor thing:
grafik

Can you use the same resolution as before for this icon and center the shield on this?

**Comment by Alexander-Wilms** [comment]
Fixed.

**Pull request merged**
