### PR TITLE
Spells refactoring8

### PR DESCRIPTION
**Pull request by alexvins**
Relevant tickets
- http://bugs.vcmi.eu/view.php?id=2302
- http://bugs.vcmi.eu/view.php?id=2419
- http://bugs.vcmi.eu/view.php?id=2422
- http://bugs.vcmi.eu/view.php?id=2491
- http://bugs.vcmi.eu/view.php?id=2498
- http://bugs.vcmi.eu/view.php?id=2499

### CODE REVIEW

**Comment by alexvins** [comment]
Feature freeze.

**Comment by ArseniyShestakov** [comment]
Ok clones are now fixed and AI games working fine so far.

**Comment by ArseniyShestakov** [comment]
This one not fix it problem with obstacles on wall hexes

**Comment by ArseniyShestakov** [comment]
Sadly they could still appear under the wall parts on hexes 12 and 166.
Probably some return of battle callback not quite valid.

Also I not sure if landmines actually can do damage so going to test this too.

**Comment by ArseniyShestakov** [comment]
Ok I tested land mines and quicksand. They do work properly.

**Pull request merged**
