### PR TITLE
Concurrent battles support

### PR DESCRIPTION
**Pull request by IvanSavenko**
Goal is to remove all references to "curB" and other ways to access ongoing battle and replace them with access by ID. General assumptions:
- It should be possible for multiple battles to happen in the same time
- Single player can only be engaged into a single battle
- Except for neutral "player", who can be present in multiple battles (e.g. several battles with neutrals)
- Battles are not serializeable - it is not possible to save game while there is an ongoing battle (can be changed in future, but low-priority task for now)

Current progress:
- [x] multiple battles in GameState
- [x] multiple battles in server logic
- [x] remove/replace CCallbackBase::battle member
- [x] multiple battles in client logic
- [x] ensure that all battle-related netpacks always receive correct BattleID
- [x] test everything

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Mostly done, will do another testing round, but basic functionality seems to be working.

**Comment by rilian-la-te** [comment]
@IvanSavenko please, run UnitTests and send failures here.

**Comment by IvanSavenko** [comment]
I can try running tests, but have zero interest in fixing any failures to be honest... Right now this is just too much maintenance pain for too little gain

**Comment by rilian-la-te** [comment]
@IvanSavenko I suggest running and fixing relevant tests to everyone who change core functionality, because even if you do not like tests in this state (requires H3 data, cannot ran in CI), tests are helpful to check some aspects of core functionality like spells. 

I think not adding tests is OK, but breaking already working ones is bad. I think we should not break tests regularly, and then make PR with "fixinig tests again".

**Comment by wb180** [comment]
Tried just to play single player map: on quick battle replay: in debug - assert, in release just freeze:
Screenshot_20230901_205456
Screenshot_20230901_205710

**Comment by IvanSavenko** [comment]
Looks like battle replay. Haven't tested that yet.

**Pull request merged**
