### PR TITLE
Easy choosing for a secondary skill (and others)

### PR DESCRIPTION
**Pull request by Laserlicht**
Easy choosing for a secondary skill in Level Up Dialog by double clicking it.

Suggestion from @IvanSavenko

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Can we apply same logic to other selection windows? E.g. treasure chests?

**Comment by Laserlicht** [comment]
> Can we apply same logic to other selection windows? E.g. treasure chests?

done :)

**Review by IvanSavenko — APPROVED** [review]
Thanks :)

**Comment by Nordsoft91** [comment]
Very good!

Idea to go broader: what about enabling single touch for touchscreens only?

**Comment by Laserlicht** [comment]
> Very good!

Thanks

> Idea to go broader: what about enabling single touch for touchscreens only?

You could do the same for the desktop and eliminate the okay button.

But I find it nicer this way. Is more like the original.

**Pull request merged**
