### PR TITLE
Extend creature siege support. Fix bug #2600

### PR DESCRIPTION
**Pull request by dydzio0614**
Make ballistics skill apply only to catapult, add new skill to handle multi attack on siege walls for creatures, fix cyclop kings

### CODE REVIEW

**Comment by DjWarmonger** [comment]
It would be simpler just to add "val" parameter to CATAPULT which contains the number of extra shots.

**Comment by dydzio0614** [comment]
I thought about that, though cyclop kings take their "catapult" bonus from crtraits.txt so I thought this may be problematic to give them bonus value. AVS also said on slack: "separate bonus design is consistent with shooting ans spellcasting", so I decided to go that way.

**Comment by DjWarmonger** [comment]
Maybe at least give it clear name, such as "CATAPULT_SHOTS" or something.

**Comment by Alucard648** [comment]
What about "EXPERT_CATAPULT" bonus to work like Expert Ballistics hero secondary skill?

**Comment by DjWarmonger** [comment]
It shoudl be more general. We might want to add more catapult shots in the future. Also more shots for Ballista - for instance Ring of Machine Affinity from ToE does that.

**Pull request merged**
