### PR TITLE
Fix potential nullptr-to-reference conversion

### PR DESCRIPTION
**Pull request by IvanSavenko**
(will cherry-pick to master after merge)

### CODE REVIEW

**Comment by Nordsoft91** [comment]
@IvanSavenko , to master to beta?

**Comment by IvanSavenko** [comment]
Not sure. Probably master?

There is no 'beta' branch right now and not sure if we're going to release 1.2.2.

Sure, can create beta branch just for this commit, but since this change is critical for some platforms and completely unused by others commit to master without release/tag might be best approach.

**Comment by IvanSavenko** [comment]
@Alexander-Wilms Any preference on where to put this fix? What would be the preferred approach as far as flatpak packaging goes?

**Comment by Alexander-Wilms** [comment]
@IvanSavenko It doesn't really matter, I can just add the patch file to the package.

**Comment by IvanSavenko** [comment]
Understood.
In that case I am keeping this fix in develop branch only, flatpak/archlinux/etc can cherry-pick/copy patch if needed.

**Comment by lemenkov** [comment]
Hello!
I've got the same issue as mentioned in #1971 but on Linux. I can confirm this PR does fixes #1971.

**Pull request merged**
