### PR TITLE
display attack type(melee/ranged) in popup window

### PR DESCRIPTION
**Pull request by kdmcser**
melee/ranged infomation is important for players to determined whether attack or not, so I think it should be displayed in master level message.

if no hero selected, the master level message should be displayed too.

屏幕截图 2024-10-02 190504

屏幕截图 2024-10-02 190543

### CODE REVIEW

**Comment by Laserlicht** [comment]
Please edit also german:
`	"vcmi.adventureMap.monsterLevel"            : "\n\nStufe %LEVEL %TOWN-Einheit",`
to
```
	"vcmi.adventureMap.monsterLevel"            : "\n\nStufe %LEVEL %TOWN-Einheit (%ATTACK_TYPE)",
	"vcmi.adventureMap.monsterMeleeType"        : "Nahkampf",
	"vcmi.adventureMap.monsterRangedType"       : "Fernkampf",
```

**Comment by kdmcser** [comment]
> is faerie dragon considered melee? 😄

It is difficult to determine whether  faerie dragon is melee or ranged now, maybe we can add a melee spellcaster in the future?

**Comment by Olegmods** [comment]
Perhaps it will be a good idea to add info if unit is a spellcaster.

**Comment by IvanSavenko** [comment]
A lot of units are spellcasters, but it is often irrelevant for such tooltip - upgraded elementals for example.

**Comment by kdmcser** [comment]
> A lot of units are spellcasters, but it is often irrelevant for such tooltip - upgraded elementals for example.

Maybe a wiki is requested in game for user to look up? add a book icon in the game, when pressed, it open a book, user can search creature, faction, heroes, artifacts and other things he want to look up in this book.

**Comment by Olegmods** [comment]
> Maybe a wiki is requested in game for user to look up? add a book icon in the game, when pressed, it open a book, user can search creature, faction, heroes, artifacts and other things he want to look up in this book.

I think it will not be easy to implement. Perhaps a good idea will be to somehow allow looking on creature info widget (that one with stats, abilities, etc) from map.

**Comment by misiokles** [comment]
Or Alt-Tab and quick lurking here :)
https://vcmi.eu/Mod%20Repository/Overview/

**Comment by IvanSavenko** [comment]
> Or Alt-Tab and quick lurking here :) https://vcmi.eu/Mod%20Repository/Overview/

Not a bad idea actually. Especially if we can provide in-game link to that page

However right now that page does not even have information on whether unit is a shooter. Same for spellcasting abilities.

**Comment by Olegmods** [comment]
> > Or Alt-Tab and quick lurking here :) https://vcmi.eu/Mod%20Repository/Overview/
> 
> Not a bad idea actually. Especially if we can provide in-game link to that page
> 
> However right now that page does not even have information on whether unit is a shooter. Same for spellcasting abilities.

But what if the mod is not on repository? Or is in repo, but is not in this page?

**Comment by misiokles** [comment]
Mods from official repo are added here auto matically with small lag.

**Comment by kdmcser** [comment]
and only English is supported in this page, user may require other language.

**Comment by IvanSavenko** [comment]
> and only English is supported in this page, user may require other language.

I'd say that this is missing feature for a website, whether we have link from in game or not.
But not sure if @Laserlicht has interest in it or whether it is supported by framework we use.

**Comment by Olegmods** [comment]
> > and only English is supported in this page, user may require other language.
> 
> I'd say that this is missing feature for a website, whether we have link from in game or not. But not sure if @Laserlicht has interest in it or whether it is supported by framework we use.

I think the site link isn't a good solution. There are some archive mods that aren't on the site though. Plus, for example, I want to show some mods that I made, but didn't publish to someone and I don't want to tell about every creature that I added or changed (because there are many, for example).

**Offtop**: is that normal that I still don't see the mod "HotA Factory creatures" in the list from the site? Several days passed since its release into the main repository.

**Comment by IvanSavenko** [comment]
Sure, player can install mod manually not from repo. But this is like 1% of our players. Meanwhile, link would be an improvement for 99%.
Sure, we can make in-game wiki, like some games have. But who is going to work on that? Which planned feature we should postpone / discard in place of in-game wiki? We don't have enough active developers to implement every suggestion, whether it is good or not.

**Comment by Olegmods** [comment]
> Sure, player can install mod manually not from repo. But this is like 1% of our players. Meanwhile, link would be an improvement for 99%. Sure, we can make in-game wiki, like some games have. But who is going to work on that? Which planned feature we should postpone / discard in place of in-game wiki? We don't have enough active developers to implement every suggestion, whether it is good or not.

I suggest to somehow allow to look at the staticstics window from the map. The wiki would be good too, but it's harder.

**Comment by Olegmods** [comment]
Screenshot_20241006_162229

That one window, like with Griffins on the screen.

**Comment by misiokles** [comment]
I think, there's no need to complicate things/windows. Such informations are needed only for first hours of playing. Then player will learn everything about new creatures and such overinformated windows will be only annoying.

**Comment by Olegmods** [comment]
> I think, there's no need to complicate things/windows. Such informations are needed only for first hours of playing. Then player will learn everything about new creatures and such overinformated windows will be only annoying.

I think that could be just an option. Like right-click with some key pressed on keyboard and the window pops. So when the player learnt about the new creatures, he won't use the combination. IDK how to add that to the phones though.

**Pull request merged**
