### PR TITLE
allow healing ability only before first turn of each round

### LINKED ISSUE #1008: healing in battle occurs twice
Steps to reproduce:
1. "Wait" with a creature 
2. The creature receives damage
3. Healing is triggered when wait is over - this one is wrong
4. Healing is triggered again in the beginning of new turn

Test map: [elixir.vmap.zip](https://github.com/vcmi/vcmi/files/9654763/elixir.vmap.zip). Grab Elixir of Life and attack. Note: must be tested with the change from #1009 or after it's merged.

### PR DESCRIPTION
**Pull request by kambala-decapitator**
prohibited cases:
- turn after wait
- turn due to high morale

allowed:
- very first round
- bad morale
- blind and similar effects

fixes #1008

### CODE REVIEW

**Comment by nullkiller** [comment]
Interesting question if healing should be done in case of bad morale or berserk?

**Comment by kambala-decapitator** [comment]
FizMig has only this about regen of Wraiths/Trolls:

> Регенерация – при получении очередного хода существо полностью восстанавливает своё здоровье (без воскрешения погибших). Если существо окаменено или парализовано, то Регенерация всё равно срабатывает в момент, когда к отряду должен был перейти ход.

**Comment by kambala-decapitator** [comment]
I'd say that:
- bad morale: heal, as creature's turn starts
- berserk: that's when creature attacks allies? Well, that's basically a normal turn

**Comment by kambala-decapitator** [comment]
thought about bad morale a bit and actually I think healing shouldn't work in this case

**Review by Nordsoft91 — APPROVED** [review]
looks safe

**Comment by nullkiller** [comment]
Checked original game - elixir of life acts on green dragons and in case of bad morale as well

**Comment by kambala-decapitator** [comment]
Thanks, something to adjust then. Do you have test map by chance?

**Comment by nullkiller** [comment]
[healing.zip](https://github.com/vcmi/vcmi/files/9691085/healing.zip)
visit tomp 2 times + mix alignments to get bad morale

**Comment by kambala-decapitator** [comment]
also healing is possible in the first round - if creature is damaged before its turn

**Comment by kambala-decapitator** [comment]
improved test map:
[regen-test.h3m.zip](https://github.com/vcmi/vcmi/files/9696330/regen-test.h3m.zip)

red hero has low morale due to undead and different factions, there's also Crypt and WT on the map to low morale even more. Blue hero has Berserk and Sorrow, also Ghost Dragon to low enemy's morale. AI doesn't seem to use those spells, but Hot Seat can be used.

**Comment by kambala-decapitator** [comment]
healing must also work when creature is blinded or under similar effect

**Comment by kambala-decapitator** [comment]
all cases should be covered now

**Pull request merged**
