### PR TITLE
Teleport: check immunities in applicable()

### LINKED ISSUE #2677: Teleport issue
**Describe the bug**
Game crashes when using teleport

**Game logs**
Server:
```
[2023-Aug-26 16:19:02.170294] TRACE network - 	Applied on gs: 9EndAction
[2023-Aug-26 16:19:02.170490] TRACE global - Activating red battle stack [3]: 2 of creatures.core.phoenix.name.plural from slot 2 of armyobj=605
[2023-Aug-26 16:19:02.170532] TRACE network - 	Sending to all clients: 20BattleSetActiveStack
[2023-Aug-26 16:19:02.170569] TRACE network - Sending a pack of type 20BattleSetActiveStack
[2023-Aug-26 16:19:02.170673] TRACE network - 	Applied on gs: 20BattleSetActiveStack
[2023-Aug-26 16:19:02.170709] TRACE global - Message 10MakeAction successfully applied!
[2023-Aug-26 16:19:02.170735] TRACE network - Sending a pack of type 14PackageApplied
[2023-Aug-26 16:19:15.143037] TRACE network - Received CPack of type 10MakeAction
[2023-Aug-26 16:19:15.143153] TRACE global - Making action: {BattleAction: side '0', stackNumber '4294967295', actionType '4', actionSubtype '63', target {2@{BattleHex: x '1', y '2', hex '35'},{BattleHex: x '15', y '6', hex '117'},}}
[2023-Aug-26 16:19:15.143174] TRACE network - 	Sending to all clients: 11StartAction
[2023-Aug-26 16:19:15.143187] TRACE network - Sending a pack of type 11StartAction
[2023-Aug-26 16:19:15.143446] TRACE network - 	Applied on gs: 11StartAction
[2023-Aug-26 16:19:15.143921] TRACE network - 	Sending to all clients: 16BattleLogMessage
[2023-Aug-26 16:19:15.143980] TRACE network - Sending a pack of type 16BattleLogMessage
[2023-Aug-26 16:19:15.144178] TRACE network - 	Applied on gs: 16BattleLogMessage
[2023-Aug-26 16:19:15.144231] TRACE network - 	Sending to all clients: 15BattleSpellCast
[2023-Aug-26 16:19:15.144256] TRACE network - Sending a pack of type 15BattleSpellCast
[2023-Aug-26 16:19:15.144336] TRACE network - 	Applied on gs: 15BattleSpellCast
[2023-Aug-26 16:19:15.144589] ERROR global - Disaster happened.
[2023-Aug-26 16:19:15.145296] ERROR global - Reason: 0xc0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:0x7ff,8c3,873,711
[2023-Aug-26 16:19:15.145617] ERROR global - Attempt to read from 0x       0
[2023-Aug-26 16:19:15.146035] ERROR global - Thread ID: 9952
[2023-Aug-26 16:19:15.146908] ERROR global - Crash info will be put in VCMI_server.exe_crashinfo.dmp
```

**To Reproduce**
Teleport unit in town siege.

**Did it work earlier?**
idk

**Version**
 - OS: Windows 11
 - Version: latest nightly

**Screenshots**
[Peek 2023-08-26 16-19.webm](https://github.com/vcmi/vcmi/assets/13953785/45256247-75ac-4d28-81ac-8318d339fb5a)

### PR DESCRIPTION
**Pull request by rilian-la-te**
Attempt to fix #2677

Please, somebody, test, who have time.

### CODE REVIEW

**Comment by krs0** [comment]
Does not work. Trying to TP magicElemental it lets me select them, it lets me select destination and then it lets me do nothing more, but game does not crash.

**Comment by rilian-la-te** [comment]
@krs game just freezes or just mana removes and teleport does not work?

**Comment by rilian-la-te** [comment]
изображение
Althrough, minor issue remains - double-hex units second hex cannot be selected for teleport.

**Comment by Laserlicht** [comment]
> @krs0 build latest beta version with this branch, and see no crash, Magic Elementals cannot even be selected (which is correct). Can you recheck it with new fix?

Yes, can confirm. Looks good. Thanks. :)

**Comment by rilian-la-te** [comment]
@Laserlicht will try to fix minor issue too.

**Comment by krs0** [comment]
Looks good for magic Elemntals and Black Dragons.
Can confirm TP does not work on second hex for 2 hexed creatures.

**Comment by rilian-la-te** [comment]
@krs0 teleport does not work only on edge, because it try to check second target as destination hex.

**Comment by rilian-la-te** [comment]
@krs0 seems fixed. Please, try.

**Comment by krs0** [comment]
Cloning using the "tail" of creatures seems to be fixed

**Comment by rilian-la-te** [comment]
Yes, by client commit)

**Pull request merged**
