### PR TITLE
Fix crash at battle end

### PR DESCRIPTION
**Pull request by DjWarmonger**
Both reproductible and random crashes happened here.

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Were crashes reproducible on latest beta?

Can you add error to log in there?
Such situation should not happen in the first place, no need to silently return

**Comment by IvanSavenko** [comment]
I did saw similar crashes but they should be already properly fixed in beta by this commit:
https://github.com/vcmi/vcmi/pull/2505/commits/d7cbe4ecde8ae8fb56350886fb00db70ff8c17b2

**Comment by DjWarmonger** [comment]
I get this in current beta:
image
image

But no crash.

**Comment by DjWarmonger** [comment]
[crash_2546.zip](https://github.com/vcmi/vcmi/files/12311548/crash_2546.zip)
And yes, looks like AI hero already moves on adventure map before making that request.

**Comment by IvanSavenko** [comment]
Yeah, seems to be happening when AI ends battle with a spell.
However request is correctly denied by server so shouldn't cause a crash.

**Comment by IvanSavenko** [comment]
To clarify - I think that this change is not needed because this is applying netpack to *gamestate*. This netpack has been generated by server, applied by server locally and sent to client.

Such packs must always succeed. If they fail for one reason or another then this is issue somewhere on server and should be fixed on server.

**Comment by DjWarmonger** [comment]
If that's the case, assertion is needed. It should never fail, yet it did.

**Comment by IvanSavenko** [comment]
Yeah, assertion or even throw runtime_error with appropriate message.

**Comment by DjWarmonger** [comment]
Done.

**Review by IvanSavenko — APPROVED** [review]

**Pull request merged**
