### PR TITLE
Only remove extension if it belongs to specified file type

### PR DESCRIPTION
**Pull request by ArseniyShestakov**
This one fixes issue 1557:
http://bugs.vcmi.eu/view.php?id=1557

It's tiny change and I tested it, but I feel there may be consequences so more eyes on it will be useful. E.g if there is some resource loading code that set incorrect EResType or any other code that expect to get filename without extension.

### CODE REVIEW

**Comment by alexvins** [comment]
There should be check that "name" is being set after "type" and it should be documented.

**Comment by ArseniyShestakov** [comment]
There is small issue with such check as "type" currently set to EResType::OTHER by default when object created. In same time it's may be set to OTHER after getTypeFromExtension check.

So I suppose valid way would be to add UNDEFINED to enum and then init "type" as EResType::UNDEFINED by default so there will be way to check if "type" has changed after object creation or not. Would that work?

**Comment by alexvins** [comment]
Should work.

**Comment by ArseniyShestakov** [comment]
Tested this one internally with all recent commits so now will merge it.

**Pull request merged**
