### PR TITLE
Fix android UI shift when keyboard appears

### PR DESCRIPTION
**Pull request by nullkiller**
Now input will be always visible

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
now iOS is broken, seems the ifdef is no longer needed (but still keep the VCMI_APPLE ifdef)

**Comment by kambala-decapitator** [comment]
I think desktop with zoom setting should also be tested

**Comment by kambala-decapitator** [comment]
disabling iOS ifdef doesn't fix it unfortunately. For now please make sure that iOS code runs unmodified.

**Comment by nullkiller** [comment]
@kambala-decapitator I changed code in a way that it should be logically same for iOS but have no iOS device. Could you check it?

**Review by kambala-decapitator — APPROVED** [review]
on iOS works good now

**Pull request merged**
