### PR TITLE
TTF fonts fallback

### PR DESCRIPTION
**Pull request by IvanSavenko**
Implements support for fixing #1745 

Actual fix (true type fonts) will probably go to vcmi-extras for now - while license-wise fonts can go to vcmi mod, but not sure whether we want this behavior by default.
Plus my concern is that if we remove them later some players will still keep them - since our installer right now is not removing old files properly at the moment

### CODE REVIEW

**Comment by rilian-la-te** [comment]
@IvanSavenko but we already use version 821)

**Comment by IvanSavenko** [comment]
> @IvanSavenko but we already use version 821)

Yet another example at to why our serialization versioning is a mess...

**Comment by rilian-la-te** [comment]
@IvanSavenko agree, but do you have other ideas how to handle different serialization?

**Comment by IvanSavenko** [comment]
> @IvanSavenko agree, but do you have other ideas how to handle different serialization?

1) Instead of incrementing version use some unique ID. For example, ID of pull request this branch belongs to or issue ID that this branch fixes. This is unique number that will not conflict between different branches.
2) Instead of having min version and current version ID's use single version ID which will be changed whenever there is a breaking change (using unique ID from p.1)
3) For non-breaking changes, introduce "feature list" - list of ID's that will be located in save header after version ID. Serializer should have method hasFeature(int ID) that returns true if save contains selected "feature". Feature ID's should also use same format from p.1.
4) Whenever there is a breaking change, all existing features should be removed and used unconditionally - to prevent pileup of unused features

**Comment by rilian-la-te** [comment]
@IvanSavenko this is also human errors possible. But firstly we need to select what we actually should serialize, and what should not.

**Comment by IvanSavenko** [comment]
> @IvanSavenko this is also human errors possible. But firstly we need to select what we actually should serialize, and what should not.

Maybe, but this is very long-term issue and for now we should serialize everything that can be serialized, with exception of hardcoded values that don't change with mods.

Meanwhile better serialization that is more fool-proof can be done at any point, including in 1.3

> there is also topic about whether we should serialize AI state... AI serialization was dropped in VCAI due to some problems with serialization/deserialization

Local player state (e.g. sleeping heroes, heroes path) also suffer from this problem. IMO player state can be stored on server, in server savegame, and as for AI - it can either use similar approach, e.g. send it to server or perhaps even move AI to server (not something that likely to happen soon though)

> there also comes topic of serializing battle state if we want to support combat save/load as in H4

Should be done only if we actually implement this feature. Not much point in writing code that won't be used for years.

**Comment by rilian-la-te** [comment]
@IvanSavenko server should not know anything about player state, and if player is AI or not. But can you remember me why client serialization is broken?

**Comment by rilian-la-te** [comment]
@IvanSavenko I agree with this approach only partially. I think server save game should be allowed to load on any client, and language/graphic mods/sounds should be irrelevant. But if we will store client state on the server - language and mods will be predefined by server, and not by local game settings.

About AI - server should know single boolean, but not AI state, because I think than we should be able to change between AI implementations even mid-party.

**Pull request merged**
