### PR TITLE
Fix 2377 "Seer Empty Text"

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Try to fix http://bugs.vcmi.eu/view.php?id=2377

### CODE REVIEW

**Comment by DjWarmonger** [comment]
It breaks the savegame as far as I see.

**Comment by vmarkovtsev** [comment]
Yes, It should - because before the fix the message was actually absent at all. We can generate it randomly each time a hero makes a visit, but looks like original H3 memorize the text, right?

**Comment by alexvins** [comment]
"completedOption" Serialization is missing

**Comment by vmarkovtsev** [comment]
Missed that. Added.

**Comment by vmarkovtsev** [comment]
Added new version format. I set it to 757, so it should be merged after https://github.com/vcmi/vcmi/pull/175.

**Comment by ArseniyShestakov** [comment]
Sorry, I must tested it with new game. There is crash in CGSeerHut::initObj :disappointed_relieved:

**Comment by vmarkovtsev** [comment]
Oops sorry, I will fix it asap.

**Comment by ArseniyShestakov** [comment]
No worries, in case you don't have time right let me know and I'll fix it.
I sent you map and also uploaded it on bug tracker.

**Comment by vmarkovtsev** [comment]
I am unable to reproduce the crash on the attached map. I visited every Seer Hut and still no crash. What's the stack trace?

**Comment by ArseniyShestakov** [comment]
Can you try with V4 or at least several times?

Problem basically occur because CGQuestGuard overload ::init() function and completedOption may contain random data.

**Comment by ArseniyShestakov** [comment]
Anyway don't worry about that, I'll commit fix now.

**Comment by ArseniyShestakov** [comment]
https://github.com/vcmi/vcmi/commit/b7fbbfdebe10fea907e3779154415c8e585bd864

**Pull request merged**
