### PR TITLE
fix gold check for School of War

### LINKED ISSUE #1333: School of War allows getting skill for less than 1000 gold
**Describe the bug**
If you have less than 1000 gold (even 0), you can still get skill from School of War. All available money is spent in such case.

**Game logs**
Relevant bits from server log:

```
DEBUG global [0x7000047df000] - Hero Sorsha visits School of War (107:0)
TRACE global [0x7000047df000] - Created a new query with id 5
TRACE network [0x7000047df000] - 	Sending to all clients: 9HeroVisit
TRACE network [0x7000047df000] - Sending a pack of type 9HeroVisit
TRACE network [0x7000047df000] - 	Applied on gs: 9HeroVisit
TRACE global [0x7000047df000] - Reward 0 is allowed
TRACE global [0x7000047df000] - Reward 1 is allowed
DEBUG global [0x7000047df000] - Visiting object with 2 possible rewards
TRACE global [0x7000047df000] - Created a new query with id 6
TRACE network [0x7000047df000] - 	Sending to all clients: 14BlockingDialog
TRACE network [0x7000047df000] - Sending a pack of type 14BlockingDialog
TRACE global [0x7000047df000] - Reward 0 is allowed
TRACE global [0x7000047df000] - Reward 1 is allowed
TRACE global [0x7000047df000] - Hero Sorsha ends movement
TRACE global [0x7000047df000] - Leaving auto CGameHandler::moveHero(ObjectInstanceID, int3, ui8, bool, PlayerColor)::(anonymous class)::operator()(TryMoveHero::EResult, CGameHandler::EGuardLook, CGameHandler::EVisitDest, CGameHandler::ELEaveTile) const.
TRACE global [0x7000047df000] - Message 8MoveHero successfully applied!
TRACE network [0x7000047df000] - Sending a pack of type 14PackageApplied
TRACE network [0x7000047df000] - Received CPack of type 10QueryReply
TRACE global [0x7000047df000] - Player 0 attempts answering query 6 with answer:
TRACE global [0x7000047df000] - 1
TRACE global [0x7000047df000] - Reward 0 is allowed
TRACE global [0x7000047df000] - Reward 1 is allowed
TRACE network [0x7000047df000] - 	Sending to all clients: 20ChangeObjectVisitors
TRACE network [0x7000047df000] - Sending a pack of type 20ChangeObjectVisitors
TRACE network [0x7000047df000] - 	Applied on gs: 20ChangeObjectVisitors
TRACE network [0x7000047df000] - 	Sending to all clients: 17SetObjectProperty
TRACE network [0x7000047df000] - Sending a pack of type 17SetObjectProperty
TRACE network [0x7000047df000] - 	Applied on gs: 17SetObjectProperty
TRACE network [0x7000047df000] - 	Sending to all clients: 12SetResources
TRACE network [0x7000047df000] - Sending a pack of type 12SetResources
TRACE network [0x7000047df000] - 	Applied on gs: 12SetResources
TRACE network [0x7000047df000] - 	Sending to all clients: 12SetPrimSkill
TRACE network [0x7000047df000] - Sending a pack of type 12SetPrimSkill
TRACE network [0x7000047df000] - 	Applied on gs: 12SetPrimSkill
DEBUG global [0x7000047df000] - Hero Sorsha visit ends.

TRACE network [0x7000047df000] - 	Sending to all clients: 9HeroVisit
TRACE network [0x7000047df000] - Sending a pack of type 9HeroVisit
TRACE network [0x7000047df000] - 	Applied on gs: 9HeroVisit
TRACE network [0x7000047df000] - 	Sending to all clients: 13PlayerBlocked
TRACE network [0x7000047df000] - Sending a pack of type 13PlayerBlocked
TRACE network [0x7000047df000] - 	Applied on gs: 13PlayerBlocked
TRACE global [0x7000047df000] - Destructed the query with id 4
TRACE global [0x7000047df000] - Destructed the query with id 5
TRACE global [0x7000047df000] - Destructed the query with id 6
TRACE global [0x7000047df000] - Message 10QueryReply successfully applied!
TRACE network [0x7000047df000] - Sending a pack of type 14PackageApplied
```

**To Reproduce**
1. Start attached map in King (Impossible) difficulty to have 0 gold on start: [school-of-war-500g.h3m.zip](https://github.com/vcmi/vcmi/files/10313590/school-of-war-500g.h3m.zip)
2. (optional) grab gold pile to have 0 < funds < 1000
3. Visit School of War
4. You're presented with choices, skill is granted on accept

**Expected behavior**
Message saying that you don't have enough money appears

**Actual behavior**
You get skill cheaper or even for free

**Did it work earlier?**
Doesn't seem so - at least same behavior in 1.1 and develop

**Screenshots**
SS from oh3 showing the correct message:
Screenshot 2022-12-28 at 13 06 13

**Version**
 - OS: macOS Intel
 - Version: 1.1, develop

### PR DESCRIPTION
**Pull request by kambala-decapitator**
fixes #1333

### CODE REVIEW

**Comment by Alucard648** [comment]
Check the same thing for other gold demanding objects, like School of Magic and University.

**Comment by kambala-decapitator** [comment]
School of Magic already checked - works correctly

**Comment by Alucard648** [comment]
Thanks.

**Comment by dydzio0614** [comment]
Arena broken

**Comment by kambala-decapitator** [comment]
> Arena broken

could you add more info? Arena doesn't require gold.

**Review by Nordsoft91 — APPROVED** [review]

**Pull request merged**
