### PR TITLE
NKAI: more fixes to defense and pandora

### PR DESCRIPTION
**Pull request by nullkiller**
Continue investigating some weird behavior. Some bug fixes and priority advancements mostly around defense

### CODE REVIEW

**Comment by DjWarmonger** [comment]
Will look into it.

BTW, I just had a look at that Clash of Dragons map I posted and current AI was doing great :)

**Comment by DjWarmonger** [comment]
Looked very good until Blue got "Unable to complete hero chain" on the main hero (the one on the right) and started to stall for weeks:
image
Eventually its other heroes picked up the lead from here, but it took a long time.

Not sure if that's related to this PR, but NKAI didn't have such issue as far as I remember.

**Comment by DjWarmonger** [comment]
Okay, for the first time in this map I see one player actually beat another. It doesn't get better than that, I suppose.

What's with the draft? Are you going to add some changes still?

**Review by DjWarmonger — APPROVED** [review]

**Comment by DjWarmonger** [comment]
Yep, I'd say heroes get stuck at Pandora with "unable to comeplete chain" bug for some reason:
image

**Comment by DjWarmonger** [comment]
One concern that might be related: In order to visit target tile under blockvis object, it takes **two** steps - one to pick up Pandora and the other to actually move to the tile. Does pathfinding take that into account?

Similiar story with adventure map guards - they can be fought without ever standing on their position.

**Comment by dydzio0614** [comment]
@DjWarmonger  I remember long ago VCAI had similar problem with visiting corpse :P

**Comment by nullkiller** [comment]
> One concern that might be related: In order to visit target tile under blockvis object, it takes **two** steps - one to pick up Pandora and the other to actually move to the tile. Does pathfinding take that into account?
> 
> Similar story with adventure map guards - they can be fought without ever standing on their position.

At least there was some logic to double-charge movement points for bypassing blockvis obj. So sometimes the algorithm just can not predict how exactly things will go. But it is mostly about hero exchange, not interaction with objects.

**Comment by nullkiller** [comment]
> Yep, I'd say heroes get stuck at Pandora with "unable to complete chain" bug , even though there are no other heroes nearby.

You mean it freezes? AI skips turns?

**Comment by nullkiller** [comment]
Need saves. Maybe there is some bug.

**Comment by DjWarmonger** [comment]
> > Yep, I'd say heroes get stuck at Pandora with "unable to complete chain" bug , even though there are no other heroes nearby.
> 
> You mean it freezes? AI skips turns?

Partially. I get this bug message about 10 times or so and eventually AI doesn't move this hero and some other heroes as well, then ends turn with many movement points remaining. I don't think all of the stuck heroes were neccessarily involved in this chain.

**Comment by nullkiller** [comment]
> > > Yep, I'd say heroes get stuck at Pandora with "unable to complete chain" bug , even though there are no other heroes nearby.
> > 
> > 
> > You mean it freezes? AI skips turns?
> 
> Partially. I get this bug message about 10 times or so and eventually AI doesn't move this hero and some other heroes as well, then ends turn with many movement points remaining. I don't think all of the stuck heroes were neccessarily involved in this chain.

Not exactly. It is a freeze, endless attempt to do something, and after 30 like attempts release build terminates current day, so all heroes who did not got a chance to move left with some MP. With AI_TRACE_LEVEL > 0 it will just hang forever.

**Comment by nullkiller** [comment]
Most likely protection from guarded object. When AI picks pandora it asks if it want to open it, and it may answer no). Will test some cases but save or at least logs would be helpful

**Comment by dydzio0614** [comment]
so @DjWarmonger if you dont have saves - what map did you use to reproduce this?

**Comment by DjWarmonger** [comment]
This one, I use it often since 2012.
[144 CoD 20121002.zip](https://github.com/vcmi/vcmi/files/11068745/144.CoD.20121002.zip)

**Comment by nullkiller** [comment]
Ok will try to run it on autoskip and see what is going on

**Comment by nullkiller** [comment]
On autoskip I was attacked on the beginning of 5th month

**Comment by DjWarmonger** [comment]
Lucky you.

**Comment by dydzio0614** [comment]
did you manage to do something with pandora?

**Comment by nullkiller** [comment]
No, I failed to reproduce stable freeze. Need further investigation. Hero chain bug was not a serious issue back in the past. Not sure it got any serious now. So

**Comment by nullkiller** [comment]
Some freezes have been reported, will investigate further

**Pull request merged**
