### PR TITLE
Release 1.4

### PR DESCRIPTION
**Pull request by IvanSavenko**
Final changes for 1.4
To be merged tomorrow / this night.

### CODE REVIEW

**Comment by dydzio0614** [comment]
my polish translation is not ready yet (ingame texts done so far)

**Comment by IvanSavenko** [comment]
@dydzio0614 Planning to finish it today or tomorrow? If yes - then I'll wait for it and include in 1.4.0

Also, @dydzio0614 and @Laserlicht 
There are a few more strings to translate in #3217 (sorry, wanted to finish it earlier)

Feel free to translate them and either open PR or just add translated versions in comments

```js
	"vcmi.optionsTab.chessFieldTurnAccumulate.help" : "Used out of combat or when {Battle Timer} runs out. Reset each turn. Leftover added to {Base Timer} at turn's end.",
	"vcmi.optionsTab.chessFieldTurnDiscard.help" : "Used out of combat or when {Battle Timer} runs out. Reset each turn. Any unspent time is lost",
	"vcmi.optionsTab.chessFieldUnitAccumulate.help" : "Used when selecting unit action in pvp combat. Leftover added to {Battle Timer} at end of unit turn.",
	"vcmi.optionsTab.chessFieldUnitDiscard.help" : "Used when selecting unit action in pvp combat. Reset at start of each unit's turn. Any unspent time is lost",

	"vcmi.optionsTab.turnTime.select"     : "Select turn timer preset",
	"vcmi.optionsTab.turnTime.unlimited"  : "Unlimited turn time",
	"vcmi.optionsTab.turnTime.classic.1"  : "Classic timer: 1 minute",
	"vcmi.optionsTab.turnTime.classic.2"  : "Classic timer: 2 minutes",
	"vcmi.optionsTab.turnTime.classic.5"  : "Classic timer: 5 minutes",
	"vcmi.optionsTab.turnTime.classic.10" : "Classic timer: 10 minutes",
	"vcmi.optionsTab.turnTime.classic.20" : "Classic timer: 20 minutes",
	"vcmi.optionsTab.turnTime.classic.30" : "Classic timer: 30 minutes",
	"vcmi.optionsTab.turnTime.chess.20"   : "Chess: 20:00 + 10:00 + 02:00 + 00:00",
	"vcmi.optionsTab.turnTime.chess.16"   : "Chess: 16:00 + 08:00 + 01:30 + 00:00",
	"vcmi.optionsTab.turnTime.chess.8"    : "Chess: 08:00 + 04:00 + 01:00 + 00:00",
	"vcmi.optionsTab.turnTime.chess.4"    : "Chess: 04:00 + 02:00 + 00:30 + 00:00",
	"vcmi.optionsTab.turnTime.chess.2"    : "Chess: 02:00 + 01:00 + 00:15 + 00:00",
	"vcmi.optionsTab.turnTime.chess.1"    : "Chess: 01:00 + 01:00 + 00:00 + 00:00",

	"vcmi.optionsTab.simturns.select"         : "Select simultaneous turns preset",
	"vcmi.optionsTab.simturns.none"           : "No simultaneous turns",
	"vcmi.optionsTab.simturns.tillContactMax" : "Simturns: Until contact",
	"vcmi.optionsTab.simturns.tillContact1"   : "Simturns: 1 week, break on contact",
	"vcmi.optionsTab.simturns.tillContact2"   : "Simturns: 2 weeks, break on contact",
	"vcmi.optionsTab.simturns.tillContact4"   : "Simturns: 1 month, break on contact",
	"vcmi.optionsTab.simturns.blocked1"       : "Simturns: 1 week, contacts blocked",
	"vcmi.optionsTab.simturns.blocked2"       : "Simturns: 2 weeks, contacts blocked",
	"vcmi.optionsTab.simturns.blocked4"       : "Simturns: 1 month, contacts blocked",
```

**Comment by dydzio0614** [comment]
yeah I plan to finish that soon

**Comment by Laserlicht** [comment]
New Strings:

```
	"vcmi.optionsTab.chessFieldTurnAccumulate.help" : "Wird außerhalb des Kampfes verwendet oder wenn der {Kampf-Timer} abgelaufen ist. Wird jede Runde zurückgesetzt. Reste werden am Ende der Runde zum {Basis-Timer} hinzugefügt.",
	"vcmi.optionsTab.chessFieldTurnDiscard.help" : "Wird außerhalb des Kampfes verwendet oder wenn der {Kampf-Timer} abgelaufen ist. Wird jede Runde zurückgesetzt. Jede nicht verbrauchte Zeit ist verloren",
	"vcmi.optionsTab.chessFieldUnitAccumulate.help" : "Wird bei der Auswahl der Einheitenaktion im PvP-Kampf verwendet. Der Rest wird am Ende des Zuges der Einheit zum {Kampf-Timer} hinzugefügt.",
	"vcmi.optionsTab.chessFieldUnitDiscard.help" : "Wird bei der Auswahl der Einheitenaktion im PvP-Kampf verwendet. Wird zu Beginn des Zuges jeder Einheit zurückgesetzt. Jede nicht verbrauchte Zeit ist verloren",

	"vcmi.optionsTab.turnTime.select"     : "Spielzug-Timer-Voreinstellung wählen",
	"vcmi.optionsTab.turnTime.unlimited"  : "Unbegrenzter Spielzug-Timer",
	"vcmi.optionsTab.turnTime.classic.1"  : "Klassischer Timer: 1 Minute",
	"vcmi.optionsTab.turnTime.classic.2"  : "Klassischer Timer: 2 Minuten",
	"vcmi.optionsTab.turnTime.classic.5"  : "Klassischer Timer: 5 Minuten",
	"vcmi.optionsTab.turnTime.classic.10" : "Klassischer Timer: 10 Minuten",
	"vcmi.optionsTab.turnTime.classic.20" : "Klassischer Timer: 20 Minuten",
	"vcmi.optionsTab.turnTime.classic.30" : "Klassischer Timer: 30 Minuten",
	"vcmi.optionsTab.turnTime.chess.20"   : "Schach: 20:00 + 10:00 + 02:00 + 00:00",
	"vcmi.optionsTab.turnTime.chess.16"   : "Schach: 16:00 + 08:00 + 01:30 + 00:00",
	"vcmi.optionsTab.turnTime.chess.8"    : "Schach: 08:00 + 04:00 + 01:00 + 00:00",
	"vcmi.optionsTab.turnTime.chess.4"    : "Schach: 04:00 + 02:00 + 00:30 + 00:00",
	"vcmi.optionsTab.turnTime.chess.2"    : "Schach: 02:00 + 01:00 + 00:15 + 00:00",
	"vcmi.optionsTab.turnTime.chess.1"    : "Schach: 01:00 + 01:00 + 00:00 + 00:00",

	"vcmi.optionsTab.simturns.select"         : "Voreinstellung für simultane Züge auswählen",
	"vcmi.optionsTab.simturns.none"           : "Keine simultane Züge",
	"vcmi.optionsTab.simturns.tillContactMax" : "Simzüge: Bis zum Kontakt",
	"vcmi.optionsTab.simturns.tillContact1"   : "Simzüge: 1 Woche, Stop bei Kontakt",
	"vcmi.optionsTab.simturns.tillContact2"   : "Simzüge: 2 Wochen, Stop bei Kontakt",
	"vcmi.optionsTab.simturns.tillContact4"   : "Simzüge: 1 Monat, Stop bei Kontakt",
	"vcmi.optionsTab.simturns.blocked1"       : "Simzüge: 1 Woche, Kontakte blockiert",
	"vcmi.optionsTab.simturns.blocked2"       : "Simzüge: 2 Wochen, Kontakte blockiert",
	"vcmi.optionsTab.simturns.blocked4"       : "Simzüge: 1 Monat, Kontakte blockiert",
```

Also replace
`"vcmi.optionsTab.turnOptions.help" : "Ändere Optionen zu Spielzug-Timer und simultanen Zügen",` (too long for the line)
with
`"vcmi.optionsTab.turnOptions.help" : "Optionen zu Spielzug-Timer und simultanen Zügen",`

**Comment by Laserlicht** [comment]
Make small adjustments to fit in Box...

**Comment by Laserlicht** [comment]
adjusted strings (because size of fields)

**Pull request merged**
