### PR TITLE
Replace cotire with CMake builtin precompiled headers support

### PR DESCRIPTION
**Pull request by soarqin**
1. This requires CMake version >= 3.16), so CMake option `ENABLE_PCH` is disabled while CMake version < 3.16
2. Unity build is not enabled in cotire use, but now you can simply enable it(but you will get build error at present due to some unity-build unfriendly codes) by passing option `CMAKE_UNITY_BUILD=ON` to command line while on CMake version >= 3.16
3. This also fixes build issue caused by cotire after updating gtest to latest release in #753

### CODE REVIEW

**Comment by nullkiller** [comment]
https://en.cppreference.com/w/cpp/language/static_assert
Message is not allowed in C++ 17 standard

**Comment by nullkiller** [comment]
> https://en.cppreference.com/w/cpp/language/static_assert Something changed in C++ 17 standard regarding it.

Probably we need to include <assert.h> to Global.h in order to let static_assert to work

**Comment by soarqin** [comment]
I think the build issue on macOS is that StdInc.h is not recognized as a C++ but C header, will fix it

**Comment by soarqin** [comment]
okay, seems like macOS builds passed

**Comment by nullkiller** [comment]
Good job. Will merge it now

**Pull request merged**
