### PR TITLE
Xbrz fixes

### LINKED ISSUE #4487: When Upscaling Filter is XBRZ ×2 ×3 ×4, some screens will get problems on Android
1. Some object will have purple edge in world map and battle map.
2. In hero's information screen of Start Scenario, the icon of magic become smaller.

3. When you open the magic book, you will find the position of magic book move out of the screen.
4. All the creatures's shadow become purple.

### LINKED ISSUE #4505: create background error in advantage map
**Describe the bug**
opening a map，so many creatures background is error.

I find a def file of one creature, it seems no problem in def previewer.
 
[CR203.zip](https://github.com/user-attachments/files/16736115/CR203.zip)

**To Reproduce**
this def is from retreat-town mod.

**Did it work earlier?**
not in 1.5.5

**Version**
 - OS: Windows
 - Version: 1.6 develop branch

### PR DESCRIPTION
**Pull request by IvanSavenko**
- Fixes not working transparency of .def files that don't use cyan as first color
- Fixes purple shadows when xbrz mode is used
- Fixes scaling of images to specified size when xbzr mode is used
- Fixes #4487
- Fixes #4505

### CODE REVIEW

**Comment by Laserlicht** [comment]
Errors I still noticed while testing on android (xbrz 3x):
- There are some horizontal offsets with (some) labels:
grafik
- big spellbook still buggy
- colorization of textures is missing
- shadow effects of windows is not correct
- unit amounts in battle are gray

**Comment by IvanSavenko** [comment]
> There are some horizontal offsets with (some) labels:

Strange. Tested xbrz x3 on PC and everything from this screenshot looks fine for me (at least on my branch)

> big spellbook still buggy

Yeah, will take a look after your related PR

> colorization of textures is missing
shadow effects of windows is not correct
unit amounts in battle are gray

Yeah, known issues, will take a look later

**Comment by IvanSavenko** [comment]
For now merging, will make another round later

**Comment by Laserlicht** [comment]
> Strange. Tested xbrz x3 on PC and everything from this screenshot looks fine for me (at least on my branch)

Ah. `True Type Fonts` from VCMI extras was enabled. This was the reason.

**Pull request merged**
