### PR TITLE
Fix order of dialogs on assembling artefacts after battle

### LINKED ISSUE #1301: assemble dialog appears after killing last creature
Steps:
1. enemy hero possesses artifact set piece(s) that you don't have
2. defeat the hero
3. as soon as the last creature dies, assemble dialog appears

Screenshot 2022-12-25 at 22 11 23

- after closing the dialog the battle result dialog appears
- there can be multiple assemble dialogs if you obtain multiple finished sets

### PR DESCRIPTION
**Pull request by IvanSavenko**
Fixes #1301 
Decided to keep existing order of dialogs because
1) This, strangely, matches H3
2) Artifacts must be sent before battle is over and defeated hero "dies".

(branch can be applied to 1.1.1 hotfix)

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
doesn't look fixed, video from the latest save in the linked issue: https://imgur.com/a/njwtCVJ

**Comment by IvanSavenko** [comment]
Fixed case when you have multiple artifacts to assemble

**Comment by kambala-decapitator** [comment]
seems good now, thanks!

but noticed the following while testing both saves from the issue:

https://github.com/vcmi/vcmi/files/10300591/Archive.tar.gz after capturing town I'm asked if I want to assemble AotD, I say yes, but in fact it's not assembled in the backpack. I also see the following logs:

> Ranged attack animation is over
> Unrecognized trigger effect type 5
> Unrecognized trigger effect type 5
> assembleArtifacts: there is no such artifact instance!
> Got false in applying 17AssembleArtifacts... that request must have been fishy!
> Stopping music file MUSIC/COMBAT03 at 60.742001
> Stopping music file Music/Win Battle at 0.704000
> Warning: IntObject re-activated with mismatching used and active
> System message: Server encountered a problem: assembleArtifacts: there is no such artifact instance!
> System message: Server encountered a problem: Got false in applying 17AssembleArtifacts... that request must have been fishy!

https://github.com/vcmi/vcmi/files/10300661/Archive.tar.gz all seems fine, but the following logs appear:

> Ranged attack animation is over
> assembleArtifacts: It's impossible to assemble requested artifact!
> Got false in applying 17AssembleArtifacts... that request must have been fishy!
> Stopping music file MUSIC/COMBAT03 at 34.108002
> Stopping music file Music/Win Battle at 0.079000
> Warning: IntObject re-activated with mismatching used and active
> System message: Server encountered a problem: assembleArtifacts: It's impossible to assemble requested artifact!
> System message: Server encountered a problem: Got false in applying 17AssembleArtifacts... that request must have been fishy!

I think it tries to assemble Sniper's Bow twice (I see 2 dialogs), but I have only 1 Cherrywood Bow (there're 2x Arrows and Bowstring)

**Comment by IvanSavenko** [comment]
Hmm... this one is a bit complex... Probably better to create separate issue/edit existing & merge this PR.

If after battle hero receives multiple propositions to assemble artifacts in the backpack then only one assembly will succeed.
This happens because vcmiclient sends information on what artifact(s) he want to use for assembly. However, first successful assembly shifts positions of artefacts in the backpack, invalidating any requests from client that rely on this order.

**Comment by kambala-decapitator** [comment]
> Probably better to create separate issue/edit existing & merge this PR

fully agree

**Review by kambala-decapitator — APPROVED** [review]

**Pull request merged**
