### PR TITLE
Fused artifacts

### PR DESCRIPTION
**Pull request by SoundSSGood**
Fused artifacts have been added. Like combined ones, they are assembled from parts. Equipped in one slot. Cannot be disassembled.

To create a fused artifact add the following to json:
```
	"components": 
	[
		"artifact1",
		"artifact2",
		"artifact3"
	],
	"fusedComponents" : true,
```

### CODE REVIEW

**Comment by Olegmods** [comment]
So fused artifact doesn't occupy the slots that its components? Or it's just cannot be disassembled?

**Comment by SoundSSGood** [comment]
> So fused artifact doesn't occupy the slots that its components? Or it's just cannot be disassembled?

Both

**Comment by IvanSavenko** [comment]
By the way - is it possible to fuse (or combine, H3 style) two identical artifacts?
In other words, will something like this work?
```json
"endlessBagOfGold":
{
	"components": 
	[
		"endlessPurseOfGold",
		"endlessPurseOfGold"
	]
}
```

(will take a look at PR a bit later)

**Comment by by003** [comment]
Good for modders...I hope Rune Words can be designed in HoMM3.

**Comment by SoundSSGood** [comment]
> By the way - is it possible to fuse (or combine, H3 style) two identical artifacts?

Now is possible

**Comment by Alucard648** [comment]
H2 used fused artifacts, instead of combined ones. Example is Battle Garb of Anduran.

**Comment by by003** [comment]
I have a suggestion:
Due to the irreversible of fusion and some potential clashes from other combined artifacts, 
You could: 
1. Make fused components DO NOT show reminding message while obtain all of them.
2. Create an icon to active it. The icon can be named as 'Fusion Mode'. If fusion mode is actived, click the components, they will prioritize fusion over combination.

**Comment by SoundSSGood** [comment]
> 2\. The button can be named as 'Fusion Mode'

Where do you propose to place this button?
I think this will cause confusion among players. And if you don't know about this button, you might not even know that there are fused artifacts. 
Question for modders: What about a visitable object for crafting fused artifacts?
CC: @IvanSavenko @dydzio0614  @krs0  @misiokles @Olegmods

**Comment by edeksumo** [comment]
> > 2. The button can be named as 'Fusion Mode'
> 
> Where do you propose to place this button? I think this will cause confusion among players. And if you don't know about this button, you might not even know that there are fused artifacts. Question for modders: What about a visitable object for crafting fused artifacts? CC: @IvanSavenko @dydzio0614 @krs0 @misiokles @Olegmods

I think that this is good idea but only, if you still preserve option for fuze in backpack. This will allow us to make powerful artifacts only in special object.

**Comment by Olegmods** [comment]
> 
 > Where do you propose to place this button? I think this will cause confusion among players. And if you don't know about this button, you might not even know that there are fused artifacts. Question for modders: What about a visitable object for crafting fused artifacts? CC: @IvanSavenko @dydzio0614 @krs0 @misiokles @Olegmods

> 
> I think that this is good idea but only, if you still preserve option for fuze in backpack. This will allow us to make powerful artifacts only in special object.

I agree with @edeksumo 's opinion. Some artifacts (Armageddon's Blade, for example) could be fused in the special object. But some (the weaker ones) should be fuseable in the backpack.

**Comment by misiokles** [comment]
Actually WoG has similar object (Artificer - script 26).
https://www.celestialheavens.com/h3maparchives/wog/wogfeatures.html

**Comment by IvanSavenko** [comment]
Not sure what would be typical usages of this features, but:
- don't feel need of different handling compared to combined artifacts. At most - add warning that fusion is irreversible to assembly dialog (that dialog should have new message btw, in place of H3 "you possess all components...")
- new button - against it unless it is really necessary AND we have space for it (and for fusion I think my anwer is "no" to both points)
- custom map object - not sure. I guess we can add support for taking away artifacts in rewardable objects, so modders will be able to implement such object on their own - currently it only allows giving new artifacts. However it won't be connected in any way to this fusion logic - just seer hut-like object that asks for a set of artifacts and gives you another one(s).

**Comment by SoundSSGood** [comment]
> * that dialog should have new message btw, in place of H3 "you possess all components...

Right. Will add.

**Comment by by003** [comment]
I think the button can be added here. 
image

**Comment by IvanSavenko** [comment]
> I think some players will ignore the warning information. It still can be considered.

And even more will not notice the button. 
And even more will be playing with no fusable artifacts but with unnecessary (for them) button.

**Comment by krs0** [comment]
2 combined artifacts could collide, same with 2 fused ones, same with 1 fused and one combined.

Do not see the need of an extra button. Simple warning should be ok.

**Pull request merged**
