### PR TITLE
Launcher improvements for 1.3

### LINKED ISSUE #1336: Extra helper buttons in launcher
Embed buttons like "report bug/suggestion" in VCMI launcher that open browser and redirect to appropriate pages. I would also add button for joining slack.

### LINKED ISSUE #1978: Launcher fails to display download progress
**Describe the bug**
When installing mods via Launcher, vcmi fails to display current download progress, progress bar stays at "unknown" for the entire time of download

**To Reproduce**
1. Start Launcher
2. Install any mod, preferably big one, e.g. WoG or HotA
3. Look at download progress bar at the bottom

**Expected behavior**
Launcher should display progress bar with text like "Downloading file, %d out of %d kbytes downloaded"

**Actual behavior**
Progress bar never initializes with download size

**Did it work earlier?**
Definitely worked originally, may have been broken when mods hosting was moved to github

**Version**
 - VCMI 1.2

### LINKED ISSUE #2140: Language auto select first start
**Describe the bug**
Just one little thing that would be nice: When you start VCMI for the first time, the "FirstLaunch" dialog appears. It would be nice if the system language of the operating system would be preselected there. If language not exists in vcmi, then english.

### PR DESCRIPTION
**Pull request by IvanSavenko**
Resolving launcher-related issues in 1.3 milestone.

Progress:
- [x] Allow player to select UI scaling in Launcher
- [x] Block resolution selector when in borderless fullscreen mode
- [x] Add description tooltip for fullscreen mode selector
- [x] Add separate Allied Adventure Map AI, set to VCAI by default
- [x] Consider what to do with mod repositories selection
- [x] Remove progress bar from setup page
- [x] Re-export translations

Resolved issues:
- Fixes #2140 
- Fixes #1978 
- Fixes #1336 

Issue to fix in separate PR's:
- #2046 
- #1787

### CODE REVIEW

**Comment by heroesiiifan** [comment]
Can you also add:
- finnish (cp1252)
- portuguese (cp1252)
- swedish (cp1252)
- turkish (cp1254)

Fan translations exist for all of them (even if not 100% finished). Have packed these into mods.

**Comment by heroesiiifan** [comment]
@IvanSavenko  Before merging: hungarian (cp1250) 

;)

**Comment by dydzio0614** [comment]
Minor suggestions to consider:
1. Rename "Help" button to "About / Help"
2. Add "report bug / suggestion" button which redirects directly to github issues (listing social media does not make it clear enough where to do low-effort bug report without joining slack/discord)
3. Maybe adding target framerate option into launcher would make changing it less obscure for people who want "original 30 FPS" or have screen with 120+ Hz refresh rate

**Comment by IvanSavenko** [comment]
@dydzio0614 
1. I would rather use one word - we don't have a lot of space available in here, especially considering tranlations. As to whether "help" or "about". "Help" seems to be more common for menus - "About" usually goes into submenu.
2. Noted, will do
3. Noted, will do. Might also be more suitable for mobiles (perhaps even set 30 fps as default?) to reduce load / save battery life.
4. Will think about it. Can't say that I am happy with current layout but have yet to come with good option - this screen does not uses a lot of space anyway.
5. Noted, will do.

**Comment by dydzio0614** [comment]
About 4... I mean behavior when resizing window up/down

**Comment by dydzio0614** [comment]
obraz

**Comment by IvanSavenko** [comment]
How would you suggest to change that? 
- Just remove empty space at the top?
- Remove empty space at the top as well as between "Our Community" and "Build Information"?

**Comment by dydzio0614** [comment]
1st option

**Pull request merged**
