### PR TITLE
convert line endings from CRLF (Windows) to LF (Linux/Unix)

### PR DESCRIPTION
**Pull request by josch**
Mixed line endings cause problems when exporting patches with git-format-patch and then trying to "git am" a patch with mixed and non-matching line endings. In such a situation git will fail to apply the patch.

This commit runs the dos2unix tools on the remaining files with CRLF (\r\n) line endings to convert them to line-feeds (\n) only.

Files that are Windows specific like *.vcxproj and *.props files were not converted.

Closes: #3073

### CODE REVIEW

**Review by IvanSavenko — APPROVED** [review]
Is everyone OK with this change? If yes - then I'll merge it in a day or two.

**Comment by josch** [comment]
Note, that the downside of this change is, that this will break `git blame` for a while because this commit changes literally every line with the CRLF line ending in the sources and headers.

**Comment by josch** [comment]
Also, change touches literally 98k lines of code. Would you like me to provide a small script that you can use to verify that I did not smuggle in any change other than the change in line endings?

**Comment by rilian-la-te** [comment]
@josch we can use exclude for this. I cannot remember exact syntax now, but I remember than I once used it for XServer changes)

**Comment by josch** [comment]
> @josch we can use exclude for this. I cannot remember exact syntax now, but I remember than I once used it for XServer changes)

It is `git blame --ignore-rev=a1a5bc28c2`. Thanks, I didn't know that option exists! This makes a change like this much less threatening, I think. There is also the option `--ignore-revs-file` which would allow to collect drastic in terms of lines of code but uninteresting in terms of functionality changes like this one.

**Comment by josch** [comment]
Here is how you can make sure that I didn't put any backdoor anywhere in those 98k changed lines. Use this script:

```sh
#!/bin/sh

for f in AI/BattleAI/BattleAI.cpp AI/BattleAI/StdInc.cpp AI/BattleAI/StdInc.h AI/BattleAI/main.cpp AI/EmptyAI/CEmptyAI.cpp AI/EmptyAI/CEmptyAI.h AI/EmptyAI/StdInc.cpp AI/EmptyAI/StdInc.h AI/EmptyAI/main.cpp AI/GeniusAI.brain AI/StupidAI/StdInc.cpp AI/StupidAI/StdInc.h AI/StupidAI/StupidAI.cpp AI/StupidAI/StupidAI.h AI/StupidAI/main.cpp AI/VCAI/AIUtility.cpp AI/VCAI/VCAI.cpp AI/VCAI/VCAI.h AUTHORS.h CCallback.cpp CCallback.h ChangeLog.md Global.h Mods/vcmi/Data/s/std.verm Mods/vcmi/Data/s/testy.erm Mods/vcmi/config/vcmi/german.json Mods/vcmi/config/vcmi/rmg/hdmod/blockbuster.JSON Mods/vcmi/config/vcmi/rmg/hdmod/extreme.JSON Mods/vcmi/config/vcmi/rmg/hdmod/extreme2.JSON Mods/vcmi/config/vcmi/rmg/hdmod/poorJebus.JSON Mods/vcmi/config/vcmi/rmg/hdmod/reckless.JSON Mods/vcmi/config/vcmi/rmg/hdmod/roadrunner.JSON Mods/vcmi/config/vcmi/rmg/hdmod/superslam.JSON Mods/vcmi/config/vcmi/rmg/heroes3/readyOrNot.JSON Mods/vcmi/config/vcmi/rmg/heroes3/worldsAtWar.JSON Mods/vcmi/config/vcmi/rmg/heroes3unused/gauntlet.JSON client/CGameInfo.cpp client/CGameInfo.h client/CMT.cpp client/CMusicHandler.cpp client/CMusicHandler.h client/CPlayerInterface.cpp client/CPlayerInterface.h client/CVideoHandler.cpp client/CVideoHandler.h client/Client.cpp client/Client.h client/NetPacksClient.cpp client/PlayerLocalState.cpp client/PlayerLocalState.h client/StdInc.cpp client/StdInc.h client/adventureMap/AdventureMapInterface.cpp client/adventureMap/AdventureMapInterface.h client/adventureMap/AdventureMapWidget.cpp client/adventureMap/AdventureMapWidget.h client/adventureMap/AdventureOptions.cpp client/adventureMap/AdventureOptions.h client/adventureMap/CResDataBar.cpp client/adventureMap/CResDataBar.h client/adventureMap/MapAudioPlayer.cpp client/adventureMap/MapAudioPlayer.h client/battle/BattleActionsController.cpp client/battle/BattleActionsController.h client/battle/BattleAnimationClasses.cpp client/battle/BattleAnimationClasses.h client/battle/BattleConstants.h client/battle/BattleEffectsController.cpp client/battle/BattleEffectsController.h client/battle/BattleFieldController.cpp client/battle/BattleFieldController.h client/battle/BattleInterface.cpp client/battle/BattleInterface.h client/battle/BattleInterfaceClasses.cpp client/battle/BattleInterfaceClasses.h client/battle/BattleObstacleController.cpp client/battle/BattleObstacleController.h client/battle/BattleProjectileController.cpp client/battle/BattleProjectileController.h client/battle/BattleRenderer.cpp client/battle/BattleRenderer.h client/battle/BattleSiegeController.cpp client/battle/BattleSiegeController.h client/battle/BattleStacksController.cpp client/battle/BattleStacksController.h client/battle/BattleWindow.cpp client/battle/BattleWindow.h client/battle/CreatureAnimation.cpp client/battle/CreatureAnimation.h client/gui/CGuiHandler.cpp client/gui/CGuiHandler.h client/gui/CIntObject.cpp client/gui/CIntObject.h client/gui/CursorHandler.cpp client/gui/CursorHandler.h client/gui/MouseButton.h client/gui/TextAlignment.h client/mapView/IMapRendererContext.h client/mapView/IMapRendererObserver.h client/mapView/MapRenderer.cpp client/mapView/MapRenderer.h client/mapView/MapRendererContext.cpp client/mapView/MapRendererContext.h client/mapView/MapRendererContextState.cpp client/mapView/MapRendererContextState.h client/mapView/MapView.cpp client/mapView/MapView.h client/mapView/MapViewActions.cpp client/mapView/MapViewActions.h client/mapView/MapViewCache.cpp client/mapView/MapViewCache.h client/mapView/MapViewController.cpp client/mapView/MapViewController.h client/mapView/MapViewModel.cpp client/mapView/MapViewModel.h client/mapView/mapHandler.cpp client/mapView/mapHandler.h client/render/CAnimation.cpp client/render/CAnimation.h client/render/CBitmapHandler.cpp client/render/CBitmapHandler.h client/render/CDefFile.cpp client/render/CDefFile.h client/render/Canvas.cpp client/render/Canvas.h client/render/ColorFilter.cpp client/render/ColorFilter.h client/render/Colors.h client/render/Graphics.cpp client/render/Graphics.h client/render/ICursor.h client/render/IImage.h client/render/IImageLoader.h client/renderSDL/CursorHardware.cpp client/renderSDL/CursorHardware.h client/renderSDL/CursorSoftware.cpp client/renderSDL/CursorSoftware.h client/renderSDL/SDLImage.cpp client/renderSDL/SDLImage.h client/renderSDL/SDLImageLoader.cpp client/renderSDL/SDLImageLoader.h client/renderSDL/SDL_Extensions.cpp client/renderSDL/SDL_Extensions.h client/resource.h client/windows/CCastleInterface.cpp client/windows/CCastleInterface.h client/windows/CCreatureWindow.cpp client/windows/CCreatureWindow.h client/windows/CHeroWindow.cpp client/windows/CHeroWindow.h client/windows/CKingdomInterface.h client/windows/CMessage.cpp client/windows/CMessage.h client/windows/CQuestLog.cpp client/windows/CQuestLog.h client/windows/CSpellWindow.cpp client/windows/CSpellWindow.h client/windows/GUIClasses.cpp client/windows/GUIClasses.h config/artifacts.json config/bonuses.json config/campaignMedia.json config/commanders.json config/difficulty.json config/obstacles.json config/schemas/skill.json config/schemas/spell.json docs/Readme.md launcher/StdInc.cpp launcher/StdInc.h launcher/main.cpp launcher/main.h lib/AI_Base.h lib/CArtHandler.cpp lib/CArtHandler.h lib/CBonusTypeHandler.cpp lib/CBonusTypeHandler.h lib/CBuildingHandler.cpp lib/CBuildingHandler.h lib/CConfigHandler.cpp lib/CConfigHandler.h lib/CConsoleHandler.cpp lib/CConsoleHandler.h lib/CCreatureHandler.cpp lib/CCreatureHandler.h lib/CCreatureSet.cpp lib/CCreatureSet.h lib/CGameInterface.cpp lib/CGameInterface.h lib/CGeneralTextHandler.cpp lib/CGeneralTextHandler.h lib/CHeroHandler.cpp lib/CHeroHandler.h lib/CScriptingModule.h lib/CSkillHandler.h lib/CSoundBase.h lib/CStack.cpp lib/CStack.h lib/CStopWatch.h lib/CThreadHelper.cpp lib/CThreadHelper.h lib/CTownHandler.cpp lib/CTownHandler.h lib/Color.h lib/CondSh.h lib/ConstTransitivePtr.h lib/GameConstants.h lib/GameSettings.cpp lib/GameSettings.h lib/IBonusTypeHandler.h lib/IGameCallback.cpp lib/IGameCallback.h lib/IGameEventsReceiver.h lib/JsonDetail.cpp lib/JsonNode.cpp lib/JsonNode.h lib/Languages.h lib/NetPacks.h lib/NetPacksBase.h lib/NetPacksLib.cpp lib/Point.h lib/Rect.cpp lib/Rect.h lib/ResourceSet.cpp lib/ResourceSet.h lib/StartInfo.h lib/StdInc.cpp lib/StdInc.h lib/TextOperations.cpp lib/TextOperations.h lib/UnlockGuard.h lib/VCMI_Lib.cpp lib/VCMI_Lib.h lib/battle/AccessibilityInfo.cpp lib/battle/AccessibilityInfo.h lib/battle/BattleAction.cpp lib/battle/BattleAction.h lib/battle/BattleAttackInfo.cpp lib/battle/BattleAttackInfo.h lib/battle/BattleHex.cpp lib/battle/BattleHex.h lib/battle/BattleInfo.cpp lib/battle/BattleInfo.h lib/battle/CBattleInfoCallback.cpp lib/battle/CBattleInfoCallback.h lib/battle/CBattleInfoEssentials.cpp lib/battle/CBattleInfoEssentials.h lib/battle/CObstacleInstance.cpp lib/battle/CObstacleInstance.h lib/battle/CPlayerBattleCallback.cpp lib/battle/CPlayerBattleCallback.h lib/battle/ReachabilityInfo.cpp lib/battle/ReachabilityInfo.h lib/battle/SideInBattle.cpp lib/battle/SideInBattle.h lib/battle/SiegeInfo.cpp lib/battle/SiegeInfo.h lib/bonuses/Bonus.cpp lib/bonuses/Bonus.h lib/campaign/CampaignHandler.cpp lib/campaign/CampaignHandler.h lib/constants/EntityIdentifiers.cpp lib/constants/EntityIdentifiers.h lib/constants/Enumerations.h lib/constants/NumericConstants.h lib/gameState/CGameState.h lib/int3.h lib/mapping/CMap.cpp lib/mapping/CMap.h lib/mapping/CMapDefines.h lib/mapping/CMapInfo.cpp lib/mapping/CMapInfo.h lib/mapping/MapFeaturesH3M.cpp lib/mapping/MapFeaturesH3M.h lib/mapping/MapFormatH3M.cpp lib/mapping/MapFormatH3M.h lib/mapping/MapFormatJson.cpp lib/mapping/MapFormatJson.h lib/mapping/MapReaderH3M.cpp lib/mapping/MapReaderH3M.h lib/modding/CModHandler.cpp lib/modding/CModHandler.h lib/registerTypes/RegisterTypes.cpp lib/registerTypes/RegisterTypes.h lib/registerTypes/TypesClientPacks1.cpp lib/registerTypes/TypesClientPacks2.cpp lib/registerTypes/TypesMapObjects1.cpp lib/registerTypes/TypesMapObjects2.cpp lib/registerTypes/TypesServerPacks.cpp lib/vcmi_endian.h license.txt mapeditor/StdInc.cpp mapeditor/StdInc.h scripting/erm/ERMInterpreter.cpp scripting/erm/ERMInterpreter.h scripting/erm/ERMParser.cpp scripting/erm/ERMParser.h scripting/erm/ERMScriptModule.cpp scripting/erm/ERMScriptModule.h scripting/erm/StdInc.cpp scripting/erm/StdInc.h server/CGameHandler.h server/NetPacksServer.cpp server/StdInc.cpp server/StdInc.h server/queries/CQuery.cpp server/queries/CQuery.h test/StdInc.cpp test/StdInc.h; do
dos2unix "$f"
done

cat <<END | git commit -a --file=- --author="Johannes Schauer Marin Rodrigues <josch@mister-muffin.de>" --date="Thu Oct 19 16:19:09 2023 +0200"
convert line endings from CRLF (Windows) to LF (Linux/Unix)

Mixed line endings cause problems when exporting patches with
git-format-patch and then trying to "git am" a patch with mixed and
non-matching line endings. In such a situation git will fail to apply
the patch.

This commit runs the dos2unix tools on the remaining files with CRLF
(\r\n) line endings to convert them to line-feeds (\n) only.

Files that are Windows specific like *.vcxproj and *.props files were
not converted.

Closes: #3073
END
```

Run this script on the `develop` branch in the vcmi git and then create a format-patch like this:

    git format-patch --abbrev=10 -1

And then make sure that your local commit is identical to the one from this pull request:

   curl --location --silent https://github.com/vcmi/vcmi/pull/3078.patch | diff -u - 0001-convert-line-endings-from-CRLF-Windows-to-LF-Linux-U.patch

**Comment by josch** [comment]
Oh and also: I do not deserve to have my name attached to 98k lines of code. So if you like, I can just change the `Author` field of my commit to a value you devs prefer.

**Comment by Laserlicht** [comment]
If this creates merging conflicts (I'm not sure for line breaks), then we should merge open and ready PR's first. An make this change on top of this to avoid double work with resolving conflicts.

**Comment by josch** [comment]
> If this creates merging conflicts (I'm not sure for line breaks), then we should merge open and ready PR's first. An make this change on top of this to avoid double work with resolving conflicts.

That's a good point! Yes, unless git is specifically told to ignore line endings, this will create merge conflicts because git (unless told otherwise) will respect and keep line endings. To avoid merge conflicts, I could also change this merge request to **exclude** those files that are changed in the currently open pull request. Then, at a later time, once the other pull requests are merged, I can file another pull request to fix the remaining files. The downside of breaking this change into more than one commit, would be that users of `git blame` would have to ignore more than one commit.

**Comment by josch** [comment]
So I went through the currently open pull requests. I ignored #347, #1554 and #2019 because those were auto-generated changes just like this one and can thus easily be re-done. The remaining 34 pull requests touch 112 files that this pull request also touches. If you prefer, we can do this in stages and let this pull request first convert the 197 files that are not changed by any of the other open pull requests (except for the 3 i mentioned initially) and do the remaining 112 files later after their respective pull requests got merged.

**Comment by SoundSSGood** [comment]
It would be nice to check for CRLF in CI. This way it will be possible to check for CRLF in future commits.

**Comment by josch** [comment]
> It would be nice to check for CRLF in CI. This way it will be possible to check for CRLF in future commits.

Good point. I can file another pull request using the following shell function to find all files containing CRLF:

    find . -path ./.git -prune -o -path ./osx -prune -o -path ./android -prune -o -type f \
    -not -name '*.png' -and -not -name '*.vcxproj*' -and -not -name '*.props' \
    -not -name '*.wav' -not -name '*.ico' -print0 | xargs -0 grep -l -z -P '\x0d\x0a'

It includes some obvious exceptions to the rule.

Where in the current CI actions do you think would that check fit best? I did not see other linters being run.

**Comment by Alexander-Wilms** [comment]
> Where in the current CI actions do you think would that check fit best? I did not see other linters being run.

@josch The JSON is being validated during CI. You could add another stage before https://github.com/vcmi/vcmi/blob/develop/.github/workflows/github.yml#L148

```yml
    - name: Check line endings
      if: ${{ startsWith(matrix.preset, 'linux-clang-test') }}
      run: |
        find . -path ./.git -prune -o -path ./osx -prune -o -path ./android -prune -o -type f \
        -not -name '*.png' -and -not -name '*.vcxproj*' -and -not -name '*.props' \
        -not -name '*.wav' -not -name '*.ico' -print0 | xargs -0 grep -l -z -P '\x0d\x0a'
```

But the command should return a value other than 0 if it finds files containing CRLF.

**Comment by IvanSavenko** [comment]
In regards to conflicts. Will probably do following tomorrow:
- merge all completed open PR's
- merge this PR manually. Depending on how merge tool will handle line endings in conflicts, I might drop some changes from this PR and apply them separately later.

**Comment by IvanSavenko** [comment]
If somebody can add check to CI that would be great, but probably as a separate RP

**Pull request merged**
