### PR TITLE
Pack linux gcc builds

### PR DESCRIPTION
**Pull request by Nordsoft91**

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
wanted to test this in my Debian VM, but unfortunately I have no idea how to install proper boost dependency: apt has 1.67, but the binary requires 1.71.

**Review by kambala-decapitator — APPROVED** [review]
the PR itself looks good

**Comment by kambala-decapitator** [comment]
testing on Mint:
```
> ./vcmilauncher 
./vcmilauncher: error while loading shared libraries: libvcmi.so: cannot open shared object file: No such file or directory

> ldd vcmilauncher 
	libvcmi.so => not found
	libboost_filesystem.so.1.71.0 => not found
	...

> LD_LIBRARY_PATH=../lib/vcmi ./vcmilauncher
./vcmilauncher: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory

> apt list --installed '*boost*'
Listing... Done
libboost-filesystem1.74.0/jammy,now 1.74.0-14ubuntu3 amd64 [installed]
...
```

tried symlinking all required boost libs, however it doesn't launch still...

```
> ln -s /lib/x86_64-linux-gnu/libboost_thread.so.1.74.0 ../lib/vcmi/libboost_thread.so.1.71.0

> LD_LIBRARY_PATH=../lib/vcmi ./vcmilauncher
./vcmilauncher: error while loading shared libraries: libminizip.so.1: cannot open shared object file: No such file or directory

> apt install libminizip1
> LD_LIBRARY_PATH=../lib/vcmi ./vcmilauncher
./vcmilauncher: symbol lookup error: ../lib/vcmi/libvcmi.so: undefined symbol: _ZN5boost10filesystem6detail28directory_iterator_constructERNS0_18directory_iteratorERKNS0_4pathEPNS_6system10error_codeE
```

seems exact boost version is required =(

**Comment by IvanSavenko** [comment]
Closing as not required (anymore)

FYI - packaging binaries & libraries this way will only work on exactly same set of libraries, e.g. same distribution.
For distro-agnostic builds you need to package a LOT of dependencies with you - boost, SDL, even libstdc++ (aka c++ library)

**Pull request closed without merging**
