### PR TITLE
NKAI: fix patrolling heroes never retreat and town danger evaluation

### PR DESCRIPTION
**Pull request by nullkiller**
Patrolling heroes should never retreat
Visiting town is also considered when evaluating hero strength

### CODE REVIEW

**Comment by dydzio0614** [comment]
hmmmm what about heroes that stand in garrisons? also something to consider but not neceseeraily as part of this PR

**Comment by nullkiller** [comment]
When hero stands in garrison and attacked will it merge armies as with town?

**Comment by dydzio0614** [comment]
It is not exactly about merging - I wonder if AI can be fooled to attack hero by putting 1 creature to the garrison or something

**Comment by nullkiller** [comment]
No, hero is always checked in this case. Town is only because it was merging garrison and hero. In case there is garrison hero merging will not happen and it will be possible to kill visiting one

**Pull request merged**
