### PR TITLE
Removed space after Torosar hero name

### PR DESCRIPTION
**Pull request by krs0**

### CODE REVIEW

**Comment by heroesiiifan** [comment]
@krs0 @misiokles 

Keep in mind, that with this change all translation mods have to be updated for 1.4 like this: https://github.com/vcmi-mods/german-translation/commit/091a880a32f5fe88c7f647b7166a0c6a3c09676b

**Comment by misiokles** [comment]
Shit, indeed :(

**Comment by krs0** [comment]
Will do it. Thanks for the heads up.

**Comment by krs0** [comment]
"Small" problem... 1.4 branches do not exist for the other translation mods

**Comment by heroesiiifan** [comment]
I can create the branches...

**Comment by heroesiiifan** [comment]
@misiokles @IvanSavenko 
can you make me also admin of:
- https://github.com/vcmi-mods/german-translation
- https://github.com/vcmi-mods/mega-pack-rus
- https://github.com/vcmi-mods/h3-for-vcmi-englisation

I want also to create branches there and make it default. But for these 3 I cannot.

**Comment by krs0** [comment]
could not do it for vietnamese... some def file gets automatically changed in my repo. @heroesiiifan Could you please change that one?

**Comment by heroesiiifan** [comment]
Done. Only Russian and English is missing. -> Need 1.4 Repo.

**Pull request merged**
